### ISSUE TITLE
Slime and Swank Versions Differ

### ISSUE THREAD

**Issue by srt19170** [slime/slime#125]
I recently started getting an error message when starting Slime that the Slime and Swank versions differ.  Xach over on Reddit suggested that the most likely cause was having an old version of Slime in the load path, and this turned out to be the case.  However, deleting the old version of Slime did not fix the problem. 

That's because the version of Slime is set at compile time in slime.el:

```
(setq slime-protocol-version
      (eval-when-compile (slime-changelog-date)))
```

so the problem isn't fixed until slime.el is recompiled.

That seems like a confusing behavior to me (and apparently others, as I found when I tried to Google a solution).  It would be better if Slime set its version at load time.

**Comment by capitaomorte** [comment]
FWIW, while cherry-picking this into SLY, f8ab3d3 is wrong I think. What if someone byte-compiles `slime.el` and doesn't load it? It'll affect the load-path and everything that depends on it, before the library is actually loaded.

**Comment by luismbo** [comment]
That's a use case I hadn't considered. However, in order for a byte-compiled-but-not-loaded slime.el to affect the load-path, one would have to call `slime-setup` manually, which is not something people should do anymore. Seems too far fetched to happen, but Murphy's law is ruthless, I guess. :-)

**Comment by capitaomorte** [comment]
`slime-path` is also used by other stuff, not just load-path setting. Namely version mismatch detection, the very point of this issue and also choosing which swank-loader.lisp to use for the next `M-x slime`. That's not as far-fetched as calling `slime-setup`. 

But I agree do it *is* a little off, though perfectly legal, to byte-compile-and-not-load. Have a look at SLY's version which uses `byte-compile-current-file` to do the right thing. It's akin to CL's `*COMPILE-FILE-TRUENAME*`. Or maybe `*COMPILE-FILE-PATHNAME*`...never know the difference.

**Comment by luismbo** [comment]
Right, the other uses of `slime-path` make it less far fatched. `byte-compile-current-file` seems like the right thing to do. (Also, using `locate-library` to determine `slime-path` sounds wrong.) Will fix, thanks.

**Comment by chuchana** [comment]
I got the same error for a different reason: I had installed slime via quicklisp and ac-slime installed it from melpa as a dependency later on. Removing it and restarting Emacs fixed the problem.
