### ISSUE TITLE
swank 2.26 on ccl 1.6

### ISSUE THREAD

**Issue by informatimago** [slime/slime#132]
The class ccl::shadowed-typecase-clause doesn't exist in all ccl versions (notably not on 1.6); Therefore it fails to load swank-ccl.lisp; Adding the following #+ line helps:

;; Needed because `ccl:report-compiler-warning' would return
;; "Nonspecific warning".
# +#.(cl:if (cl:ignore-errors (cl:find-class 'ccl::shadowed-typecase-clause)) '(:and) '(:or))

(defmethod compiler-warning-short-message ((c ccl::shadowed-typecase-clause))
  (princ-to-string c))

**Comment by omero72** [comment]
Hello

Where do we put those 5 lines, into "slime-2.13/swank-loader.lisp or into swank/ccl.lisp or into some file else? And btw, what does #+#. mean? Thanks. 
 
;; Needed because `ccl:report-compiler-warning' would return
;; "Nonspecific warning".
#+#.(cl:if (cl:ignore-errors (cl:find-class 'ccl::shadowed-typecase-clause)) '(:and) '(:or))
(defmethod compiler-warning-short-message ((c ccl::shadowed-typecase-clause))
(princ-to-string c))

**Comment by informatimago** [comment]
> On 16 Mar 2015, at 17:24, Ömer <notifications@github.com> wrote:
> 
> Hello
> 
> Where do we put those 5 lines, into "slime-2.13/swank-loader.lisp or into swank/ccl.lisp or into some file else? And btw, what does #+#. mean? Thanks.
> 
> ;; Needed because `ccl:report-compiler-warning' would return
> ;; "Nonspecific warning".
> #+#.(cl:if (cl:ignore-errors (cl:find-class 'ccl::shadowed-typecase-clause)) '(:and) '(:or))
> (defmethod compiler-warning-short-message ((c ccl::shadowed-typecase-clause))
> (princ-to-string c))
> 


#. http://www.lispworks.com/documentation/HyperSpec/Body/02_dhf.htm
#+ http://www.lispworks.com/documentation/HyperSpec/Body/02_dhq.htm

-- 
__Pascal J. Bourguignon__

**Comment by omero72** [comment]
Thank you for the comment. So now it's apperant that they're read-time operators that's fine. Btw I still couldn't get past  "Class named CCL::SHADOWED-TYPECASE-CLAUSE not found error."

**Comment by informatimago** [comment]
> On 16 Mar 2015, at 19:26, Ömer <notifications@github.com> wrote:
> 
> Thank you for the comment. So now it's apperant that they're read-time operators that's fine. Btw I still couldn't get past "Class named CCL::SHADOWED-TYPECASE-CLAUSE not found error."
> 


This error is surprising, because of the ignore-errors operator.

This code is for CCL, since only CCL has the CCL package.

Trying to intern a symbol in the CCL package in another implementation will signal a read-time error before ignore-errors may act, so you could get a package not found error in another implementation, but there's no way you could get a class not found error from the code showed in the previous messages.

-- 
__Pascal J. Bourguignon__

**Comment by omero72** [comment]
I've added those suggested 5 lines to ./swank.lisp ,  ./swank-loader.lisp , ./swank/ccl.lisp , and I still couldn't get rid of the same error as I tried to start compiling swank. Here are my data 
OSX 10.7.4, Emacs-24.4.1, slime-2.13, ClozureCL-1.10
and my screenshot showing where and how I get the error: http://i.hizliresim.com/dnJWrQ.png
The tutorial I follow is : https://www.youtube.com/watch?v=_B_4vhsmRRI (for quick preview, fast forward to 2:30 where I start to put the statements at my inferior-lisp mode on Emacs)

**Comment by omero72** [comment]
I've replaced CCL-1.10 with the CMUCL version 20D Unicode and it works like a piece of cake.This rules out my way of configuration. Now the CCL-1.10's incompatibilty with slime-2.13 continues. The issue still not solved.

**Comment by luismbo** [comment]
@omero72 do you have a fix? A pull request would be awesome.

**Comment by stassats** [comment]
Works with the latest ccl.
