### ISSUE TITLE
"M-x slime" fails with "Recursive-load"

### ISSUE THREAD

**Issue by Elzair** [slime/slime#181]
When I try to start-up slime, via `M-x slime`,  I get the following error.

   byte-code: Recursive load: "~/.emacs.d/.emacs.d/elpa/slime-20140818.918/slime.elc", "~/.emacs.d/.emacs.d/elpa/slime-20140818.918/contrib/slime-fancy.elc", "~/.emacs.d/.emacs.d/elpa/slime-20140818.918/slime.elc", "~/.emacs.d/.emacs.d/elpa/slime-20140818.918/contrib/slime-fancy.elc", "~/.emacs.d/.emacs.d/elpa/slime-20140818.918/slime.elc", "~/.emacs.d/.emacs.d/elpa/slime-20140818.918/contrib/slime-fancy.elc", "~/.emacs.d/.emacs.d/elpa/slime-20140818.918/slime.elc", "~/.emacs.d/.emacs.d/elpa/slime-20140818.918/contrib/slime-fancy.elc", "~/.emacs.d/.emacs.d/elpa/slime-20140818.918/slime.elc"

**Comment by duncanmak** [comment]
@Elzair How did you fix this? I'm seeing this too.

**Comment by duncanmak** [comment]
I figured it out - I had an old install of `slime-repl` sitting around.
