### ISSUE TITLE
Can't load contribs with SBCL 1.2.6 under Windows

### ISSUE THREAD

**Issue by fpopineau** [slime/slime#212]
Everything is in the title. The log is provided below. Albeit I have no idea if it is a problem with SBCL or with SLIME.
I'll post on sbcl-bugs too.

Fabrice

This is SBCL 1.2.6, an implementation of ANSI Common Lisp.
More information about SBCL is available at http://www.sbcl.org/.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.

WARNING: the Windows port is fragile, particularly for multithreaded
code.  Unfortunately, the development team currently lacks the time
and resources this platform demands.
- (load "c:/home/.emacs.d/vendor/slime/swank-loader.lisp")

T
- (swank-loader:init :delete nil :reload nil :load-contribs t)
  <pre>
  STYLE-WARNING: redefining EMACS-INSPECT (#<SB-PCL:SYSTEM-CLASS T>) in DEFMETHOD
  STYLE-WARNING:
  redefining THREAD-FOR-EVALUATION (#<STRUCTURE-CLASS
                                     MULTITHREADED-CONNECTION>
                                   #<SB-MOP:EQL-SPECIALIZER
                                     {1006620BB3}>) in DEFMETHOD
  WARNING: change in instance length of class PRETTY-STREAM:
  current length: 26
  new length: 27
  STYLE-WARNING: redefining SB-PRETTY:PRETTY-STREAM-P in DEFUN
  STYLE-WARNING: redefining SB-PRETTY::MAKE-PRETTY-STREAM in DEFUN
  Help! 11 nested errors. SB-KERNEL:_MAXIMUM-ERROR-DEPTH_ exceeded.
  Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1003037563}>
  Help! 11 nested errors. SB-KERNEL:_MAXIMUM-ERROR-DEPTH_ exceeded.
  Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1003037563}>
  </pre>

**Comment by terminal625** [comment]
@luismbo could you provide the "correct implementation" link? the gmane link is dead and id like to help track it down

**Comment by luismbo** [comment]
@terminal625 Not sure what you mean by "correct implementation", but the
gmane link pointed to this discussion:
https://sourceforge.net/p/sbcl/mailman/message/33102827/ HTH
