### ISSUE TITLE
slime.el can't be byte-compiled using gnu emacs 25.0.50 

### ISSUE THREAD

**Issue by stefanhusmann** [slime/slime#225]
Byte compiling slime.el with emacs 25.0.50.1 both from master of from xwidget branch does not work. The compilation hangs without error message, but also without getting ready.

**Comment by luismbo** [comment]
Works for me with `"GNU Emacs 25.0.50.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F34))\n of 2015-01-13 on builder10-9.porkrind.org"` from http://emacsformacosx.com/builds.

I tried both `M-x byte-compile-file RET slime.el RET` and `make`.

Could it be an Emacs bug on your platform? Which platform is that?

**Comment by stefanhusmann** [comment]
I am on Arch Linux 64 Bit. I used my PKGBUILD from https://aur.archlinux.org/packages/emacs-xwidget-git/.
I must take back my statement for emacs from trunk. Only the xwidget branch seems to be affected.

**Comment by luismbo** [comment]
Oh, OK. Tagged as `emacs-bug` instead then. Let us know if it turns out to be SLIME's fault somehow!

**Comment by stefanhusmann** [comment]
The maintainer of the xwidget branch of emacs did a major merge with the master branch and now the problem is gone. Thanks for your support.
