### ISSUE TITLE
SLIME and Swank Fail on a MIPS Architecture

### ISSUE THREAD

**Issue by haziz** [slime/slime#226]
I am trying to use Emacs with [SLIME](https://common-lisp.net/project/slime/) and Swank on an [Imagination Creator CI20](http://blog.imgtec.com/powervr/mips-creator-ci20-development-board-now-available) Mips board to learn Common Lisp. I am using SBCL and Clisp as my compiler/interpreter (mainly SBCL which is usually set as the inferior-lisp-mode); I did however test this with both SBCL and Clisp set as the inferior-lisp-mode and it fails with both. I tried to run SLIME but it invariably fails while trying to load or compile a Swank file. The error message from one of the attempts suggests that it is having difficulty with the architecture (Mips - little endian). I am running the default install of Debian 7 Wheezy (Mipsel) the board comes with.

I tried this with [SLIME](https://common-lisp.net/project/slime/) installed via apt-get from the Debian repository, another time with the Melpa install of SLIME and lastly another attempt with the Github git repository (latest) of SLIME. They all fail though the error messages are sometimes subtly different. It fails with both Emacs 23 and 24.

I am attaching the error messages/blurb from my attempt with the Github repository of SLIME, using SBCL as the compiler. SBCL was installed from the SBCL repository since Mipsel Wheezy seems not to have it in the Debian repository. It seems to be a failry old version of SBCL but is the latest binary for the architecture on the SBCL website. SBCL runs fine as a REPL from the command line.

```
(progn (load "/usr/share/common-lisp/source/slime/swank-loader.lisp" :verbose t) (funcall (read-from-string "swank-loader:init")) (funcall (read-from-string "swank:start-server") "/tmp/slime.4482"))

This is SBCL 1.0.28, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* 
; loading #P"/usr/share/common-lisp/source/slime/swank-loader.lisp"
WARNING:
   No architecture feature found in (POWERPC PPC X86 X86-64 X86_64 AMD64 I686
                                     I586 I486 PC386 IAPX386 SPARC64 SPARC
                                     HPPA64 HPPA ARM PENTIUM3 PENTIUM4 JAVA-1.4
                                     JAVA-1.5 JAVA-1.6 JAVA-1.7).

debugger invoked on a SB-C::INPUT-ERROR-IN-COMPILE-FILE:
  READ failure in COMPILE-FILE:
    SB-INT:SIMPLE-READER-PACKAGE-ERROR at 5799 (line 150, column 52) on #<SB-SYS:FD-STREAM for "file /usr/share/common-lisp/source/slime/swank-loader.lisp" {50007F71}>:
      Symbol "APPLY-OUTPUT-TRANSLATIONS" not found in the ASDF package.

Type HELP for debugger help, or (SB-EXT:QUIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit debugger, returning to top level.

(SB-C::READ-FOR-COMPILE-FILE
 #<SB-SYS:FD-STREAM for "file /usr/share/common-lisp/source/slime/swank-loader.lisp" {50007F71}>
 5418)
0] 
```

**Comment by luismbo** [comment]
Did you uninstall the Debian version before using SLIME from melpa/git?

**Comment by haziz** [comment]
@luismbo Yes I did initially before trying to run the Melpa version. I did later reinstall it, I currently have both it and the github version of slime in place. Will retry after apt-get removing it again tonight. I tried various permutations of running it many times (over 10 overall) and most were done with the Debian version uninstalled. The error message above however was likely when I had both the Debian and github versions installed and with a path to slime variable set in my .emacs file pointing to the github version. Will uninstall the Debian version and retry after I get home tonigtt.

**Comment by attila-lendvai** [comment]
i think it's because the ASDF version in that SBCL is too old.

**Comment by haziz** [comment]
I retried with the Debian copy of slime unintstalled and it still fails. Essentially the same error message above (I can upload the current error message). I tried the Quicklisp version of Slime and SBCL fails but interestingly CLISP manag

**Comment by haziz** [comment]
I seem to have accidentally closed this "issue", this was unintended, it is still an ongoing problem. See above. Thanks.

**Comment by luismbo** [comment]
@haziz have you tried upgrading ASDF as Attila suggested? Your version of SBCL is pretty old too.

**Comment by haziz** [comment]
I no longer use the MiPs board that often, so I will close this problem, although it was never satisfactorily solved for me.
