### ISSUE TITLE
xrefs stopped working when the file has in-package

### ISSUE THREAD

**Issue by stassats** [slime/slime#227]
With SBCL:
(in-package :cl-user)

(defun foo ()
  (dddddds 10))
C-c C-w C-c
=>
Argument X is not a NUMBER: NIL
which is returned by source-path-stream-position

**Comment by luismbo** [comment]
@melisgl does this ring a bell?

**Comment by stassats** [comment]
Sorry, I fixed it before the bell.

**Comment by luismbo** [comment]
Heh, thanks. :)
