### ISSUE TITLE
SLIME binds M-n and M-p in ordinary editing buffer

### ISSUE THREAD

**Issue by mrkkrp** [slime/slime#229]
SLIME binds <kbd>M-n</kbd> and <kbd>M-p</kbd> to `slime-next-note` and `slime-previous-note`. It's OK for interactive REPL, where it makes sense, but it also binds the functions in `lisp-mode`. So, when user hits <kbd>M-n</kbd> or <kbd>M-p</kbd> in ordinary editing buffer, he/she is always presented with "No next note." or "No previous note.". This is incorrect, there is no reason to bind these functions in ordinary editing buffer. Some people bind <kbd>M-n</kbd> and <kbd>M-p</kbd> to some editing functions, SLIME overwrites this.

**Comment by luismbo** [comment]
If you compile a buffer (and compilation notes are  issued), it will be annotated. So, the bindings are not useless. If you want to binding those keys to something else, you can do it via lisp-mode-hook. Does that make sense?

**Comment by mrkkrp** [comment]
Thank you for your explanation.
