### ISSUE TITLE
swank/sbcl::compiler-policy breaks on new sbcl (1.2.12 or so)

### ISSUE THREAD

**Issue by 3b** [slime/slime#246]
sbcl stores policy as a struct rather than a list now, breaking `C-u C-c C-c` and similar in `swank/sbcl::compiler-policy`. http://thread.gmane.org/gmane.lisp.steel-bank.devel/19060 suggests using `(sb-c::policy-quality policy quality)` instead of `(cdr (assoc quality policy))`, which seems to work.

**Comment by luismbo** [comment]
Thanks, fixed in b7771ce.

**Comment by luismbo** [comment]
FTR, turns out this particular change was unintended in SBCL. Reverted by 4b948ca3d85ae92eced253564879c51920b55360.
