### ISSUE TITLE
SLIME 2.14 error: 'There is no package named "SWANK-REPL" .'

### ISSUE THREAD

**Issue by egarrulo** [slime/slime#247]
I have upgraded from SLIME 2.9 to 2.14 and, now, starting the inferior lisp raises this error with both CCL and SBCL.  There is such a package in *contrib*, but SLIME doesn't see it.

I am attaching the stack-trace for CCL.  Thanks for your assistance.

--

    There is no package named "SWANK-REPL" .
       [Condition of type CCL::NO-SUCH-PACKAGE]

    Restarts:
     0: [CONTINUE] Retry finding package with name "SWANK-REPL".
     1: [USE-VALUE] Find specified package instead of "SWANK-REPL" .
     2: [MAKE-NICKNAME] Make "SWANK-REPL" be a nickname for package "SWANK".
     3: [RETRY-LOAD] Retry loading #P"/home/egarrulo/emacs/lisp/site-lisp/slime/slime-2.14/contrib/swank-presentations.lisp"
     4: [SKIP-LOAD] Skip loading #P"/home/egarrulo/emacs/lisp/site-lisp/slime/slime-2.14/contrib/swank-presentations.lisp"
     5: [LOAD-OTHER] Load other file instead of #P"/home/egarrulo/emacs/lisp/site-lisp/slime/slime-2.14/contrib/swank-presentations.lisp"
     --more--

    Backtrace:
      0: (CCL::%PARSE-TOKEN #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/home/egarrulo/emacs/lisp/site-lisp/slime/slime-2.14/contrib/swank-presentations.lisp"/6 UTF-8) #x18DBB6EE> #\s (NIL))
      1: (CCL::%PARSE-EXPRESSION #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/home/egarrulo/emacs/lisp/site-lisp/slime/slime-2.14/contrib/swank-presentations.lisp"/6 UTF-8) #x18DBB6EE> #\s (NIL))
      2: (CCL::%READ-LIST-EXPRESSION #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/home/egarrulo/emacs/lisp/site-lisp/slime/slime-2.14/contrib/swank-presentations.lisp"/6 UTF-8) #x18DBB6EE> (NIL) #\))
      3: (CCL::READ-LIST #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/home/egarrulo/emacs/lisp/site-lisp/slime/slime-2.14/contrib/swank-presentations.lisp"/6 UTF-8) #x18DBB6EE> NIL #\))
      4: (CCL::%PARSE-EXPRESSION #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/home/egarrulo/emacs/lisp/site-lisp/slime/slime-2.14/contrib/swank-presentations.lisp"/6 UTF-8) #x18DBB6EE> #\( (NIL))
      5: (CCL::%READ-LIST-EXPRESSION #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/home/egarrulo/emacs/lisp/site-lisp/slime/slime-2.14/contrib/swank-presentations.lisp"/6 UTF-8) #x18DBB6EE> (NIL) #\))
      6: (CCL::READ-LIST #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/home/egarrulo/emacs/lisp/site-lisp/slime/slime-2.14/contrib/swank-presentations.lisp"/6 UTF-8) #x18DBB6EE> NIL #\))
      7: (CCL::%PARSE-EXPRESSION #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/home/egarrulo/emacs/lisp/site-lisp/slime/slime-2.14/contrib/swank-presentations.lisp"/6 UTF-8) #x18DBB6EE> #\( NIL)
      8: (CCL::%READ-FORM #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/home/egarrulo/emacs/lisp/site-lisp/slime/slime-2.14/contrib/swank-presentations.lisp"/6 UTF-8) #x18DBB6EE> NIL (NIL))
      9: (CCL::READ-INTERNAL #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/home/egarrulo/emacs/lisp/site-lisp/slime/slime-2.14/contrib/swank-presentations.lisp"/6 UTF-8) #x18DBB6EE> NIL (NIL) NIL)
     10: (CCL::READ-RECORDING-SOURCE #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/home/egarrulo/emacs/lisp/site-lisp/slime/slime-2.14/contrib/swank-presentations.lisp"/6 UTF-8) #x18DBB6EE> :EOFVAL (NIL) :..
     11: ((:INTERNAL CCL::WITH-COMPILATION-UNIT-BODY CCL::LOAD-FROM-STREAM))
     12: (CCL::CALL-WITH-COMPILATION-UNIT #<COMPILED-LEXICAL-CLOSURE (:INTERNAL CCL::WITH-COMPILATION-UNIT-BODY CCL::LOAD-FROM-STREAM) #xB60B4906> :OVERRIDE NIL)
     13: (CCL::LOAD-FROM-STREAM #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/home/egarrulo/emacs/lisp/site-lisp/slime/slime-2.14/contrib/swank-presentations.lisp"/6 UTF-8) #x18DBB6EE> NIL)
     14: (CCL::%LOAD #P"/home/egarrulo/emacs/lisp/site-lisp/slime/slime-2.14/contrib/swank-presentations.lisp" NIL NIL :ERROR :DEFAULT NIL)
     15: (LOAD #P"/home/egarrulo/emacs/lisp/site-lisp/slime/slime-2.14/contrib/swank-presentations.lisp" :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST :ERROR :EXTERNAL-FORMAT :DEFAULT :PRESERVE-OPTIMIZ..
     16: (REQUIRE SWANK-IO-PACKAGE::SWANK-PRESENTATIONS #P"/home/egarrulo/emacs/lisp/site-lisp/slime/slime-2.14/contrib/swank-presentations.lisp")
     17: (SWANK:SWANK-REQUIRE (SWANK-IO-PACKAGE::SWANK-INDENTATION SWANK-IO-PACKAGE::SWANK-ASDF SWANK-IO-PACKAGE::SWANK-TRACE-DIALOG SWANK-IO-PACKAGE::SWANK-PACKAGE-FU SWANK-IO-PACKAGE::SWANK-PRESENTATIONS ..)..
     18: (CCL::CALL-CHECK-REGS SWANK:SWANK-REQUIRE (SWANK-IO-PACKAGE::SWANK-INDENTATION SWANK-IO-PACKAGE::SWANK-ASDF SWANK-IO-PACKAGE::SWANK-TRACE-DIALOG SWANK-IO-PACKAGE::SWANK-PACKAGE-FU ..)))
     19: (CCL::CHEAP-EVAL (SWANK:SWANK-REQUIRE ..)))
     20: (SWANK:EVAL-FOR-EMACS (SWANK:SWANK-REQUIRE ..)) "COMMON-LISP-USER" 2)
     21: ((:INTERNAL SWANK::SPAWN-WORKER-THREAD))
     22: (SWANK/BACKEND:CALL-WITH-DEBUGGER-HOOK #<Compiled-function SWANK:SWANK-DEBUGGER-HOOK #x18C9DA8E> #<Compiled-function (:INTERNAL SWANK::SPAWN-WORKER-THREAD) (Non-Global)  #x18C7135E>)
     23: ((:INTERNAL SWANK::SPAWN-WORKER-THREAD))
     24: (CCL::RUN-PROCESS-INITIAL-FORM #<PROCESS worker(8) [Active] #x18CE5026> (#<COMPILED-LEXICAL-CLOSURE (:INTERNAL CCL::%PROCESS-RUN-FUNCTION) #x18CE4EDE>))
     25: ((:INTERNAL (CCL::%PROCESS-PRESET-INTERNAL (PROCESS))) #<PROCESS worker(8) [Active] #x18CE5026> (#<COMPILED-LEXICAL-CLOSURE (:INTERNAL CCL::%PROCESS-RUN-FUNCTION) #x18CE4EDE>))
     26: ((:INTERNAL CCL::THREAD-MAKE-STARTUP-FUNCTION))

**Comment by attila-lendvai** [comment]
FTR, there's this on top of ```swank-presentations.lisp```:

```
(eval-when (:compile-toplevel :load-toplevel)
  (swank-require :swank-repl))
```

would it be missing an :execute? it shouldn't...

you may try to delete the fasl's also. i'm not sure that the swank loading infrastructure fully tracks dependencies and timestamps.

**Comment by egarrulo** [comment]
I have added *:execute* and it works.  Thanks :-)

(I had already tried deleting the FASL files.)

**Comment by luismbo** [comment]
@egarrulo what contribs are you using?

**Comment by egarrulo** [comment]
@luismbo Those that come with SLIME 2.14. I have downloaded the *.tar.gz* archive of the 2.14 release and there is a *contrib* folder inside.

**Comment by egarrulo** [comment]
@luismbo Or better: I suppose that that is what SLIME is using.  At least, I modified the *swank-presentations.lisp* inside that directory and SLIME started working again.

**Comment by luismbo** [comment]
@egarrulo yes, but none of the contribs are loaded by default. You to request them explicitly. What's your SLIME configuration like in your .emacs?

**Comment by egarrulo** [comment]
I use *slime-company* -- a third-party contrib -- that loads *swank-arglists* (see https://github.com/anwyn/slime-company/blob/master/slime-company.el).

**Comment by luismbo** [comment]
@egarrulo Can you paste your config?

**Comment by egarrulo** [comment]
The following snippet of code will cause the error when run with *emacs -Q* after the new FASL files have been generated (that is: the first time, the code runs fine).  You will need the latest versions of *company-mode* and *slime-company* to run the snippet:

https://github.com/anwyn/slime-company/releases
https://github.com/company-mode/company-mode/releases

Tested on Emacs 24.5 on Debian GNU/Linux.

    (add-to-list 'load-path "/home/egarrulo/emacs/lisp/site-lisp/slime/slime-2.14")
    (add-to-list 'load-path "/home/egarrulo/emacs/lisp/site-lisp/slime-company/slime-company-0.8")
    (add-to-list 'load-path "/home/egarrulo/emacs/lisp/site-lisp/company-mode/company-mode-0.8.12")

    (defun string-join (list delimiter)
      (mapconcat 'identity list delimiter))

    (defvar slime-net-coding-system 'utf-8-unix)
    (defvar slime-net-coding-system 'iso-latin-1-unix) ;This has to be fixed, but I don't know yet for what
    (defvar slime-startup-animation nil)

    (require 'slime-autoloads)

    (add-to-list 'slime-contribs 'slime-fancy)

    (defvar slime-lisp-implementations
      `((ccl ("ccl" "--terminal-encoding" "utf-8"))))

    (defun slime-nth-implementation-to-shell-command (index)
      (string-join (mapcar #'shell-quote-argument (cadr (nth index slime-lisp-implementations)))
		      " "))

    (setq inferior-lisp-program (slime-nth-implementation-to-shell-command 0))

    (slime-setup '(
		   slime-fancy
		   slime-asdf
		   slime-banner
		   slime-company
		   slime-indentation))

    (defmacro defslime-start (name lisp &optional coding-system args)
      "Define an alias to start SLIME with a specific implementation."
      `(defun ,name ()
	 (interactive)
	 (slime-start :program ,lisp ,@(when args (list :program-args args))
		      :coding-system (or ',coding-system 'utf-8-unix))))
    (defslime-start ccl "ccl" utf-8-unix '("--terminal-encoding" "utf-8"))

    (ccl)

**Comment by tarballs-are-good** [comment]
Was there any additional resolution on this? I am running into it too, using no other config than that provided by `quicklisp-slime-helper`.

**Comment by luismbo** [comment]
@tarballs-are-good does Attila's fix work for you? https://github.com/slime/slime/issues/247#issuecomment-109580877

**Comment by luismbo** [comment]
@tarballs-are-good, @egarrulo, after loading slime, what does `(swank::find-module :swank-repl)` return?

**Comment by luismbo** [comment]
d7e4f8d should fix this issue, but it would still be interesting to know why the contrib is being loaded uncompiled.

**Comment by djr7C4** [comment]
This issue may have resurfaced again (either that or I'm just doing something wrong).  I encounter it with both slime 2.17 and 85e2e614b3adf6e6295ee07f14ca44db4512a409.  To reproduce, evaluate the following code with emacs -Q:

    (package-initialize)
    (require 'slime)
    
    (setq inferior-lisp-program "sbcl")
    
    (require 'slime-repl)

The run M-x slime and M-x slime-repl.  Enter 1 in the repl and press enter.  This results in the *slime-error* buffer:

    Invalid protocol message:
    Package SWANK-REPL does not exist.
    
      Line: 1, Column: 36, File-Position: 36
    
      Stream: #<SB-IMPL::STRING-INPUT-STREAM {1002F3A683}>
    
    (:emacs-rex (swank-repl:listener-eval "1
    ") "COMMON-LISP-USER" :repl-thread 2)

**Comment by luismbo** [comment]
@djr7C4 Alas, the contribs are not meant to be `require`d. Maybe one day they'll work like that, but for now `(setq slime-contribs '(slime-repl))` is the way to do it.

**Comment by djr7C4** [comment]
I can confirm that it works fine now.  Sorry for the false report and thanks for the response and your work on slime.
