### ISSUE TITLE
SLIME 2.14: "Invalid function" error in `slime-find-asd-file`

### ISSUE THREAD

**Issue by egarrulo** [slime/slime#248]
The `cl-loop` in `slime-find-asd-file` contains a `return` form.  This causes an `(invalid-function return)` error in Emacs 24.5.1.  The fix is to rename `return` as `cl-return`, like this:

    (defun slime-find-asd-file (directory system-names)
      "Tries to find an ASDF system definition file in the
    `directory' and returns it if it's in `system-names'."
      (let ((asd-files
             (directory-files (file-name-directory directory) nil "\.asd$")))
        (cl-loop for system in asd-files
                 for candidate = (file-name-sans-extension system)
                 when (cl-find candidate system-names :test #'string-equal)
                 do (cl-return candidate))))

**Comment by luismbo** [comment]
Thanks @egarrulo.
