### ISSUE TITLE
Renaming of `slime-fontify-string` has broken third-party package.

### ISSUE THREAD

**Issue by egarrulo** [slime/slime#249]
The function `slime-fontify-string` in `slime-autodoc` has been renamed as `slime-autodoc--fontify` (see https://github.com/slime/slime/commit/930f364853e518419978082c9a8455071e537b59).  This change has broken the third-party package `slime-company` (see https://github.com/anwyn/slime-company), that uses such function.

Since the original name didn't make apparent that the function was meant as private, I propose that the original name be restored.

Temporary fix:

    ;; Make `slime-company` work with SLIME 2.14.
    (eval-after-load 'slime-autodoc
      '(fset 'slime-fontify-string 'slime-autodoc--fontify))

**Comment by luismbo** [comment]
@ellerh does renaming `slime-autodoc--fontify` to `slime-autodoc-fontify` (and perhaps adding an obsolete function alias for `slime-fontify-string`) sound sensible?

**Comment by ellerh** [comment]
Yes,
```(define-obsolete-function-alias 'slime-fontify-string 'slime-autodoc--fontify
  "SLIME 2.10")```
is probably the path of least resistence.

**Comment by luismbo** [comment]
@egarrulo Thanks, I've added the alias you suggested. I think slime-company should probably implement its own fontify function since `slime-autodoc--fontify` is tailored towards slime-autodoc's usage. For example, I can image its highlight mechanism being improved and having to change the protocol. If you agree, perhaps you could submit a bug report for slime-company in that direction?

**Comment by egarrulo** [comment]
Thanks for the fix.  Sure, I will submit a bug report for `slime-company`.  Actually, I was unsure about where to file this bug report. It seemed more appropriate to file it here here because `slime-autodoc` had changed its public interface without an obvious pressing reason. But now I understand that `slime-autodoc` has a different functionality than what I had thought.  Cheers.
