### ISSUE TITLE
Debugger generates error when examining stack frames of traced CCL functions

### ISSUE THREAD

**Issue by rgivan1** [slime/slime#255]
We are using Slime to control a CCL process under Emacs.  We have found that the debugger encounters an error if we attempt to examine the stack frame generated for a traced function <b>foo</b> when <pre>(trace (foo :break t))</pre> is in effect.

While we are not at all knowledgeable about slime or swank, we have found that the following change fixes the issue (new code in bold):

<pre>
(defun function-name-package (name)
  (<b>if (and (consp name) (eq (car name) 'ccl::traced))
      (function-name-package (second name))</b>
      (etypecase name
        (null nil)
        (symbol (symbol-package name))
        ((cons (eql setf) symbol) (symbol-package (cadr name)))
        ((cons (eql :internal)) (function-name-package (car (last name))))
        ((cons (and symbol (not keyword)) (cons list null))
         (symbol-package (car name)))
        (standard-method (function-name-package (ccl:method-name name))))))
</pre>

This occurs in the file slime/swank/ccl.lisp, although we are currently still using an older release (downloaded April 2013) where this was swank-ccl.lisp and that is where we have produced the problem.  We provide this information in case someone more knowledgeable about slime, swank, and ccl can ascertain that this fix should be added to the distribution.

**Comment by luismbo** [comment]
Thanks! I noticed the setf case wasn't being handled correctly either so I fixed that too.
