### ISSUE TITLE
completion at slime-repl annoying with completion-in-region

### ISSUE THREAD

**Issue by csrhodes** [slime/slime#272]
I don't understand what's going on.  Reporting in the hope that other people can reproduce it.

If I type a few characters at the slime REPL, then hit `TAB`, `slime-indent-and-complete-symbol` is called, more or less as I expect.

However, at that point subsequent `TAB` keypresses don't call `slime-indent-and-complete-symbol` again; instead they call `completion-at-point`.  On my system, this is because `completion-in-region-mode` has been put in the overriding mode alist, and it doesn't get removed until something happens, such as switching buffers or actually performing a completion.  But: `completion-at-point` doesn't know about the nice slime completion functions, so performing a completion is pretty painful.

Firstly, is this just me, or does anyone else see this behaviour?  Secondly, what's the right fix?  Maybe to have completion at the slime repl work entirely through the `completion-at-point` infrastructure through a buffer-local variable rather than through a local binding of `completion-at-point-functions` in `slime-complete-symbol`?

Help?

**Comment by ellerh** [comment]
Hmm. Good detective work. I added code that sets the buffer local `completion-at-point-functions` in `slime-repl-mode`.  Maybe `slime-mode` should do that too; it's less clear there as `slime-mode` is a minor-mode.

**Comment by luismbo** [comment]
Does https://github.com/slime/slime/commit/f8cffb16aed4979a6c5c1026e92e293842b4de61 (and perhaps subsequent commits) fix this issue?

**Comment by csrhodes** [comment]
Luís Oliveira <notifications@github.com> writes:

> Does f8cffb1 (and perhaps subsequent commits) fix this issue?

By eye, I'd say yes; I haven't actually tried yet, though.

Christophe

**Comment by stassats** [comment]
For one thing, it broke configuration via slime-complete-symbol-function, it now only consults slime-completion-at-point-functions.

**Comment by stassats** [comment]
Oh, and when you do configure it via slime-completion-at-point-functions, it can't be changed without killing the repl buffer.

**Comment by ellerh** [comment]
I don't see any way to customize `completion-in-region` without setting the buffer local variable `completion-at-point-functions`. I think we can either go back to our own completion code without `completion-in-region` or break backward compatibility.  It's unfortunate that `completion-at-point-functions` needs to be set because that is quite a bit harder to deal with for minor modes than a key binding.  On the plus side, `completion-at-point-functions` is now the standard way to customize completion.

**Comment by stassats** [comment]
That commit seems to have fixed slime-complete-symbol-function, but now
```(setq slime-completion-at-point-functions '(slime-fuzzy-complete-symbol))``` stopped having an effect. I've never used it before, no idea if it was broken previously or not.

**Comment by ellerh** [comment]
> (setq slime-completion-at-point-functions '(slime-fuzzy-complete-symbol)) stopped having an effect.

The functions in `slime-completion-at-point-functions` should follow the same conventions as the elements of `completion-at-point-functions`.  I.e. the function should return a triple `(beg end completion-table)` or a function or nil.  In your case something like `(setq slime-completion-at-point-functions (list (lambda () #'slime-fuzzy-complete-symbol)))` should work, assuming that `slime-complete-symbol-function` is nil.

**Comment by stassats** [comment]
I tried using `slime-completion-at-point-functions' only after `slime-complete-symbol-function' stopped working, and it did the job. Now I went back to `slime-complete-symbol-function', but this may have broken configuration for people who were using `slime-completion-at-point-functions'.

**Comment by ellerh** [comment]
> but this may have broken configuration for people who were using slime-completion-at-point-functions.

This was an issue for one week. Hopefully not too many people updated SLIME during that period.
