### ISSUE TITLE
Slime don't work after previous update

### ISSUE THREAD

**Issue by karlkorp** [slime/slime#273]
(progn (load "/home/karlkorp/.emacs.d/elpa/slime-20151011.201/swank-loader.lisp" :verbose t) (funcall (read-from-string "swank-loader:init")) (funcall (read-from-string "swank:start-server") "/tmp/slime.16142"))

This is SBCL 1.1.14.debian, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* 
; loading #P"/home/karlkorp/.emacs.d/elpa/slime-20151011.201/swank-loader.lisp"
WARNING: SWANK/BACKEND also exports the following symbols:
  (SWANK/BACKEND:MACROEXPAND-ALL SWANK/BACKEND:BUFFER-FIRST-CHANGE
   SWANK/BACKEND:SLDB-STEP-INTO SWANK/BACKEND:DESCRIBE-DEFINITION
   SWANK/BACKEND:DESCRIBE-SYMBOL-FOR-EMACS SWANK/BACKEND:MAKE-LOCK
   SWANK/BACKEND:MAKE-WEAK-VALUE-HASH-TABLE SWANK/BACKEND:UNPROFILE
   SWANK/BACKEND:FIND-REGISTERED SWANK/BACKEND:FRAME-CALL
   SWANK/BACKEND:COMPILER-MACROEXPAND SWANK/BACKEND:SET-STREAM-TIMEOUT
   SWANK/BACKEND:GUESS-EXTERNAL-FORMAT SWANK/BACKEND:WRAP
   SWANK/BACKEND:SWANK-COMPILE-FILE SWANK/BACKEND:EVAL-CONTEXT
   SWANK/BACKEND:RECEIVE-IF SWANK/BACKEND:FUNCTION-NAME
   SWANK/BACKEND:BACKGROUND-SAVE-IMAGE SWANK/BACKEND:EVAL-IN-FRAME
   SWANK/BACKEND:EMACS-CONNECTED SWANK/BACKEND:EXEC-IMAGE
   SWANK/BACKEND:ACTIVATE-STEPPING SWANK/BACKEND:PREFERRED-COMMUNICATION-STYLE
   SWANK/BACKEND:PROFILE-RESET SWANK/BACKEND:INTERRUPT-THREAD
   SWANK/BACKEND:GDB-INITIAL-COMMANDS SWANK/BACKEND:CALLS-WHO
   SWANK/BACKEND:WHO-SPECIALIZES SWANK/BACKEND:CALL-WITH-DEBUGGING-ENVIRONMENT
   SWANK/BACKEND:CLOSE-SOCKET SWANK/BACKEND:SLDB-STEP-OUT
   SWANK/BACKEND:SLDB-STEPPER-CONDITION-P SWANK/BACKEND:GRAY-PACKAGE-NAME
   SWANK/BACKEND:FORMAT-STRING-EXPAND SWANK/BACKEND:MAKE-FD-STREAM
   SWANK/BACKEND:SOCKET-FD SWANK/BACKEND:SPAWN SWANK/BACKEND:FIND-THREAD
   SWANK/BACKEND:FIND-DEFINITIONS SWANK/BACKEND:CURRENT-THREAD
   SWANK/BACKEND:VALID-FUNCTION-NAME-P SWANK/BACKEND:CREATE-SOCKET
   SWANK/BACKEND:WHO-CALLS SWANK/BACKEND:CALL-WITH-DEBUGGER-HOOK
   SWANK/BACKEND:ACCEPT-CONNECTION SWANK/BACKEND:REGISTER-THREAD
   SWANK/BACKEND:ADD-SIGIO-HANDLER SWANK/BACKEND:PROFILED-FUNCTIONS
   SWANK/BACKEND:WAIT-FOR-INPUT SWANK/BACKEND:COMMAND-LINE-ARGS
   SWANK/BACKEND:TYPE-SPECIFIER-P SWANK/BACKEND:LIST-CALLERS
   SWANK/BACKEND:KILL-THREAD SWANK/BACKEND:SLDB-BREAK-ON-RETURN
   SWANK/BACKEND:THREAD-ATTRIBUTES SWANK/BACKEND:FRAME-PACKAGE
   SWANK/BACKEND:RECEIVE SWANK/BACKEND:PATHNAME-TO-FILENAME
   SWANK/BACKEND:UNWRAP SWANK/BACKEND:MAKE-INPUT-STREAM SWANK/BACKEND:ARGLIST
   SWANK/BACKEND:DEFAULT-DIRECTORY SWANK/BACKEND:LIST-CALLEES
   SWANK/BACKEND:INSTALL-DEBUGGER-GLOBALLY SWANK/BACKEND:SLDB-STEP-NEXT
   SWANK/BACKEND:FRAME-RESTARTABLE-P SWANK/BACKEND:SWANK-COMPILE-STRING
   SWANK/BACKEND:SEND SWANK/BACKEND:COMPUTE-BACKTRACE
   SWANK/BACKEND:WHO-REFERENCES SWANK/BACKEND:CONDITION-EXTRAS
   SWANK/BACKEND:PROFILE-REPORT SWANK/BACKEND:MAKE-WEAK-KEY-HASH-TABLE
   SWANK/BACKEND:TOGGLE-TRACE SWANK/BACKEND:FRAME-VAR-VALUE
   SWANK/BACKEND:DESCRIBE-PRIMITIVE-TYPE SWANK/BACKEND:DISASSEMBLE-FRAME
   SWANK/BACKEND:PRINT-CONDITION SWANK/BACKEND:SLDB-BREAK-AT-START
   SWANK/BACKEND:DUP SWANK/BACKEND:CALL-WITH-LOCK-HELD
   SWANK/BACKEND:REMOVE-FD-HANDLERS SWANK/BACKEND:THREAD-STATUS
   SWANK/BACKEND:SET-DEFAULT-INITIAL-BINDING SWANK/BACKEND:FIND-SOURCE-LOCATION
   SWANK/BACKEND:LISP-IMPLEMENTATION-TYPE-NAME SWANK/BACKEND:WHO-BINDS
   SWANK/BACKEND:WRAPPED-P SWANK/BACKEND:RETURN-FROM-FRAME
   SWANK/BACKEND:THREAD-ALIVE-P SWANK/BACKEND:CALL-WITH-USER-BREAK-HANDLER
   SWANK/BACKEND:WHO-MACROEXPANDS SWANK/BACKEND:SET-DEFAULT-DIRECTORY
   SWANK/BACKEND:FRAME-SOURCE-LOCATION SWANK/BACKEND:REMOVE-SIGIO-HANDLERS
   SWANK/BACKEND:DEFAULT-READTABLE-ALIST SWANK/BACKEND:PROFILE
   SWANK/BACKEND:MAKE-OUTPUT-STREAM SWANK/BACKEND:COMPILER-MACROEXPAND-1
   SWANK/BACKEND:LISP-IMPLEMENTATION-PROGRAM SWANK/BACKEND:HASH-TABLE-WEAKNESS
   SWANK/BACKEND:FIND-EXTERNAL-FORMAT SWANK/BACKEND:UTF8-TO-STRING
   SWANK/BACKEND:FRAME-CATCH-TAGS SWANK/BACKEND:STRING-TO-UTF8
   SWANK/BACKEND:INSTALL-SIGINT-HANDLER SWANK/BACKEND:UNPROFILE-ALL
   SWANK/BACKEND:FILENAME-TO-PATHNAME SWANK/BACKEND:RESTART-FRAME
   SWANK/BACKEND:THREAD-ID SWANK/BACKEND:PRINT-FRAME
   SWANK/BACKEND:ADD-FD-HANDLER SWANK/BACKEND:CALL-WITH-SYNTAX-HOOKS
   SWANK/BACKEND:INITIALIZE-MULTIPROCESSING SWANK/BACKEND:THREAD-NAME
   SWANK/BACKEND:LOCAL-PORT SWANK/BACKEND:CHARACTER-COMPLETION-SET
   SWANK/BACKEND:WHO-SETS SWANK/BACKEND:FRAME-LOCALS
   SWANK/BACKEND:PROFILE-PACKAGE SWANK/BACKEND:ALL-THREADS
   SWANK/BACKEND:CALL-WITH-COMPILATION-HOOKS SWANK/BACKEND:SAVE-IMAGE
   SWANK/BACKEND:GETPID)
See also:
  The ANSI Standard, Macro DEFPACKAGE
  The SBCL Manual, Variable *ON-PACKAGE-VARIANCE*

; file: /home/karlkorp/.emacs.d/elpa/slime-20151011.201/swank/sbcl.lisp
; in: DEFMETHOD SEXP-IN-BOUNDS-P (SB-IMPL::COMMA T)
;     (DEFMETHOD SWANK/SOURCE-PATH-PARSER:SEXP-IN-BOUNDS-P
;                ((SWANK/SBCL::S SB-IMPL::COMMA) SWANK/SBCL::I)
;       (= SWANK/SBCL::I 1))
; --> PROGN EVAL-WHEN 
; ==>
;   (SB-PCL::%DEFMETHOD-EXPANDER SWANK/SOURCE-PATH-PARSER:SEXP-IN-BOUNDS-P NIL
;                                ((SWANK/SBCL::S SB-IMPL::COMMA) SWANK/SBCL::I)
;                                ((= SWANK/SBCL::I 1)))
; 
; caught STYLE-WARNING:
;   can't find type for specializer SB-IMPL::COMMA in
;   SB-PCL::PARAMETER-SPECIALIZER-DECLARATION-IN-DEFMETHOD.

; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Lock on package SB-C violated when interning COMMA-EXPR while in package
;     SWANK/SBCL.
;   See also:
;     The SBCL Manual, Node "Package Locks"
;   
;     (in form starting at line: 2001, column: 11, file-position: 79453)
; 
; compilation unit aborted
;   caught 1 fatal ERROR condition
;   caught 1 ERROR condition
;   caught 1 STYLE-WARNING condition
;; 
;; Error while compiling /home/karlkorp/.emacs.d/elpa/slime-20151011.201/swank/sbcl.lisp:
;;   COMPILE-FILE returned NIL.
;; Aborting.
;; *

**Comment by attila-lendvai** [comment]
your SBCL is too old.

you can:
 - unpull this commit from your slime
 - update your sbcl
 - or wait if someone with commit rights considers it worth adding the necessary conditionals to support 2+ years old SBCL versions

**Comment by ellerh** [comment]
Fixed

**Comment by karlkorp** [comment]
Thank you
