### ISSUE TITLE
failed to open slime in the emacs

### ISSUE THREAD

**Issue by sunhang** [slime/slime#281]
In my MacBook(Yosemite 10.10.5),I have use "M-x package-install RET slime RET",to install slime successfully.

And I find two path in my mac.

~/.slime/fasl/2015-06-01/sbcl-1.2.14-darwin-x86-64/.

~/.emacs.d/elpa/slime-20151118.1044/.

Then,I add the code to .emacs.

;slime setup
(add-to-list 'load-path "~/.emacs.d/elpa/slime-20151118.1044/")
(setq inferior-lisp-program "/usr/local/bin/sbcl")
(require 'slime-autoloads)
(slime-setup '(slime-fancy))

Finally,I'm failed to tap M-x slime on a new started emacs.It promps "Searching for program: no such file or directory, lisp".

Gotta make my mind up.As a newbie,I have found many tutorial blog,but has not resovle the progrom.

I can’t find exactly what the problem is.

**Comment by luismbo** [comment]
Did you install SBCL? Is it in `/usr/local/bin/sbcl`?

**Comment by geocar** [comment]
Did you *execute* those lines in your `.emacs` file (e.g. by restarting Emacs or by doing `M-x load-file ~/.emacs`)

**Comment by swuecho** [comment]
try to see if you can run sbcl by:

```
`which sbcl`
```

somehow,  thers is a sbcl in /usr/local/bin/sbcl, but not runnable.

remove it. and then check

```
which sbcl
```


at least, I solve my problem this way.
