### ISSUE TITLE
Can't work with kawa

### ISSUE THREAD

**Issue by s-kostyaev** [slime/slime#294]
% java -cp /usr/share/java/kawa.jar:/home/feofan/.emacs.d/elpa/slime-20160113.630/contrib/swank-kawa.jar:/usr/lib/jvm/java-8-openjdk/lib/tools.jar -agentlib:jdwp=transport=dt_socket,server=y,suspend=n -Xss2M kawa.repl --r7rs -s
Listening for transport dt_socket at address: 35601
#|kawa:1|# (import (swank-kawa))
#|kawa:2|# (create-swank-server 4005)
Listening on port: 4005
connection: Socket[addr=/127.0.0.1,port=47278,localport=4005]
listener: Thread[swank-listener,5,main] 1308444215 chan@207abc3 #<environment main>
attaching: 6345 20
attaching2: com.sun.jdi.ProcessAttach (defaults: pid=, timeout=) {pid=pid=6345, timeout=timeout=20}
canBeModified: #t
canRedefineClasses: #t
canAddMethod: #f
canUnrestrictedlyRedefineClasses: #f
canGetBytecodes: #t
canGetConstantPool: #t
canGetSyntheticAttribute: #t
canGetSourceDebugExtension: #t
canPopFrames: #t
canForceEarlyReturn: #t
canGetMethodReturnValues: #t
canGetInstanceInfo: #t
closing socket: ServerSocket[addr=0.0.0.0/0.0.0.0,localport=4005]
Exception in thread "swank" java.lang.Error: mcase failed tmp
(chan@71b1176b (error java.util.NoSuchElementException NoSuchElementException (java.util.ArrayList$Itr.next(ArrayList.java:854) java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1042) swank-kawa.$N1st(swank-kawa.scm:2442) swank-kawa.requestBreakpoint(swank-kawa.scm:1586) swank-kawa.vmMonitor(swank-kawa.scm:1432) swank-kawa.apply1(swank-kawa.scm:1000) gnu.expr.ModuleBody.applyN(ModuleBody.java:243) swank-kawa.applyN(swank-kawa.scm) gnu.expr.ModuleMethod.applyN(ModuleMethod.java:237) gnu.kawa.functions.ApplyToArgs.applyN(ApplyToArgs.java:141) gnu.mapping.ProcedureN.apply2(ProcedureN.java:39) swank-kawa$frame32.lambda72(swank-kawa.scm:2150) swank-kawa$frame32.apply1(swank-kawa.scm:2148) gnu.expr.ModuleBody.applyN(ModuleBody.java:243) gnu.expr.ModuleMethod.applyN(ModuleMethod.java:237) gnu.kawa.functions.ApplyToArgs.applyN(ApplyToArgs.java:141) gnu.mapping.ProcedureN.apply2(ProcedureN.java:39) swank-kawa$frame31.lambda70(swank-kawa.scm:2141) swank-kawa$frame31.apply0(swank-kawa.scm:2141) gnu.expr.ModuleBody.applyN(ModuleBody.java:241) gnu.expr.ModuleMethod.applyN(ModuleMethod.java:237) gnu.kawa.functions.ApplyToArgs.applyN(ApplyToArgs.java:141) gnu.mapping.ProcedureN.apply1(ProcedureN.java:31) swank-kawa$frame29.lambda66(swank-kawa.scm:2044) swank-kawa$frame29.apply0(swank-kawa.scm:2043) gnu.expr.ModuleMethod.apply0(ModuleMethod.java:207) gnu.mapping.RunnableClosure.run(RunnableClosure.java:80) java.lang.Thread.run(Thread.java:745))))
        at swank.macros.ferror$V(swank-kawa.scm:94)
        at swank-kawa.dispatchEvents(swank-kawa.scm:539)
        at swank-kawa.setupServer(swank-kawa.scm:495)
        at swank-kawa.createSwankServer(swank-kawa.scm:479)
        at atInteractiveLevel-2.run(stdin:2)
        at gnu.expr.ModuleExp.evalModule2(ModuleExp.java:293)
        at gnu.expr.ModuleExp.evalModule(ModuleExp.java:212)
        at kawa.Shell.run(Shell.java:291)
        at kawa.Shell.run(Shell.java:203)
        at kawa.Shell.run(Shell.java:184)
        at kawa.repl.processArgs(repl.java:373)
        at kawa.repl.main(repl.java:793)

**Comment by luismbo** [comment]
Thanks for the report. Are you able to do some debugging on your own?

**Comment by s-kostyaev** [comment]
Yes. But I am newbee in java.

**Comment by luismbo** [comment]
Well, you might be able to get away with debugging in scheme-land only. Good luck.

**Comment by s-kostyaev** [comment]
in swank-kawa.scm:1586 `(! classesByName vm "swank$Mnkawa")` does not return nonempty list.

**Comment by luismbo** [comment]
Discussion carries on in #295
