### ISSUE TITLE
In GNU Clisp no break keys (C-c C-b, C-c C-c) do anything

### ISSUE THREAD

**Issue by cellarweasel** [slime/slime#296]
I've narrowed this down so it is more reproducible. 
This is only on Emacs on Windows. I'm using the native port of emacs not cygwin. 

Original Issue text:
With Clisp neither one does anything and something like (loop) cannot be ended without closing Emacs. 
I've tested this on the windows emacs and found that with SBCL both C-c C-c and C-c C-b work as expected. 
In the Clisp Console Ctrl-c works as expected so it is something about when it's loaded through SLIME.

**Comment by cellarweasel** [comment]
Because this is potentially a CLisp issue and not a SLIME problem there is a alternate ticket in the CLisp ticket queue.

**Comment by luismbo** [comment]
@cellarweasel OK, thanks, keeps us posted. This does seem like an issue on the CLISP side. Last time I checked, CLISP was unmaintained so that might not help.

Where did you get your CLISP binary from?

**Comment by cellarweasel** [comment]
From the sourceforge page that is the official download location from the link on the website.

**Comment by cellarweasel** [comment]
@luismbo After a great deal of thought I believe that this is an interface issue. Clisp receives breaks only when inside of loops but the main REPL ignores them. Unlike Bash or SBCL or so which give a new prompt (bash) or just die (SBCL)  Clisp does not respond at the top level. This may have been a "feature" at one point, but sadly now Clisp is dead.  Land of Lisp uses CLisp and that is what brought me here. The author, Conrad Barski M.D., never does recommend anything except a text editor and the REPL. He even states that indentation is important so he put it in the book, but the REPL doesn't allow it and that putting entire expressions on one line is ok for the readers. 

That is just some perspective on how I got here.

**Comment by cellarweasel** [comment]
Just to be clear, when I say interface I mean a point where two systems, subjects, organizations, etc., meet and interact.
