### ISSUE TITLE
Slime connection refused and  sldb-debugged-continuation void

### ISSUE THREAD

**Issue by ryukinix** [slime/slime#301]
My setup about slime on init.el is:

```
(setq slime-contribs '(slime-fancy))
(setq inferior-lisp-program "/usr/bin/clisp")
```

I tried `sbcl` and don't works too.

After load `slime`, opens ok with clisp, but we hove some weirds messages.
![bug-slime](https://cloud.githubusercontent.com/assets/7642878/13282922/139cc9cc-daca-11e5-99f6-0274ba521dec.png)

Here a more descriptive message
![bug-slime2](https://cloud.githubusercontent.com/assets/7642878/13282923/139ffdd6-daca-11e5-88c8-c240ccfb4a64.png)

And the problem final is that when I try evalute some lisp expression:
![bug-slime3](https://cloud.githubusercontent.com/assets/7642878/13282924/13a7aa5e-daca-11e5-85d7-b32d6a0bcd84.png)

What could be?

**Comment by luismbo** [comment]
Does that happen when you load a fresh Emacs (with the config you mentioned) and run SLIME with `M-x slime`?

**Comment by ryukinix** [comment]
And general, `M-x slime` followed by `M-x slime-connect`.

**Comment by luismbo** [comment]
`M-x slime` is all you need. Don't call `M-x slime-connect` afterwards. That's for more advanced uses where you start SWANK yourself.

**Comment by ryukinix** [comment]
Nice! Sorry for that dumb mistake! I think you can close this issue.

**Comment by luismbo** [comment]
@ryukinix np. Cheers.
