### ISSUE TITLE
slime-secret protection can be bypassed

### ISSUE THREAD

**Issue by zellerin** [slime/slime#302]
The initial connection slime-secret mechanism reads input as a form. This means that even without knowledge of the secret one can execute any command (e.g., pass it `000019(:hello #.(cl:print 'Hi))` as first input to connection instead of secret), or bypass the protection completely (pass it `000017#.(swank::slime-secret)` instead of secret).

The most direct solution is to read, if secret is required, the known number of octets into sequence and just compare them without any interpretation.

I can make a patch if this approach is ok.

**Comment by luismbo** [comment]
That makes sense. I wonder if setting `swank::*validate-input*` to true would be the proper fix for that?

**Comment by zellerin** [comment]
Setting `swank/rpc::*validate-input*` to `T` makes my next repl statement to fail immediately and close connection. And slime would not start after that. Current form of `simple-read` apparently (as the first issue) fails to interpret `:` as a package separator, and keywords are present there. And maybe - just maybe - use of read macros would make that function cleaner.

But if implemented well, it could prevent this particular attack. What appears to immediately work and should fix the issue at hand is locally setting `swank/rpc::*validate-input*` around the call to `decode-message` in `authenticate-client`:
```lisp
(defun authenticate-client (stream)
  (let ((secret (slime-secret))
        (swank/rpc::*validate-input* t)) <-- added
    (when secret
      (set-stream-timeout stream 20)
      (let ((first-val (decode-message stream)))
        (unless (and (stringp first-val) (string= first-val secret))
          (error "Incoming connection doesn't know the password.")))
      (set-stream-timeout stream nil))))
```
On the other hand, any incremental manipulation of the string before it is compared to expected text increases chance of possible mischief.

**Comment by mpsyco** [comment]
Maybe set [\*read-eval*](http://www.lispworks.com/documentation/HyperSpec/Body/v_rd_eva.htm#STread-evalST) to nil?

**Comment by zellerin** [comment]
`*read-eval*`: this is an obvious possibility, but blacklisting individual offending constructs usually means, from my experience, that you forget something (e.g., do we care about local attacker doing DoS attacks on you? If so, is `#1#` a problem? etc). Whitelisting - even if form of current `validate-input` - says more precisely what we expect. (Other thing is what we do when the error is raised - currently, slime does not handle malformed input too well)

But for the password: we know what we exactly expect as first chunk. We know how many octets it should have. So the safest possibility is to just read so many octets and compare that.

**Comment by luismbo** [comment]
@zellerin IIUC, what you're suggesting is something like using `read-packet` instead of `decode-message` to grab the secret?

**Comment by zellerin** [comment]
Almost. Using `read-packet` still enables attacker to force you easily to allocate up to 0xffffff bytes (16MB). It most likely does not matter these days, so may be ok (I do not see a threat model where this amount of memory is relevant for local attacks, but I may be mistaken).

What I had originally in mind was one step deeper - use `(parse-header)`, and then `read-chunk` for `(min provided-length, some-limit)` octets (not password length, to prevent attacker to find it), and compare. One easy way would be add optional `LIMIT` parameter to `read-packet` and then call `read-packet` with this parameter set to something sufficiently large.

But maybe I am too paranoid; even the simple `*validate-input*` (or even `*read-eval*`) fix above will solve the issue in the subject.

**Comment by luismbo** [comment]
@zellerin if we're going to be paranoid about it, `*read-eval*` doesn't guard against *DoS by very big float exponent* and things like that. If you feel comfortable with the `*validate-input*` solution, then perhaps that's a good way to go since that seems fairly simple (now that you've fixed it. :-))).

**Comment by zellerin** [comment]
Good enough for me as an immediate fix, if we have other use cases for `*validate-input*`. If the `*validate-input*` should exist only for this, it is overkill. Do you have plans to have it used more widely?

**Comment by zellerin** [comment]
I would also suggest documenting the security considerations in the manual, so that the situation is clear and further discussion (e.g., if there should be prompt for password on emacs side, or if we should allow per-target password to connect to different servers) is easier. I have no suggestion where it should be and whether it should be @section, @subsection or @footnote, but something like:

@section Security considerations

By default, the only protection of access to your running lisp process is that the port is open only on local interface. If you access remote server, use ssh tunneling for encryption on the fly and port restriction.This still means that anyone who can open connection on that machine can do anything under the privileges of the lisp process.

If this is not desired, you can set up a file called @file{~/.slime-secret} in your home and in home of the user running lisp on remote machine to restrict connection only to those who have the password. The assumption is that if one can snoop communication or read your protected file, he has so high privilege that will not gain by hijacking the process anyway.

This still does not protect against at least two attacks: the local user can still make Lisp process to allocate up to 16MB memory for each connection it opens, and if he can kill the Lisp process (or be faster), he can listen on that port and wait for remote user to connect and reveal the password. It is up to you to evaluate the risks in your environment.
