### ISSUE TITLE
SLIME don't work after updating

### ISSUE THREAD

**Issue by karlkorp** [slime/slime#306]
**; loading #P"/home/*****************/.emacs.d/elpa/slime-20160319.1057/swank-loader.lisp"
; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Lock on package SB-C violated when interning META-INFO while in package
;     KEYWORD.
;   See also:
;     The SBCL Manual, Node "Package Locks"
;   
;     (in form starting at line: 960, column: 68, file-position: 38202)
;; 
;; Error compiling /home/karlkorp/.emacs.d/elpa/slime-20160319.1057/swank/sbcl.lisp:**

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
_$ sbcl --version
SBCL 1.1.14.debian_

**Comment by tohl** [comment]
> $ sbcl --version
> SBCL 1.1.14.debian

your sbcl is too old.

**Comment by karlkorp** [comment]
I must use this (1.1.14) version of SBCL for my application.

**Comment by PuercoPop** [comment]
@karlkorp then have you considered an older version of SLIME? It seems the appropriate thing to do.

**Comment by karlkorp** [comment]
Again, for my work I use an older version of SLIME. SLIME - best IDE (IMHO) for Common Lisp development and it should at least allow me to work comfortably with the old version of the compiler.

**Comment by luismbo** [comment]
@karlkorp does this fix your problem?

```diff
diff --git a/swank/sbcl.lisp b/swank/sbcl.lisp
index 3d21d12..bec0aee 100644
--- a/swank/sbcl.lisp
+++ b/swank/sbcl.lisp
@@ -968,7 +968,10 @@ QUALITIES is an alist with (quality . value)"
 
 (defun setf-expander (symbol)
   (or 
-   #+#.(cl:if (sb-c::meta-info :setf :inverse ()) '(:and) '(:or))
+   #+#.(cl:if (cl:and (cl:find-symbol "META-INFO" :sb-c)
+                      (sb-c::meta-info :setf :inverse ()))
+              '(:and)
+              '(:or))
    (sb-int:info :setf :inverse symbol)
    (sb-int:info :setf :expander symbol)))
 
```

**Comment by luismbo** [comment]
@karlkorp ab6d1bd should fix it. Let us know if it doesn't. Thanks.

**Comment by karlkorp** [comment]
Thank you very much, dear developers. SLIME works now. Very pleased with the speed and quality of your work! Please, don't break backward compatibility for use with older compilers. This is important not only for me but for other developers compelled to work with older compilers.
Thank you very much!!!
