### ISSUE TITLE
slime.el: function 'slime-eval-last-expression-display-output' deprecated?

### ISSUE THREAD

**Issue by rprimus** [slime/slime#307]
Sun Mar 20 19:04:52 GMT 2016

Section 3.2 `Evaluation Commands` of the 2.17 manual makes reference to `slime-eval-last-expression-display-output`,  however this function/key-binding does not exist. 

Looking at the code (`slime.el`), this was commented out in commit 1df1b19d73852017999ee03b028ce53fbadd40c0 (Jan 2009).

If there are no plans to re-implement this, should this be removed from the documentation?

**Comment by luismbo** [comment]
@rprimus fixed! Thanks.
