### ISSUE TITLE
Invoking slime causes simple file error 

### ISSUE THREAD

**Issue by dcguim** [slime/slime#310]
I`ve installed slime through melpa as suggested in the [instructions](https://github.com/slime/slime#quick-setup-instructions) 
My current version of slime is:

     >Status: Installed in `/home/dcoelho/.emacs.d/elpa/slime-20160402.549/'.
     >Version: 20160402.549
     >Requires: cl-lib-0.5, macrostep-0.9
     >Summary: Superior Lisp Interaction Mode for Emacs

Im on a Red Hat Enterprise Linux 7.2 running a Emacs 24.3, 
when I fire up slime with `M-x slime` it displays the following error:
> `#<THREAD "main thread" RUNNING {AF487D1}>:
  attempt to load an empty FASL file:
  "/home/dcoelho/.slime/fasl/2016-04-02/sbcl-1.2.7-linux-x86/sbcl.fasl"`

 >` (SB-FASL::LOAD-AS-FASL #<SB-SYS:FD-STREAM for "file /home/dcoelho/.slime/fasl/2016-04-02/sbcl-1.2.7-linux-x86/sbcl.fasl" {B6BEC31}> NIL NIL) `

I dont have any idea on how to solve this, I tried uninstalling and reinstalling two times and it didnt work, any suggestions?
*obs: Ive uninstalled it by deleting the package through `M-x list-packages` and by deleting the package from ~/.slime*
Thanks,
Dan

**Comment by luismbo** [comment]
It looks like something is wrong with your SBCL installation. If you open SBCL directly from the command line and eval `(require :sb-bsd-sockets)`.

Maybe requiring as root helps (or tweaking the permissions). If that fails try downloading and installing from an official SBCL tarball instead.

**Comment by dcguim** [comment]
Thanks luismbo,
I solved the problem by "installing to a different prefix" as suggested in www.sbcl.org/getting.html in my home folder under my ~/common-lisp directory.

**Comment by jqtruong** [comment]
just ran into this issue (on arch linux, sbcl 1.4.13, slime 2.23) and the fix was to remove `~/.slime`, then entering `M-x slime` (or just `slime` from eshell)
