### ISSUE TITLE
Slime Exceeds max eval depth in process filter

### ISSUE THREAD

**Issue by swflint** [slime/slime#322]
When I attempt to connect to slime (M-x slime), I receive the following error:

    Connecting to Swank on port 43762..
    error in process filter: slime-net-filter: Lisp nesting exceeds `max-lisp-eval-depth'

My Slime config is as follows:

    (add-to-list 'load-path "~/.emacs.d/slime/")
    (require 'slime)
    (slime-setup '(slime-fancy
               slime-banner
               slime-mrepl
               slime-tramp
               slime-xref-browser
               slime-scratch
               slime-sprof
               slime-hyperdoc
               slime-references
               slime-autodoc
               slime-trace-dialog
               slime-repl-ansi-color
               slime-indentation))

    (setf slime-lisp-implementations
          '((sbcl ("sbcl"))
            (ccl ("ccl"))
            (ccl64 ("ccl64"))
            (abcl ("abcl"))))

    (setq slime-sprof-exclude-swank t)

What can/should I do to be able to use slime?

**Comment by attila-lendvai** [comment]
could it be that you have a different version of slime loaded by the CL side and the Emacs side?

**Comment by swflint** [comment]
Explain?  As far as I know, they load from the same source tree.

--
Samuel W. Flint
4096R/266596F4
      (9477 D23E 389E 40C5 2F10  DE19 68E5 318E 2665 96F4)
(λs.s s) λs.s s

**Comment by PuercoPop** [comment]
max-lisp-eval-depth means that the limit of active tail calls has been reached. As emacs lisp doesn't provide TCO it probably means some code in Slime should be rewritten in an iterative fashion.

@swflint Try setting debug-on-error to t before starting slime to get a full backtrace so we could see there the problem occurs.

**Comment by swflint** [comment]
And, I get no backtrace.

--
Samuel W. Flint
4096R/266596F4
      (9477 D23E 389E 40C5 2F10  DE19 68E5 318E 2665 96F4)
(λs.s s) λs.s s

**Comment by swflint** [comment]
All right, now in a fresh emacs, with

    (slime-setup '(slime-fancy
           slime-banner
           slime-mrepl
           slime-scratch
           slime-hyperdoc
           slime-references
           slime-autodoc
           slime-trace-dialog))

As my slime-setup, I have no problems.
