### ISSUE TITLE
Hang when hitting TAB on (read) on debian sid

### ISSUE THREAD

**Issue by phoe-krk** [slime/slime#329]
Emacs hangs when doing the following:

1) Go into Slime REPL, type `(read)` and hit Return.
2) Hit TAB and have it hang.

Someone mentioned that it seems similar to the issue https://github.com/slime/slime/issues/17

I'm on SLIME 2016-04-19, debian sid x64, emacs lucid 24.5.1.

Confirmed also on the following config:
```
GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2016-04-08 on binet, modified by Debian
; SLIME 2016-02-10 ( #<QL-DIST:SYSTEM swank / slime-v2.18 / quicklisp 2016-06-28> )
Linux d 4.6.0-1-amd64 #1 SMP Debian 4.6.1-1 (2016-06-06) x86_64 GNU/Linux
```
And on this config:
```
osx 10.11.5
emacs built from git
GNU Emacs 25.1.50.1 (x86_64-apple-darwin15.5.0, NS appkit-1404.47 Version 10.11.5 (Build 15F34))
 of 2016-06-28
slime ; SLIME 2016-04-19
quicklisp "2016-05-31"
```

**Comment by luismbo** [comment]
TAB is bound to `indent-for-tab-command` in slime-repl-read-mode but shouldn't. Should be easy to fix, I hope. FWIW, you can press <kbd>C-g</kbd> to make Emacs responsive again.

**Comment by luismbo** [comment]
@phoe-krk should be fixed now. Thanks.
