### ISSUE TITLE
slime-edit-definition (M-.) "symbol's function definition is void: equalp"

### ISSUE THREAD

**Issue by mr1yh1** [slime/slime#332]
Calling from REPL, slime-edit-definition was not jumping to the source file, 
giving the error "symbol's function definition is void: equalp".

those files in slime/contrib includes "equalp" (instead of "cl-equalp"); 
slime-enclosing-context.el:204
slime-package-foo.el:177

after changing them problem seems to be fixed for me.

**Comment by luismbo** [comment]
Fixed, thanks!
