### ISSUE TITLE
Edge case where macrostep expansion fails

### ISSUE THREAD

**Issue by gdobbins** [slime/slime#339]
I have tested the following minimal example on SBCL:

    (defun foo (x y)
      (list x y))
    
    (define-compiler-macro foo (&whole form x y)
      (if (eql x 1)
          `(list 2 ,y)
          form))
    
    (defmacro bar (&body body)
      `(flet ((foo (&rest args)
                args))
         ,@body))

Executing `(bar (foo 1 2 3))` returns the expected `(1 2 3)` however if `macrostep-expand` is used on the `bar` macro in this form the following error is generated:

>error while parsing arguments to DEFINE-COMPILER-MACRO FOO:
>  too many elements in
>    (1 2 3)
>  to satisfy lambda list
>    (X Y):
>  exactly 2 expected, but got 3

instead of the expected expansion:

    (FLET ((FOO (&REST ARGS)
             ARGS))
      (FOO 1 2 3))

Obviously this has to do with the fact that the `flet` defined `foo` accepts arbitrarily many arguments, whereas the top level defined `foo`'s compiler-macro expects two. What I'm not quite sure of is why the compiler-macro is ever called; since the top level function is shadowed by the `flet` the compiler-macro should not apply.

**Comment by luismbo** [comment]
Huh oh. We're not keeping track of environments. That needs to be fixed indeed. I'm currently travelling without a computer, do you feel like taking a stab at fixing this?

**Comment by attila-lendvai** [comment]
i could reproduce this and the fix indeed fixes it.

**Comment by luismbo** [comment]
Thanks!
