### ISSUE TITLE
Custom client for Swank?

### ISSUE THREAD

**Issue by HiPhish** [slime/slime#344]
Hello everyone,

I am new here and I’m not an Emacs user, I am a Neovim user. If you don’t know what Neovim is, it’s a fork of Vim that is refactoring and improving the Vim source to make it more maintainable and allow new features. Among them are the possibility of asynchronous plugins and being able to write plugins in any language.

And this is where Slime comes in: I would like to write a plugin similar to Slime, but for Neovim. The plugin would be written in Common Lisp, but the client language doesn’t really matter. I have been looking a bit at the Slime source and I see that it is made of two independent parts: a server application called Swank and written in Common Lisp, and a client that’s an Emacs plugin and written in Emacs Lisp which is the actual Slime. Slime is loaded by Emacs and connect to an instance of Swank. That instance can either be spawned by Slime itself, or by the user and Slime is then told by the user to connect to it. The user then controls Slime via key chords or commands, and Slime then sends messages to Swank, receives answers and then does something in Emacs based on those answers. Swank is the one that does all the heavy lifting while Slime is just responsible for generating messages from the buffer contents and manipulating the buffer according to Swank’s answers.

Did I get everything right so far? If so, then it means I have to write the client-part. So here are my questions:
- Is there a standalone Swank? I know I can install Swank via Quicklisp, but that pulls in the entire Slime repo, which is wasting several megabytes. Not a big deal, but still.
- Is there any documentation on how to use Swank, other than reading the source? swank.lisp is almost 4000 lines long, there is no way I’m reading all of that.

There are a two standalone Swank clients (swank-client and swank-protocol), but all they can do is send expressions to Swank for evaluations, which would be enough only for a rudimentary REPL, but I want to be able to use all Swank features. There is also an incomplete Markdown document describing some of the protocol, but that’s years old by now.

I really don’t know where to start digging in such a large project. I hope you can help me out because it would be really cool if we could share the backend server :)

HiPhish

---

I have been trying to post this to the mailing list for days, but my mail always gets rejected even though I have subscribed, so please excuse me for abusing the issues section like this.

**Comment by luismbo** [comment]
Sorry, this issue got buried in the large list of issues. Let us know if you still need help!

**Comment by HiPhish** [comment]
I have lost interest since, and the Common Lisp client for Neovim doesn't work properly anyway. Thanks for replying though.
