### ISSUE TITLE
slime-describe-symbols truncates plist

### ISSUE THREAD

**Issue by jimka2001** [slime/slime#369]
If I set the plist of a symbols as follows, slime-describe-symbol truncates in a funny way.
I suspect it is a bug.  If it is intentional, then it's bizarre.

CL-USER> (setf (get 'cl-user::my-symbol 'cl-user::my-prop-name) '(:SORT-NODES 
 (LAMBDA (GRAPH) 
   (DECLARE (NOTINLINE SORT)) 
   (SORT GRAPH #'< :KEY #'COUNT-CONNECTIONS-PER-NODE)) 
 :SORT-STRATEGY "INCREASING-CONNECTIONS" :INNER-LOOP :OPERATION :DO-BREAK-SUB 
 :STRICT :DO-BREAK-LOOP T) )

emacs> (slime-describe-symbol "cl-user::mysymbol")
displays the following in a buffer.  I would prefer it to display the 
real symbol-plist, rather than the truncated one.
---------------------
COMMON-LISP-USER::MY-SYMBOL
  [symbol]

Symbol-plist:
  COMMON-LISP-USER::MY-PROP-NAME -> (:SORT-NODES..

**Comment by phoe** [comment]
The two periods at the end smell like http://clhs.lisp.se/Body/v_pr_lin.htm .

**Comment by stassats** [comment]
That's what your implementation's DESCRIBE does.
