### ISSUE TITLE
slime.el has ^M characters

### ISSUE THREAD

**Issue by massung** [slime/slime#372]
`swank-loader::slime-version-string` uses `slime.el` to search for the `;; Version:` line. At the end of this it returns a string with a trailing newline. The latest SBCL will not strip this when attempting to create the FASL directory, and then fails. Either:

* `slime.el` needs to be resaved without the newline characters (and update the git repository to not allow the file to be submitted again with newlines) or...

* Both `slime-check-version` in slime.el and `slime-version-string` in swank-loader need to take the trailing newline into account.

The first option is a simple fix for everyone, the latter is safest for the future.

**Comment by luismbo** [comment]
I don't see any such CR characters. My wild guess is that you're on Windows and grabbed SLIME via Git with `core.autocrlf` on? Tagging this as invalid until my guess is rebutted. :-)

**Comment by massung** [comment]
That's a pretty good guess and turned out to be the case. I would still - long term - suggest altering the functions to trim the strings (just in case), but I can certainly understand if you don't want to. ;-)

**Comment by luismbo** [comment]
@massung oh, right, I see your point. It certainly can happen, as you've shown. :-) Do you feel like creating a pull request for that?

**Comment by luismbo** [comment]
So, for the record, the workaround for this issue is to make sure you grab SLIME from Git with `core.autocrlf` set to false. (tagged as workaround)
