### ISSUE TITLE
build error under Arch Linux, emacs 26

### ISSUE THREAD

**Issue by stefanhusmann** [slime/slime#381]
Under Arch Linux with emacs 26 from git master the build fails with this buildlog:
http://dpaste.com/0ZFG3P4

**Comment by stefanhusmann** [comment]
Workaround is to avoid byte compiling slime-hyperdoc.el.

**Comment by stefanhusmann** [comment]
The Problem was probably only on my system (some stale leftovers from a broken tramp installation or so).

**Comment by luismbo** [comment]
@stefanhusmann that's good news. Thanks for the follow-up! In any case, it was a good reminder that we should add Emacs 26 builds to Travis CI.
