### ISSUE TITLE
Open Parenthesis at start of line in doc string trips up top level form recognition.

### ISSUE THREAD

**Issue by fiveop** [slime/slime#382]
An open parenthesis at the start of a doc string line will trip up the top level from recognition.

Invoking `slime-compile-defun` via key-binding (per default C-c C-c) anywhere within

```
(defun foo ()
  "bar
(baz)"
  nil)
```
will yield an error. The same is true if the closing parenthesis is omitted.

Automatic indentation is also messed up after the docstring, though I don't know if that is slime-mode's job or lisp-mode's.

**Comment by luismbo** [comment]
AFAIK, this is a lisp-mode limitation and the workaround is to prepend the opening parenthesis with a backward slash `\`.

(A similar issue happens if your code is incorrectly indented such that a non top-level form gets its opening parenthesis on the first column.)

**Comment by luismbo** [comment]
Of course, if you have a cunning plan to fix this, please do share! 🙃

**Comment by fiveop** [comment]
For future reference:

The offending code is probably found in `beginning-of-defun-raw` in `lisp.el` of the emacs source code. Among other things it searches backward using the regexp `"^\\s("`.
