### ISSUE TITLE
DEFUN/DEFMACRO broken if line in docstring begins with (

### ISSUE THREAD

**Issue by phoe** [slime/slime#384]
If a documentation string inside DEFUN or DEFMACRO has a newline followed immediately by `#\(`, the indentation after that line breaks and `C-c` no longer works (seems to no longer send the proper part of the buffer to Swank for compilation).

```lisp
(defun foo (bar baz)
  "This is broken.
(This parenthesis breaks C-c and indentation after it.)"
(frobnicate bar baz) ;; this is actually what indentation looks like in emacs
nil)
```

**Comment by luismbo** [comment]
Duplicated issue: #382
