### ISSUE TITLE
Docstring for DEFPARAMETER is off-colored in lisp-mode

### ISSUE THREAD

**Issue by phoe** [slime/slime#387]
In the following code snippet, only DEFVAR has its documentation string properly colored.

```lisp
(defvar *foo* 2 "foo")
(defparameter *bar* 2 "bar")
```

Screenshot:
![](https://i.imgtc.com/Kjj98qu.png)

theme zenburn
Slime 2.19
Spacemacs 0.200.9
Emacs 24.5.1

**Comment by ExpHP** [comment]
I can reproduce this, having only just installed slime-mode now to test.

Theme lush
Slime 2.19
Spacemacs v.0.200.8
Emacs 25.2.1

**Comment by luismbo** [comment]
We rely on Emacs's `lisp-mode` for several things, one of which is fontification. I think this should be fixed in `lisp-mode`. Can you report it to the Emacs developers?

**Comment by phoe** [comment]
Yes, will do tomorrow.

**Comment by luismbo** [comment]
Awesome, thanks!
