### ISSUE TITLE
Can't disable linum-mode in SLIME REPL

### ISSUE THREAD

**Issue by duncan-bayne** [slime/slime#389]
I've added the following hook in an attempt to disable linum-mode in the SLIME REPL:

```
(add-hook 'slime-repl-mode-hook
  (lambda ()
    (message "disabling linum-mode")
    (linum-mode 0)))
```

I can see the message "disabling linum-mode" in *messages*, but the line numbers remain:

![linum](https://cloud.githubusercontent.com/assets/65949/26521251/51ed5f36-4327-11e7-8f15-e8814cdfbcfc.png)

If I do `M-x linum-mode` manually while in the SLIME REPL, the line numbers disappear as expected.

**Comment by luismbo** [comment]
https://stackoverflow.com/questions/6837511/automatically-disable-a-global-minor-mode-for-a-specific-major-mode

Can you try these tips? Seems unlikely to be a SLIME-specific issue, so I'll close this. Feel free to reopen if stackoverflow doesn't help.
