### ISSUE TITLE
slime-edit-definition (M-.) does not look for local function definitions

### ISSUE THREAD

**Issue by MatthewRock** [slime/slime#393]
```common-lisp
(defun some-function ()
  (labels ((my-fun (x)
                (if (= x 5) (my-fun 4) (print x)))
    (my-fun 5)))
```

In the code above, when using slime-edit-definition (M-.) on the my-fun calls, we will be informed that there's no known definition, even though it's just above.

Hard mode: local function could be declared special.

**Comment by luismbo** [comment]
Have you loaded the `slime-mdot-fu` contrib? (Perhaps indirectly via
`slime-fancy`.) That's the bit of magic that enables local definition
lookups.

**Comment by MatthewRock** [comment]
No, I haven't. I will try that out and get back to you. Would that count as nofix then?

**Comment by luismbo** [comment]
Counts as "has already been fixed", I guess. :-)
