### ISSUE TITLE
Document the Slime/Swank protocol

### ISSUE THREAD

**Issue by phoe** [slime/slime#394]
I want to write a Swank server for Lisp Flavored Erlang, but for this, I need to know the protocol which I need to implement on the server.

I have only seen unofficial and incomplete documents that explain how the protocol works.

Are there any official documents describing the Swank/Slime protocol?

**Comment by luismbo** [comment]
Not that I'm aware of, no.

**Comment by phoe** [comment]
Okay.

As a part of my effort towards developing a swank server for LFE, I will try creating a document that describes the protocol.

I will post my progress here.

**Comment by luismbo** [comment]
ETOOMANYOPENISSUES. Do keep us posted though!
