### ISSUE TITLE
Error in swank:fuzzy-generate-matchings

### ISSUE THREAD

**Issue by osense** [slime/slime#395]
Hi,

when connecting from a remote machine (through a SSH tunnel), I'm getting a crash as soon as something triggers auto-completion *within* a module. The auto-completion on module names works fine. Here's the backtrace:

```
The value NIL is not of type REAL.
   [Condition of type TYPE-ERROR]

Restarts:
 0: [*ABORT] Return to SLIME's top level.
 1: [ABORT] Abort thread (#<THREAD "repl-thread" RUNNING {100ACE0063}>)

Backtrace:

  0: (SWANK::FUZZY-GENERATE-MATCHINGS "utils:*" "COMMON-LISP-USER" NIL)
  1: (SWANK::FUZZY-COMPLETION-SET "utils:*" "COMMON-LISP-USER" :LIMIT NIL :TIME-LIMIT-IN-MSEC NIL)
  2: (SWANK:FUZZY-COMPLETIONS "utils:*" "COMMON-LISP-USER" :LIMIT NIL :TIME-LIMIT-IN-MSEC NIL)
  3: (SB-INT:SIMPLE-EVAL-IN-LEXENV (SWANK:FUZZY-COMPLETIONS "utils:*" (QUOTE "COMMON-LISP-USER")) #<NULL-LEXENV>)
  4: (EVAL (SWANK:FUZZY-COMPLETIONS "utils:*" (QUOTE "COMMON-LISP-USER")))
  5: (SWANK:EVAL-FOR-EMACS (SWANK:FUZZY-COMPLETIONS "utils:*" (QUOTE "COMMON-LISP-USER")) "COMMON-LISP-USER" 13)
  6: (SWANK::PROCESS-REQUESTS NIL)
  7: ((LAMBDA NIL :IN SWANK::HANDLE-REQUESTS))
  8: ((LAMBDA NIL :IN SWANK::HANDLE-REQUESTS))
  9: (SWANK-BACKEND::CALL-WITH-BREAK-HOOK #<FUNCTION SWANK:SWANK-DEBUGGER-HOOK> #<CLOSURE (LAMBDA NIL :IN SWANK::HANDLE-REQUESTS) {100ACF00FB}>)
 10: ((FLET SWANK-BACKEND:CALL-WITH-DEBUGGER-HOOK :IN "/home/deployer/apps-premvp/lisperator-libs/slime-20140829-git/swank-sbcl.lisp") #<FUNCTION SWANK:SWANK-DEBUGGER-HOOK> #<CLOSURE (LAMBDA NIL :IN SWANK:..
 11: (SWANK::CALL-WITH-BINDINGS ((*STANDARD-OUTPUT* . #1=#<SWANK-BACKEND::SLIME-OUTPUT-STREAM {100ACB8853}>) (*STANDARD-INPUT* . #2=#<SWANK-BACKEND::SLIME-INPUT-STREAM {100ACB87A3}>) (*TRACE-OUTPUT* . #1#)..
 12: (SWANK::HANDLE-REQUESTS #<SWANK::MULTITHREADED-CONNECTION {100ABBD8E3}> NIL)
 13: ((FLET #:WITHOUT-INTERRUPTS-BODY-1117 :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
 14: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
 15: ((FLET #:WITHOUT-INTERRUPTS-BODY-537 :IN SB-THREAD::CALL-WITH-MUTEX))
 16: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {7FFFEDF76C2B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THR..
 17: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "repl-thread" RUNNING {100ACE0063}> #S(SB-THREAD:SEMAPHORE :NAME "Thread setup semaphore" :%COUNT 0 :WAITCOUNT 0 :MUTEX #<SB-THREAD:MU..
 18: ("foreign function: call_into_lisp")
 19: ("foreign function: new_thread_trampoline")
```

Interestingly, this doesn't happen when I'm connecting from an emacs instance running directly on the remote machine. I'm running slime 2.9, but since it works on the remote, I don't think the somewhat older version should be a problem. If anyone has any suggestion on how I could resolve this problem, I would be most grateful.

A.

Edit: ok actually now it doesn't work on the remote machine either…

**Comment by attila-lendvai** [comment]
> auto-completion within a module

what does that mean? do you mean a `package` by `module`?

what lisp are you using, and where does that `util:` package come from?

note that the slime version running in your emacs and in your remote lisp must match (but it would bark otherwise).

**Comment by osense** [comment]
> what does that mean? do you mean a package by module?
Yeah, sorry.
> what lisp are you using, and where does that util: package come from?
The lisp is `SBCL 1.1.14.debian`.
> note that the slime version running in your emacs and in your remote lisp must match
Yup, they do match :)

**Comment by luismbo** [comment]
@osense a recipe for reproducing the issue (perhaps involving ssh to localhost) would be rather helpful!

**Comment by osense** [comment]
I couldn't get emacs to tell me which line exactly in `SWANK::FUZZY-GENERATE-MATCHINGS` causes this, but it is caused by passing `NIL` as the last argument. If a numerical value is always provided, there is no issue.
