### ISSUE TITLE
SLIME Autodoc erroring due to change in El-Doc

### ISSUE THREAD

**Issue by RobertCochran** [slime/slime#400]
`eldoc-message` in eldoc.el has changed its function parameters in Emacs Git 7ef0b5f6.

This causes function parameter errors when autodoc tries to display messages, which slows things down (at least for me), and therefore becomes a hassle really fast.

It seems like changing the call `eldoc-message` in [`slime-autodoc--async%`](https://github.com/slime/slime/blob/f223388c78ea51ce7717e9bbae14c50ad2386c2c/contrib/slime-autodoc.el#L160) to remove the first `"%s"` works on first examination, but I have no idea what that implies for the long term, such as backwards compatibility.

**Comment by p-m** [comment]
This patch solves the issue:

```
diff --git a/contrib/slime-autodoc.el b/contrib/slime-autodoc.el
index 6ba468d2..41942edc 100644
--- a/contrib/slime-autodoc.el
+++ b/contrib/slime-autodoc.el
@@ -42,7 +42,7 @@
   "Like autodoc informtion forcing multiline display."
   (interactive)
   (let ((doc (slime-autodoc t)))
-    (cond (doc (eldoc-message "%s" doc))
+    (cond (doc (eldoc-message doc))
          (t (eldoc-message nil)))))
 
 ;; Must call eldoc-add-command otherwise (eldoc-display-message-p)
@@ -55,7 +55,7 @@
   (self-insert-command n)
   (let ((doc (slime-autodoc)))
     (when doc
-      (eldoc-message "%s" doc))))
+      (eldoc-message doc))))
 
 (eldoc-add-command 'slime-autodoc-space)
 
@@ -157,7 +157,7 @@ If it's not in the cache, the cache will be updated asynchronously."
       ;; Now that we've got our information,
       ;; get it to the user ASAP.
       (when (eldoc-display-message-p)
-       (eldoc-message "%s" (slime-autodoc--format doc multilinep))))))
+       (eldoc-message (slime-autodoc--format doc multilinep))))))
 
 ^L
 ;;; Minor mode definition
```

Peter

**Comment by dgutov** [comment]
> I have no idea what that implies for the long term, such as backwards compatibility

The backward compatibility will be fine: with no extra arguments, the first argument was treated as a plain string, not a format string. So the code is a direct equivalent, and you should apply this patch as soon as you can.

**Comment by dgutov** [comment]
On the other hand, I really question your usage of `eldoc-message` if the first place. It's not the way to display ElDoc messages. The correct way is to set an `eldoc-documentation-function`.

**Comment by dgutov** [comment]
But this patch is a good first improvement anyway.

**Comment by joaotavora** [comment]
> The correct way is to set an eldoc-documentation-function.

Hmm, what if the function documentation takes a while to fetch, as is the case here? Is there a `eldoc-documentation-function-async`?

**Comment by dgutov** [comment]
Not yet. But Emacs is waiting for your contribution!

**Comment by dgutov** [comment]
You could also use `sit-for`, BTW.

**Comment by joaotavora** [comment]
> Not yet. But Emacs is waiting for your contribution!

Heh. Concentrating on that flymake refactor right now. actually there's a very similar problem there, let's see how I solve it, then maybe export it to eldoc.

> You could also use sit-for, BTW.

hmm, sounds interesting but I don't follow

**Comment by dgutov** [comment]
Call the request asynchronously first. Then call `sit-for` in a loop while there is no user input. If the long request has completed, great, return it. 

Otherwise when user input arrives, return nil. And the callback for the asynchronous request will do nothing.

Just an option.

**Comment by joaotavora** [comment]
> If the long request has completed, great, return it.

you mean when eldoc calls my `eldoc-documentation-function`?

I think I more or less see the gist of it, but I still don't get where `sit-for` comes in.

> Just an option.

Sure, sounds interesting, but I still don't get it. Sounds like a common Emacs idiom, do you have any examples?

**Comment by dgutov** [comment]
> you mean when eldoc calls my eldoc-documentation-function?

Inside your `eldoc-documentation-function`, yes.

> Sounds like a common Emacs idiom, do you have any examples?

It's not great, because it blocks timer execution (I think). But it can be helpful.

`flyspell-post-command-hook` does something like that, except without HTTP requests.

**Comment by luismbo** [comment]
@p-m applied your patch, thanks.
