### ISSUE TITLE
eldoc-message has changed signature in emacs 27

### ISSUE THREAD

**Issue by clynbech** [slime/slime#406]
It appears that eldoc-message has changed signature in recently available emacs 27, such that it now takes only one optional parameter. This is fortunately easily fixed in slime by wrapping the two parameters in a call to format and that should be (I think) backwards compatible with older versions of emacs (I do not have any older emacs handy so I cannot easily check the old signature).

Affected functions are: slime-autodoc--async% and slime-autodoc-manually in contrib/slime-autodoc.el. In particular the former is annoying as it will trigger an error every time one moves around in the buffer, yielding autodoc completely useless.

One might argue that the change in emacs was not entirely intentional (at least if looking at the documentation of eldoc-message-function), so I will raise the issue on the emacs-devel list as well.

**Comment by luismbo** [comment]
@clynbech thanks. Please do keep us posted regarding your report on emacs-devel.

**Comment by clynbech** [comment]
I have now analysed the situation further and have given up on taking it up on emacs-devel.

It seems that the change was done after some deliberation as described in this emacs bug report https://debbugs.gnu.org/cgi/bugreport.cgi?bug=27230. Apparently the change was done back in June.

The upshot is that third party users of eldoc are *not* supposed to use eldoc-message directly, but should rather use eldoc-documentation-function, for which I will make an attempt to make a fix.

Incidently, there was another report of this problem already, in https://github.com/slime/slime/issues/400

**Comment by luismbo** [comment]
@clynbech right, and we fixed that bug in https://github.com/slime/slime/commit/ba657d910f411754dfb0de3b5c6059aa1977ab85 I'm assuming you didn't test using slime from git, was that it?

**Comment by luismbo** [comment]
@clynbech OK, cool. Good to know.
