### ISSUE TITLE
Autodoc ignores ElDoc's lighter customization

### ISSUE THREAD

**Issue by sirikid** [slime/slime#409]
Because of this form:
https://github.com/slime/slime/blob/55fc578ed829b95a63c31cec242bd86a6e0be39e/contrib/slime-autodoc.el#L178

**Comment by luismbo** [comment]
Could you explain why that's problematic and perhaps offer some alternative?

**Comment by sirikid** [comment]
Some people do not want to see all the minor modes in the modeline. ElDoc provides a customizable variable `eldoc-minor-mode-string`, which is its lighter. So, you need to add such a variable for the Autodoc mode. This can be done in several ways, and I hope to present my vision of the solution soon.

**Comment by luismbo** [comment]
Right. FWIW, I use `(diminish 'eldoc-mode)` and it works for me.

**Comment by sirikid** [comment]
I do not want to sound rude, but why you diminish ElDoc instead of Autodoc?
Also, [here](https://github.com/sirikid/slime/tree/slime-autodoc-customizable-lighter) is my solution.

**Comment by luismbo** [comment]
@sirikid Indeed, `(diminish 'slime-autodoc-mode)` would make much more sense. Your solution makes sense to me, you should open a pull request.
