### ISSUE TITLE
On start 'Detect access to an invalid or protected memory address'

### ISSUE THREAD

**Issue by DeadNumbers** [slime/slime#411]
Arch Linux, kernel 4.13.12-1-ARCH 
Emacs 25.3.1
It's happens every time on start `slime`. How to fix?
![_2017-11-15_14-36-19](https://user-images.githubusercontent.com/9416005/32834355-6656366e-ca13-11e7-9e70-029af4769123.png)

**Comment by luismbo** [comment]
Is that ECL? What version? Can you try and load swank manually into ECL without using Emacs?

**Comment by DeadNumbers** [comment]
@luismbo 
```
user@arch ~ ➤ ecl
;;; Loading "/home/user/quicklisp/setup.lisp"
;;; Loading #P"/usr/lib/ecl-16.1.3/asdf.fas"
ECL (Embeddable Common-Lisp) 16.1.3 (git:UNKNOWN)
Copyright (C) 1984 Taiichi Yuasa and Masami Hagiya
Copyright (C) 1993 Giuseppe Attardi
Copyright (C) 2000 Juan J. Garcia-Ripoll
Copyright (C) 2016 Daniel Kochmanski
ECL is free software, and you are welcome to redistribute it
under certain conditions; see file 'Copyright' for details.
Type :h for Help.  
Top level in: #<process TOP-LEVEL>.
> (ql:quickload "swank")
To load "swank":
  Load 1 ASDF system:
    swank
; Loading "swank"
.
("swank")
> 
```

**Comment by luismbo** [comment]
@DeadNumbers so far so good, try `(swank:create-server)` next.

**Comment by DeadNumbers** [comment]
@luismbo 
![_2017-11-15_16-21-42](https://user-images.githubusercontent.com/9416005/32838293-7b7684e6-ca21-11e7-89b9-f21f0ffcf017.png)

**Comment by luismbo** [comment]
@DeadNumbers now `M-x slime-connect` into that ECL instance from Emacs.

**Comment by DeadNumbers** [comment]
@luismbo have no warnings, no errors if manual connect.

**Comment by luismbo** [comment]
@DeadNumbers Interesting. When the connection fails, what's in the `*inferior-lisp*` and `*slime-events*` buffers?

**Comment by DeadNumbers** [comment]
@luismbo I can't find `*slime-events*`. Sorry, I'm newbie in Emacs magic.
![_2017-11-15_17-36-31](https://user-images.githubusercontent.com/9416005/32841642-f1e3bfcc-ca2b-11e7-838e-db206a20671a.png)

**Comment by luismbo** [comment]
So, when you use Quicklisp to load SWANK, you're actually loading a different version from then one you're using from Emacs. Can you try and use SLIME 2.19 to see if that works better? https://github.com/slime/slime/releases/tag/v2.19

BTW, pasting the actual test is much more convenient than screenshots.

@dkochmanski Does this ring any bells? Might https://github.com/slime/slime/pull/403 solve this?

**Comment by dkochmanski** [comment]
I don't think so (but I may be wrong). I think that problem tackled in #403 may be a result (in contrary to my initial assumption) of some other commit than adding `:spawn` as a way to communicate in ECL. I didn't have time to work on it lately. When I do, I'll try to bisect changes to pin-point the culpirt.

**Comment by dkochmanski** [comment]
Sometimes protection/memory issues are result of loading FASL from incompatible version (i.e compiled with different ECL compilation). ECL doesn't validate that yet.

**Comment by DeadNumbers** [comment]
>remove the ~/.slime/fasl directory

Thats help. Thanks!

**Comment by luismbo** [comment]
Ah, interesting. Good catch @dkochmanski!
