### ISSUE TITLE
install from git ,slime can't start

### ISSUE THREAD

**Issue by YDJX** [slime/slime#414]
system is Windows10 x86-64 , emacs version 25.31
(progn (load "d:\\MyWorkSpace\\slime\\swank-loader.lisp" :verbose t) (funcall (read-from-string "swank-loader:init")) (funcall (read-from-string "swank:start-server") "c:\\Users\\xxx\\AppData\\Local\\Temp\\slime.392"))

This is SBCL 1.4.2, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.

WARNING: the Windows port is fragile, particularly for multithreaded
code.  Unfortunately, the development team currently lacks the time
and resources this platform demands.
* 
; loading #P"d:/MyWorkSpace/slime/swank-loader.lisp"
;; 
;; Error ???ing d:/MyWorkSpace/slime/packages.lisp:
\
;; 

debugger invoked on a SB-INT:SIMPLE-FILE-ERROR in thread
#<THREAD "main thread" RUNNING {10027900C3}>:
\

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY   ] Retry directory creation.
  1: [CONTINUE] Continue as if directory creation was successful.
  2: [ABORT   ] Exit debugger, returning to top level.

/sbcl-1.4.2-win32-x86-64/packages.fasl" :VERBOSE NIL :MODE 511)
0] 

and *Message* is printing message
slime-abort-connection’.)
Polling "c:/Users/xxx/AppData/Local/Temp/slime.392" .. 1103 (Abort with ‘M-x slime-abort-connection’.)
Polling "c:/Users/xxx/AppData/Local/Temp/slime.392" .. 1104 (Abort with ‘M-x slime-abort-connection’.)
.........

**Comment by luismbo** [comment]
The output seems a bit garbled, but it seems like it didn't have enough permissions to create the fasl file or it tried to create it in the wrong place or something like that. Can you get a backtrace by typing `:bt` when the error pops up?

**Comment by luismbo** [comment]
There was some discussion over e-mail and it seems like the HOME variable may have been set something that SBCL couldn't parse.

**Comment by YDJX** [comment]
It's no use. and I don't want to use slime. It doesn't matter with the home environment variable...

**Comment by lekso22** [comment]
run cmd as admin
