### ISSUE TITLE
SLIME Tar Not Found on MELPA

### ISSUE THREAD

**Issue by artforlife** [slime/slime#417]
After enabling MELPA repository and successfully installing a few packages from it, I attempted to install SLIME.

However, when I run `M-x package-install <RET> SLIME <RET`. I get the following in the mini-buffer:

> http://melpa.org/packagesslime-20171207.17.12.tar: Not found

**Comment by luismbo** [comment]
That's pretty weird. `M-x package-refresh-contents` should fix that, probably? HTH.
