### ISSUE TITLE
Using ANSI colors?

### ISSUE THREAD

**Issue by belambert** [slime/slime#420]
Hi, I've wondered about this for a while.  Is it possible to print with ANSI colors in a Slime repl buffer?

If I load the `cl-ansi-text` library from Quicklisp `(ql:quickload :cl-ansi-text)`, and I run `(cl-ansi-text:yellow "yellow")` in the Slime REPL the output is: `"[33myellow[0m"`.  When I run the same commands directly in an SBCL REPL, it prints as expected `"yellow"` in a yellow color.

Is it possible to use ANSI colors in Slime? Or maybe there's some workaround?

Thanks,
Ben

**Comment by luismbo** [comment]
https://mailman.common-lisp.net/pipermail/slime-devel/2017-December/011690.html
