### ISSUE TITLE
Commit "2e7f9463 * More energy efficient auto-flush-loop." breaks Lispworks 7.0/Emacs master

### ISSUE THREAD

**Issue by pederkl** [slime/slime#424]
Upgrading my Slime and Emacs today (to their respective git master branches), compiling a file with errors in it with Lispworks 7 on Ubuntu 16.04 reproducibly caused a hang.  Reverting commit 2e7f9463 fixed it for me.

Testcase:  a file /tmp/foo.lisp containing 
```lisp
(this:will-fail)
```

When compiled with
```lisp
(let ((hcl:*compiler-break-on-error* t))
    (compile-file  "/tmp/foo.lisp"))
```
in the slime-repl buffer, I get an error message in the repl buffer, fontified like text output:

>**++++ Error between functions:
  Reader cannot find package THIS.

And then nothing.  No prompt, no sldb-buffer. I can still type, but nothing I type evokes any response.  `C-c C-c` doesn't help.  `, restart-inferior-lisp` unsticks things, but is quite suboptimal.

Expected behaviour: After seeing the textual error message, I expected an sldb buffer to pop up with the same error and some means for me to continue.

As stated above, reverting commit 2e7f9463 fixed it for me, getting back the expected behaviour.  I'm not familiar enough with the codebase to provide a better patch, I'm afraid, sorry.

**Comment by stassats** [comment]
I don't see how it could cause that problem. And it works in lispworks 6.

**Comment by stassats** [comment]
The problem manifested itself differrently on Lispworks 6, should be fixed now.

**Comment by pederkl** [comment]
I can confirm that this appears fixed in the latest git.  Thanks!
