### ISSUE TITLE
[Suggestion] Support for implicit-outermost-paren input

### ISSUE THREAD

**Issue by akater** [slime/slime#442]
Provide an option to omit the outermost parens pair. In Common Lisp, this is already provided by a small [opfr.lisp](http://rpw3.org/hacks/lisp/opfr.lisp). OPFR supports parened forms as well. Looks like it does not support multi-line input though. Using it in SLIME breaks slime completion and font consistency. Looks like such a feature, if provided, better be provided by slime itself.

I'm not sure if it would be useful. But the suggestion has been floating around, and is not present in local Issues.

Strict read vs implicit-paren read may be indicated by different prompts, e.g.:
```
CL-USER> (user input)
```
vs
```
CL-USER $ user input
```
or maybe even
```
CL-USER (user input
```
or some user-specified `slime-implicit-outermost-paren-prompt-string`.

**Comment by akater** [comment]
I vaguely remember someone saying Lisp Machines had implicit top-level parentheses but can't find a reference.

**Comment by stassats** [comment]
Not something I would like to see, even if optional. Is it that hard to type one parenthesis?

**Comment by akater** [comment]
It is not hard to type one parenthesis, and it is still easier not to type one.

For an interested reader: Eshell allows evaluation of both traditional and implicitly enclosed forms, and this doesn't even seem to be optional.

**Comment by stassats** [comment]
I'm sure some people will find it useful. But it's one more feature to implement and support, a feature that very few people will know about and of questionable utility.
