### ISSUE TITLE
"error in process filter: Wrong number of type arguments: (0 . 1), 2" constantly pops up when editing

### ISSUE THREAD

**Issue by RyanMatlock** [slime/slime#450]
When starting to type something as simple as `(defun)` (with `paredit` mode enabled, so the closing paren is there automatically), I keep getting `error in process filter: Wrong number of type arguments: (0 . 1), 2` in my minibuffer (along with an error beep from OS X), which makes editing very annoying. This began once I updated Emacs from 25.3 to 26.1 using Homebrew. My `.emacs` file only contains the following slime-specific lines:

    (setq inferior-lisp-program "/usr/local/bin/sbcl")
    (setq slime-contribs '(slime-fancy))

Here's the traceback I get once I toggle `debug-on-error` on:

    Debugger entered--Lisp error: (wrong-number-of-arguments (0 . 1) 2)
      eldoc-message("%s" #("(defun name lambda-list &body body)" 1 6 (face font-lock-keyword-face) 7 11 (face font-lock-function-name-face) 24 29 (face font-lock-type-face)))
      slime-autodoc--async%(("defun" swank::%cursor-marker%) truncate-sym-name-if-fit ("(defun name lambda-list &body body)" t))
      apply(slime-autodoc--async% (("defun" swank::%cursor-marker%) truncate-sym-name-if-fit ("(defun name lambda-list &body body)" t)))
      (lambda (&rest more) (apply 'slime-autodoc--async% (append '(("defun" swank::%cursor-marker%) truncate-sym-name-if-fit) more)))(("(defun name lambda-list &body body)" t))
      #f(compiled-function (g459 g460 g455) #<bytecode 0x4101c4f5>)(--buffer-- --cont-- (:ok ("(defun name lambda-list &body body)" t)))
      apply(#f(compiled-function (g459 g460 g455) #<bytecode 0x4101c4f5>) --buffer-- --cont-- (:ok ("(defun name lambda-list &body body)" t)))
      (lambda (&rest --cl-rest--) (apply (function #f(compiled-function (g459 g460 g455) #<bytecode 0x4101c4f5>)) '--buffer-- '--cont-- --cl-rest--))((:ok ("(defun name lambda-list &body body)" t)))
      slime-dispatch-event((:return (:ok ("(defun name lambda-list &body body)" t)) 7) #<process SLIME Lisp>)
      slime-process-available-input(#<process SLIME Lisp>)
      slime-net-filter(#<process SLIME Lisp> "00003B(:return (:ok (\"(defun name lambda-list &body body)\" t)) 7)")

Perhaps `*slime-events*` would also be useful:

    (:emacs-rex
     (swank:connection-info)
     "COMMON-LISP-USER" t 1)
    (:return
     (:ok
      (:pid 4143 :style :spawn :encoding
            (:coding-systems
             ("utf-8-unix" "iso-latin-1-unix"))
            :lisp-implementation
            (:type "SBCL" :name "sbcl" :version "1.4.8" :program "/usr/local/Cellar/sbcl/1.4.8/libexec/bin/sbcl")
            :machine
            (:instance "matlockmbp.local" :type "X86-64" :version "Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz")
            :features
            (:swank :quicklisp :sb-bsd-sockets-addrinfo :asdf3\.3 :asdf3\.2 :asdf3\.1 :asdf3 :asdf2 :asdf :os-macosx :os-unix :non-base-chars-exist-p :asdf-unicode :64-bit :64-bit-registers :alien-callbacks :ansi-cl :ash-right-vops :bsd :c-stack-is-control-stack ...)
            :modules
            ("SB-CLTL2" "SB-INTROSPECT" "SB-BSD-SOCKETS" "SB-POSIX" "ASDF" "asdf" "UIOP" "uiop")
            :package
            (:name "COMMON-LISP-USER" :prompt "CL-USER")
            :version "2.20"))
     1)
    (:emacs-rex
     (swank:swank-require
      '(swank-trace-dialog swank-package-fu swank-presentations swank-macrostep swank-fuzzy swank-fancy-inspector swank-c-p-c swank-arglists swank-repl))
     "COMMON-LISP-USER" t 2)
    (:indentation-update
     (("do-debug-fun-vars" 1
       ("SB-DISASSEM" "SB-DEBUG" "SB-DI"))
      ("do-debug-fun-blocks" 1
       ("SB-DISASSEM" "SB-DEBUG" "SB-DI"))
      ("do-debug-block-locations" 1
       ("SB-DISASSEM" "SB-DEBUG" "SB-DI"))
      ("when-upgrading" 1
       ("ASDF/FIND-COMPONENT" "ASDF/PLAN" "ASDF/OPERATE" "ASDF/FOOTER" "ASDF/BACKWARD-INTERNALS" "ASDF/BUNDLE" "ASDF/FORCING" "ASDF/LISP-ACTION" "ASDF/BACKWARD-INTERFACE" "ASDF/SYSTEM-REGISTRY" "ASDF/SESSION" "ASDF/FIND-SYSTEM" "ASDF/PARSE-DEFSYSTEM" "ASDF/SOURCE-REGISTRY" "ASDF/ACTION" "ASDF/COMPONENT" "ASDF/PACKAGE-INFERRED-SYSTEM" "ASDF/SYSTEM" "ASDF/OPERATION" "ASDF/OUTPUT-TRANSLATIONS" ...))
      ("with-asdf-deprecation" 1
       ("ASDF/FIND-COMPONENT" "ASDF/PLAN" "ASDF/OPERATE" "ASDF/FOOTER" "ASDF/BACKWARD-INTERNALS" "ASDF/BUNDLE" "ASDF/FORCING" "ASDF/LISP-ACTION" "ASDF/BACKWARD-INTERFACE" "ASDF/SYSTEM-REGISTRY" "ASDF/SESSION" "ASDF/FIND-SYSTEM" "ASDF/PARSE-DEFSYSTEM" "ASDF/SOURCE-REGISTRY" "ASDF/ACTION" "ASDF/COMPONENT" "ASDF/PACKAGE-INFERRED-SYSTEM" "ASDF/SYSTEM" "ASDF/OPERATION" "ASDF/OUTPUT-TRANSLATIONS" ...))
      ("with-sequence-iterator" 2
       ("SB-SEQUENCE"))
      ("with-sequence-iterator-functions" 2
       ("SB-SEQUENCE"))
      ("dosequence" 1
       ("SB-SEQUENCE"))
      ("match" 1
       ("SWANK" "SWANK/MATCH"))
      ("socket-error-case" 2
       ("SB-BSD-SOCKETS"))
      ("with-socket-fd-and-addr" 2
       ("SB-BSD-SOCKETS"))
      ("addrinfo-error-case" 2
       ("SB-BSD-SOCKETS"))
      ("with-socket-addr" 2
       ("SB-BSD-SOCKETS"))
      ("with-vector-sap" 1
       ("SB-BSD-SOCKETS"))
      ("syscall-error-case" 2
       ("SB-BSD-SOCKETS"))
      ("pv-binding" 1
       ("SB-PCL"))
      ("simple-lexical-method-functions" 1
       ("SB-PCL"))
      ("pv-binding1" 1
       ("SB-PCL"))
      ("bind-args" 1
       ("SB-PCL"))
      ("dotimes-fixnum" 1
       ("SB-PCL"))
      ...))
    (:return
     (:ok
      ("SWANK-ARGLISTS" "SWANK-FANCY-INSPECTOR" "SWANK-FUZZY" "SWANK-C-P-C" "SWANK-UTIL" "SWANK-MACROSTEP" "SWANK-PRESENTATIONS" "SWANK-REPL" "SWANK-PACKAGE-FU" "SWANK-TRACE-DIALOG" "SB-CLTL2" "SB-INTROSPECT" "SB-BSD-SOCKETS" "SB-POSIX" "ASDF" "asdf" "UIOP" "uiop"))
     2)
    (:emacs-rex
     (swank:init-presentations)
     "COMMON-LISP-USER" t 3)
    (:emacs-rex
     (swank-repl:create-repl nil :coding-system "utf-8-unix")
     "COMMON-LISP-USER" t 4)
    (:return
     (:ok swank::present-repl-results)
     3)
    (:return
     (:ok
      ("COMMON-LISP-USER" "CL-USER"))
     4)
    (:emacs-rex
     (swank:autodoc
      '("defun" "my-butlast" nil "" swank::%cursor-marker%)
      :print-right-margin 162)
     "COMMON-LISP-USER" t 5)
    (:return
     (:ok
      ("(defun name lambda-list &body ===> body <===)" t))
     5)
    (:emacs-rex
     (swank:buffer-first-change "/Users/matlock/lang/common-lisp/test.lisp")
     "COMMON-LISP-USER" t 6)
    (:return
     (:ok nil)
     6)
    (:emacs-rex
     (swank:autodoc
      '("defun" swank::%cursor-marker%)
      :print-right-margin 162)
     "COMMON-LISP-USER" t 7)
    (:return
     (:ok
      ("(defun name lambda-list &body body)" t))
     7)

**Comment by stassats** [comment]
Can't reproduce.

**Comment by RyanMatlock** [comment]
Hmm, I was using `slime`/`sbcl` to work through a very basic intro to Common Lisp, so this is all very much above my head. I can't even seem to figure out how to downgrade to Emacs 25.3 to see if the problem persists.

**Comment by ungil** [comment]
It was fixed a few months ago, but that was after the latest release. Now that Emacs 26.1 is out it would be nice to make a new release available via quicklisp.

https://github.com/slime/slime/issues/400

**Comment by renzo-orsini** [comment]
I have the same problem. When starting slime with Emacs 26.1, after writing something like `defun` the same error is generated. I have installed quicklisp, and use ccl. The emacs debug backtrace is the same that above, that is `slime-autodoc--async%`  calls `eldoc-message` with 2 arguments while at most 1 is required.

**Comment by mvdwege** [comment]
I can reproduce. Emacs 26.1 on Fedora, slime and swank 2.21. Exact same symptoms.

Please re-open this issue.

**Comment by stassats** [comment]
Can't reproduce.

**Comment by varjagg** [comment]
Emacs 26.1 on OSX, same error scroll-up-command and scroll-down-command in addition to above mentioned. Same kind of backtrace as above.

**Comment by varjagg** [comment]
Boiled down to user error: slime was in loadpath both via quicklisp install and upstream git snapshot.

**Comment by TeslaBR** [comment]
Hello, I'm sorry but I'm having the exact same issue, and I can't figure out how to correct it from the description of the user error above. I installed Emacs using Brew, then SBCL, and then both quicklisp and slime from inside SBCL, everything from terminal. Any help would be greatly appreciated. 
This is my first participation on GitHub, and I've only been studying programming for about 6 months so please go easy on me... I'm really at a loss here

**Comment by stassats** [comment]
You haven't installed slime before at some other location? Is ```C-h v slime-version``` 2.22? Are you using tramp?

**Comment by cmatzenbach** [comment]
@TeslaBR I had the same issue.  Upgrading slime to version 2.22 like @stassats said is the fix for it.  If you installed via quicklisp, you can do `(ql:update-dist "quicklisp")`, otherwise if you installed it via emacs upgrade through there, or via git do it manually.

**Comment by Jaso-N7** [comment]
I had the same issue on emacs 26.1.
Even after executing `(ql:update-dist "quicklisp")`, emacs may complain about version mismatches, so it also helps to update your emacs slime package as well.
