### ISSUE TITLE
Emacs stuttering when slime is connected

### ISSUE THREAD

**Issue by szos** [slime/slime#453]
Ive recently come across an issue with slime after upgrading to emacs 26.1. After connecting slime (via M-x slime or M-x slime-connect) emacs begins hanging and stuttering. for example pressing C-f takes about 1.5 seconds to register when slime is connected. this isnt for every action; the stuttering gets better for a couple minutes, then gets bad for a couple minutes. Looking in the message buffer reveals that when this stutter occurs emacs is spitting out the following: 

error in process filter: progn: Wrong number of arguments: (0 . 1), 2
error in process filter: Wrong number of arguments: (0 . 1), 2

disconnecting from slime solves the stuttering, but i use slime most days to interact with SBCL.

**Comment by luismbo** [comment]
I've been using Emacs 26.1 for the past couple of days without issues. `M-x toggle-debug-on-error` might help you figure out where that's coming from.

**Comment by stassats** [comment]
You need to use the latest slime version.

**Comment by szos** [comment]
with toggle-debug-on-error as soon as I type anything into the slime sbcl repl it throws me into the debugger. the backtrace starts at a call to eldoc-message:

`  eldoc-message("%s" #("(defmacro name lambda-list &body body)" 1 9 (face font-lock-keyword-face) 10 14 (face font-lock-function-name-face) 27 32 (face font-lock-type-face)))`
the code that calls it is: 
`(progn (eldoc-message "%s" (slime-autodoc--format doc multilinep)))`
I can post the entirety of wha the backtrace spat out if need be.
the strangeness here is that this persists even with eldoc mode turned off globally, with no hooks calling it. which makes me wonder if its a problem with `(slime-autodoc--format doc multilinep)`, and not eldoc-message.

**Comment by luismbo** [comment]
Ah. `eldoc-message`, you need to update your SLIME, as @stassats said then.
