### ISSUE TITLE
C-x C-e evaluates too fast in GNU Emacs minibuffer

### ISSUE THREAD

**Issue by 717g301github** [slime/slime#454]
I have been observing this bug for at least a week or longer. It was working before just fine. Today I have installed slime under clean environment and without any other packages, and under the new user, just  to see if the problem is present in the newest version from MELPA, and the bug is there.

Description: when SLIME is loaded, the evaluation with C-x C-e is showing very fast in the Emacs minibuffer, so that is not workable any more. To see the result, I need to use C-c C-p which is not convenient.

This is serious issue that shall be solved.

How to replicate:

1. Load slime 2.21 from melpa
2. Try evaluating with C-x C-e to see

Emacs version that I am using is:  GNU Emacs 27.0.50 (build 3, x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars)  of 2018-06-15

**Comment by stassats** [comment]
Doesn't happen in Emacs 26.1

**Comment by 717g301github** [comment]
I have tested now with GNU Emacs 25.3.1. which is default on [Hyperbola GNU/Linux-libre](https://www.hyperbola.info) and the bug is not there, as you said, so I guess that belongs to GNU Emacs, I will see what to do there.

**Comment by 717g301github** [comment]
I pulled now recent and decent version of GNU Emacs and there is no bug. This can be closed.
