### ISSUE TITLE
slime-edit-definition in Emacs 26.1 gives "Wrong number of arguments: (6 . 7), 4" error

### ISSUE THREAD

**Issue by genworks** [slime/slime#455]
This error was popping up from editing any Lisp file in Slime 2.20 and seems to have been fixed in Slime v2.21. 

But even with Slime v2.21, with Emacs 26.1  the same (or similar) error is occurring reliably upon invoking `slime-edit-definition`

Is this due to a different API change?

**Comment by stassats** [comment]
Works fine here.

**Comment by genworks** [comment]
Clarification -- I now see that the error only occurs when I'm connected to a remote Lisp, with `M-x slime-connect`

The remote Lisp has swank from slime v2.21 loaded, and the local Emacs is running slime v2.21 as well. 

In *Messages* buffer, we have:

```
 if: Wrong number of arguments: (6 . 7), 4
```

**Comment by stassats** [comment]
Works fine here as well. Is your slime-tramp misconfigured?

**Comment by stassats** [comment]
You can post, but I actually don't know how to configure it right.
Do M-x toggle-debug-on-error

**Comment by daewok** [comment]
This is likely the same issue as #427

**Comment by luismbo** [comment]
Assuming this has been fixed by #459 as suggested by @daewok. Thanks.
