### ISSUE TITLE
add support for uiop:define-package

### ISSUE THREAD

**Issue by knobo** [slime/slime#466]
``` cl
;; File: contrib/slime-package-fu.el
(defvar slime-defpackage-regexp
  "^(\\(cl:\\|common-lisp:\\)?\\(defpackage\\|uiop:define-package\\)\\>[ \t']*")
```

**Comment by luismbo** [comment]
How about an unqualified `define-package`? If it's a good idea, can you tweak the the regex to handle that as well and open a pull request? Thanks.

**Comment by knobo** [comment]
But here it is.
 
`"^(\\(cl:\\|common-lisp:\\|uiop:\\|\\uiop/package:\\)?\(defpackage\\|define-package\\)\\>[ \t']*")
`

**Comment by knobo** [comment]
see #526
