### ISSUE TITLE
Which is better for "slime-setup with parameters" and "set slime-contribs"?

### ISSUE THREAD

**Issue by re-mx** [slime/slime#469]
Hello and sorry for my poor English.

Which of the following two ways is better?
1) :
```emacs-lisp
(slime-setup '(slime-repl slime-fuzzy))
```

2) :
```emacs-lisp
(setq slime-contribs '(slime-repl slime-fuzzy))
(slime-setup)
```

Thank you!

**Comment by luismbo** [comment]
Just doing `(setq slime-contribs '(slime-repl slime-fuzzy))` is enough. No need to call `slime-setup`. HTH.

**Comment by re-mx** [comment]
Thank you for your reply.

I saw this explanation in the documentation.

And I don't understand what you mean.

Do you mean the following?
Do 2, but only need to set `slime-contribs` without explicitly calling `(slime-setup)`.

Thank you.

BTW, when does this `(slime-setup)` need to be called? And what are the disadvantages of `(slime-setup '(slime-repl slime-fuzzy))?

**Comment by luismbo** [comment]
You don't need to call `slime-setup`.
