### ISSUE TITLE
"Symbol's function definition is void: screen-width" error when trying to start 

### ISSUE THREAD

**Issue by papa0** [slime/slime#473]
When I try to start SLIME in GNU Emacs 24.5.1 on Slackware 14.2 all I get is the error "Symbol's function definition is void: screen-width" and no SLIME.Web search turned up nothing helpful. Any clues?

**Comment by luismbo** [comment]
Try M-x toggle-debug-on-error to see where the error is coming from.

**Comment by papa0** [comment]
Thanks for the advice. The debugger told me the failure was in comint.el. Suspecting my version was badly out-of-date, I downloaded the latest from Github, and now SLIME starts. Case closed.
