### ISSUE TITLE
SLIME video dead link

### ISSUE THREAD

**Issue by wasserwerk** [slime/slime#479]
The "Marco Baringer's SLIME video (150MB, 55 minutes)." link on the slime page (https://common-lisp.net/project/slime/) is dead.

**Comment by luismbo** [comment]
@wasserwerk does this seem like a proper replacement? https://www.youtube.com/watch?v=_B_4vhsmRRI

**Comment by luismbo** [comment]
Note to self: the other links are dead (or smell funny: Flash) as well.

**Comment by wasserwerk** [comment]
That is indeed a good replacement, that I already found earlier myself, but the link on SLIME page is still dead and should point to somethong usable.

**Comment by stassats** [comment]
Was the original video 480p as well?

**Comment by luismbo** [comment]
Hmm. I'll ask the common-lisp.net admins if they have the original video somewhere.

**Comment by wasserwerk** [comment]
I'm not sure, but I think this was more than 480p.

**Comment by wasserwerk** [comment]
Thank you for the fix. The linked video has better resolution than on YT.

**Comment by stassats** [comment]
Maybe someone should reupload it to youtube before it goes down again. Although someone should probably shoot a remake.
