### ISSUE TITLE
emacs + lisp + allegro errno 99

### ISSUE THREAD

**Issue by ksuhakua** [slime/slime#492]
Hi) I have a problem when trying to start Slime+Allegro on Emacs, it gives me:
I tried it on 3 different computers and result is the same.
;Fast loading from bundle code/acldns.fasl
Error: "Local socket address not available" (errno 99) occurred while
creating a passive socket on 10.15.3.181 port "(any)" .
[condition type: socket-error]

Scrennshot of a error:
![slime](https://user-images.githubusercontent.com/34161204/51975802-d7bc3280-248b-11e9-91d1-5483d5df0286.png)

IP last octet may be different, 10.15.3 part stays the same.
I have 10.5.0.0/22 subnet on my network, when I turn off network connection it runs without errors.

here's what (let ((top-level:*zoom-print-length* 100))
    (tpl::zoom-command :all t :count t)) outputs:

Evaluation stack:
linux-gate.so.1: No such file or directory
Warning: while extracting symbols from /lib/i386-linux-gnu/librt.so.1: couldn't find .symtab section
Warning: while extracting symbols from /lib/i386-linux-gnu/libm.so.6: couldn't find .symtab section
Warning: while extracting symbols from /lib/i386-linux-gnu/libdl.so.2: couldn't find .symtab section
Warning: while extracting symbols from /lib/i386-linux-gnu/libc.so.6: couldn't find .symtab section
Warning: while extracting symbols from /lib/ld-linux.so.2: couldn't find .symtab section
Warning: while extracting symbols from /lib/i386-linux-gnu/libnss_files.so.2: couldn't find .symtab section
Warning: while extracting symbols from /lib/i386-linux-gnu/libnss_compat.so.2: couldn't find .symtab section
Warning: while extracting symbols from /lib/i386-linux-gnu/libnss_nis.so.2: couldn't find .symtab section
Warning: while extracting symbols from /lib/i386-linux-gnu/libnsl.so.1: couldn't find .symtab section

   (EXCL::READ-EVAL-PRINT-LOOP :CONTINUE-ERROR-STRING NIL :CONDITION
                               #<stream-error ADDRESS-NOT-AVAILABLE code: 99 creating a passive socket on 10.15.3.225 port "(any)"  
  NIL>)
   (EXCL::INTERNAL-INVOKE-DEBUGGER "Error"
                                   #<stream-error ADDRESS-NOT-AVAILABLE code: 99 creating a passive socket on 10.15.3.225 port "(any)"  
  NIL>
                                   T)
   (ERROR SOCKET-ERROR :IDENTIFIER :ADDRESS-NOT-AVAILABLE :STREAM NIL
          :ACTION
          "creating a passive socket on 10.15.3.225 port \"(any)\" "
          :CODE 99 :STRING "Cannot assign requested address")
   (EXCL::.ERRNO-STREAM-ERROR
      "creating a passive socket on 10.15.3.225 port \"(any)\" " NIL 99)  ->(SOCKET::MAKE-SOCKET-STREAM-INTERNET
      #<STANDARD-CLASS SOCKET:SOCKET-STREAM-INTERNET-PASSIVE> :TYPE
      :STREAM :CONNECT :PASSIVE :ADDRESS-FAMILY :INTERNET :LOCAL-PORT 0
      :LOCAL-HOST "localhost" :BACKLOG 5 :EOL #\Newline :REUSE-ADDRESS
      T)
   ((:RUNSYS "lisp_apply"))
   (SOCKET:MAKE-SOCKET :CONNECT :PASSIVE :LOCAL-PORT 0 :LOCAL-HOST
                       "localhost" :REUSE-ADDRESS T :BACKLOG 5)
   ((FLET (:TOP-LEVEL-FORM "allegro.lisp" 1143)
      SWANK-BACKEND:CREATE-SOCKET)
      "localhost" 0 :BACKLOG NIL)
   ((:RUNSYS "lisp_apply"))
   (SWANK-BACKEND:CREATE-SOCKET "localhost" 0 :BACKLOG NIL)
   (SWANK::SOCKET-QUEST 0 NIL)
   (SWANK::SETUP-SERVER 0 #<Closure # @ #x20890a7a> :SPAWN NIL NIL)
   (SWANK:START-SERVER "/tmp/slime.8189")
   (SYS::..RUNTIME-OPERATION "applyn" :UNKNOWN-ARGS)
   (FUNCALL SWANK:START-SERVER "/tmp/slime.8189")
   [... EXCL::%EVAL ]
   (EVAL (PROGN # # #))
   (TPL::READ-EVAL-PRINT-ONE-COMMAND NIL NIL)
   (EXCL::READ-EVAL-PRINT-LOOP :LEVEL 0)
   (TPL::TOP-LEVEL-READ-EVAL-PRINT-LOOP1)
   (TPL:TOP-LEVEL-READ-EVAL-PRINT-LOOP)
   ((:RUNSYS "lisp_apply"))
   (TPL:START-INTERACTIVE-TOP-LEVEL
      #<TERMINAL-SIMPLE-STREAM [initial terminal io] fd 0/1 @
        #x2017ef32>
      #<Function TOP-LEVEL-READ-EVAL-PRINT-LOOP> NIL)
   (EXCL::START-LISP-EXECUTION T)
   ((:RUNSYS "lisp_apply"))
   [... EXCL::THREAD-BIND-AND-CALL* ]
   (EXCL::THREAD-BIND-AND-CALL NIL #<Function START-LISP-EXECUTION-0>
                               (T))
(ACL-SOCKET::MAKE-SOCKET-STREAM-INTERNET
   #<STANDARD-CLASS ACL-SOCKET:SOCKET-STREAM-INTERNET-PASSIVE>
  :TYPE :STREAM
  :CONNECT :PASSIVE
  :ADDRESS-FAMILY :INTERNET
  :LOCAL-PORT 0
  ...)

**Comment by luismbo** [comment]
This doesn't seem to be a SLIME-specific issue. Try to figure out why `(SOCKET:MAKE-SOCKET :CONNECT :PASSIVE :LOCAL-PORT 0 :LOCAL-HOST
"localhost" :REUSE-ADDRESS T :BACKLOG 5)` fails. It's strange that creating a socket bound to `localhost` ends up bound to `10.15.3.225`.

**Comment by ksuhakua** [comment]
Where is this configuration stored and how can fix that?

**Comment by luismbo** [comment]
Did you try to create a socket in Allegro with out SLIME? Also, try another Lisp to see if that helps.

**Comment by ksuhakua** [comment]
So far I found a workaround, it's editing /etc/hosts file to point the link it's resolving from our DNS servers to 127.0.0.1. IP in the error was different because it resolved that link to different addresses within 10.15.3.x network. 
It's weird that Slime goes out to the local DNS server to create a socket, not just sticks to localhost on the local machine.

**Comment by luismbo** [comment]
Allegro has its own DNS client and it may be misconfigured. See https://franz.com/support/documentation/current/doc/dns.htm.
