### ISSUE TITLE
How to identify if a Lisp code is running through Slime?

### ISSUE THREAD

**Issue by ryukinix** [slime/slime#501]
Suppose I need to check if a Lisp code is running through Slime because I need a special behavior that this is used or just I didn't do things because break. The same can accomplished with conditional reader directives `#[+-]<symbol>` like:

```lisp

#-quicklisp
(let ((quicklisp-init (merge-pathnames ".quicklisp/setup.lisp"
                                       (user-homedir-pathname))))
  (when (probe-file quicklisp-init)
    (load quicklisp-init)))
```

Which only executes this code when quicklisp is not available. How can I do the same for Slime?

**Comment by luismbo** [comment]
Something like this, maybe:

```lisp
#+swank
(when swank::*emacs-connection*
  ...)
```

But this is probably a bad idea. What are you trying to do?

**Comment by ryukinix** [comment]
I'm trying to give a special behavior for this: https://github.com/ryukinix/lisp-chat/issues/11

cl-readline doesn't works well inside of SLIME. So I need to do a parametric polymorphic behavior in compile-time around the the [get-user-input](https://github.com/ryukinix/lisp-chat/blob/92937708f1e4c5135f19a71de95420358682c4b5/src/client.lisp#L18) function

**Comment by ryukinix** [comment]
> But this is probably a bad idea. What are you trying to do?
Why is a bad idea?

**Comment by luismbo** [comment]
Reader conditionals work at read-time so, if you happen to compile your code within SLIME then run it outside SLIME (or vice-versa), you won't get the desired result.

Which stream does `cl-readline` try to use? Inspect the value of `*standard-input*` (or whatever stream). When running within the SLIME REPL, it'll have a specific type like `slime-input-stream` so you can test for that.

HTH.

**Comment by ryukinix** [comment]
Thanks!!!!

**Comment by ryukinix** [comment]
> Which stream does cl-readline try to use? Inspect the value of *standard-input*, for instance. When running within the SLIME REPL, it'll have a specific type like slime-input-stream so you can test for that.


Just a doubt... `slime-input-stream` it's a CL class... I saw something in the code about initialization, but what exactly is the `read-string` of :input-fn (???) slot?

**Comment by luismbo** [comment]
@ryukinix it's a function that's invoked everytime something tries to read new input from the stream:

```
CL-USER> (swank::make-input-stream (lambda () (format nil "Hello, world! (~a)~%" (random 100))))
#<SWANK/GRAY::SLIME-INPUT-STREAM @ #x116e93142>
CL-USER> (read-line *)
"Hello, world! (93)"
NIL
CL-USER> (read-line **)
"Hello, world! (22)"
NIL
```

**Comment by ryukinix** [comment]
That's explain a lot of things! Thanks. I'll try something like that!
