### ISSUE TITLE
Setting SWANK:*GLOBALLY-REDIRECT-IO* has no effect

### ISSUE THREAD

**Issue by thibaultlanglois** [slime/slime#508]
Hi,
It seems that SWANK:*GLOBALLY-REDIRECT-IO* has no effect:
; SLIME 2.23
CL-USER> (setq SWANK:*GLOBALLY-REDIRECT-IO* :STARTED-FROM-EMACS)
:STARTED-FROM-EMACS
CL-USER> (sb-thread:make-thread #'(lambda () (print 'hello)))

HELLO 
#<SB-THREAD:THREAD FINISHED values: HELLO {1008B42F83}>
CL-USER> (setq SWANK:*GLOBALLY-REDIRECT-IO* t)
T
CL-USER> (sb-thread:make-thread #'(lambda () (print 'hello)))

HELLO 
#<SB-THREAD:THREAD FINISHED values: HELLO {1008B57F53}>
CL-USER> (lisp-implementation-version)
"1.4.16"
CL-USER> (lisp-implementation-type)
"SBCL"
CL-USER> 

I updated emacs from Arch repository today:
GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.7) of 2019-03-17

Before messages printed by threads were redirected to the *inferior-lisp* buffer. 
How can I get this behavior again ?

**Comment by stassats** [comment]
It has to be set in ~/.swank.lisp

**Comment by thibaultlanglois** [comment]
Fair enough, I tried this:
~/.swank.lisp is:
```
(setq swank:*globally-redirect-io* :started-from-emacs)
```
Then M-x slime, in `*inferior-lisp* I get:
```
 (progn (load "/home/tl/comp/lang/lisp/quicklisp/dists/quicklisp/software/slime-v2.23/swank-loader.lisp" :verbose t) (funcall (read-from-string "swank-loader:init") :from-emacs t) (funcall (read-from-string "swank:start-server") "/tmp/slime.3437"))

This is SBCL 1.4.16, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* ; loading #P"/home/tl/comp/lang/lisp/quicklisp/dists/quicklisp/software/slime-v2.23/swank-loader.lisp"
WARNING:
   redefining EMACS-INSPECT (#<SB-PCL:SYSTEM-CLASS COMMON-LISP:T>) in DEFMETHOD

; file: /home/tl/.swank.lisp
; in: SETQ SWANK:*GLOBALLY-REDIRECT-IO*
;     (SETQ SWANK:*GLOBALLY-REDIRECT-IO* :STARTED-FROM-EMACS)
; 
; caught WARNING:
;   undefined variable: SWANK:*GLOBALLY-REDIRECT-IO*
; 
; compilation unit finished
;   Undefined variable:
;     SWANK:*GLOBALLY-REDIRECT-IO*
;   caught 1 WARNING condition
;; Swank started at port: 39509.
39509
* WARNING:
   redefining THREAD-FOR-EVALUATION (#<STRUCTURE-CLASS SWANK::MULTITHREADED-CONNECTION>
                                     #<SB-MOP:EQL-SPECIALIZER :FIND-EXISTING>) in DEFMETHOD
```

Something must be wrong in my config. 
Any suggestion ?

**Comment by stassats** [comment]
You really want output to go to `*inferior-lisp*`? Then you are setting it to the opposite value… T enables IO redirection, NIL disables.

**Comment by thibaultlanglois** [comment]
Well actually setting `swank:*globally-redirect-io*` in .swank.lisp does not work, I get a warning in `*inferior-lisp*` :
```
; file: /home/tl/.swank.lisp
; in: SETQ SWANK:*GLOBALLY-REDIRECT-IO*
;     (SETQ SWANK:*GLOBALLY-REDIRECT-IO* :STARTED-FROM-EMACS)
; 
; caught WARNING:
;   undefined variable: SWANK:*GLOBALLY-REDIRECT-IO*
; 
; compilation unit finished
;   Undefined variable:
;     SWANK:*GLOBALLY-REDIRECT-IO*
;   caught 1 WARNING condition
;; Swank started at port: 39509.
```
The behavior I would like and worked until I updated emacs to 26.1 is that only print instructions made from non-REPL threads go to `*inferior-lisp*` while others go to the REPL.

This allows to run many background tasks without having the REPL cluttered with their output.

I am not sure Slime is to blame since this appeared after starting using emacs 26.1.

**Comment by stassats** [comment]
But does it actually work, if you disregard the warning? You need to use defparameter if you don't like warnings.

**Comment by thibaultlanglois** [comment]
You are right defparameter removes the warning. But it does not work:
```
; SLIME 2.23
CL-USER> swank:*globally-redirect-io*
T
CL-USER> (sb-thread:make-thread #'(lambda () (print 'hello)))

HELLO
#<SB-THREAD:THREAD waiting on: #<MUTEX "buffer write lock" (free)> {1008B82F83}>
 
CL-USER> 
```

**Comment by stassats** [comment]
You need to set it to NIL, not T.

**Comment by thibaultlanglois** [comment]
It worked. Thank you very much for you time and patience.

The variable documentation says:
```
  Documentation:
    When T globally redirect all standard streams to Emacs.
    When :STARTED-FROM-EMACS redirect when launched by M-x slime
```
Maybe it should say something about the NIL value.
