### ISSUE TITLE
strange locale

### ISSUE THREAD

**Issue by arademaker** [slime/slime#509]
When I start slime, I got the following message in the *inferior-lisp* buffer. 

```
WARNING: Setting locale failed.
  Check the following variables for correct values:
  LANG=en_BR.UTF-8
This is SBCL 1.5.0, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.
```

The ` LANG=en_BR.UTF-8` is quite strange since I have  all locales properly configured

```
$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

any idea? How slime get this value?

**Comment by luismbo** [comment]
M-x ielm and (getenv "LANG") to see if it's coming from the Emacs environment.

**Comment by arademaker** [comment]
thank you,  for some reason `(getenv "LANG") is giving me this strange value.  I added in the .emacs 

```
(setenv "LANG"   "en_US.UTF-8")
(setenv "LC_ALL" "en_US.UTF-8")
```

and the message was gone.
