### ISSUE TITLE
Support uiop:define-package for slime-export-class

### ISSUE THREAD

**Issue by Ambrevar** [slime/slime#523]
`slime-export-class` fails when `uiop:define-package` is used instead of `defpackage`.

I tried setting

```elisp
(defvar slime-defpackage-regexp
  "^(\\(cl:\\|common-lisp:\\|uiop:\\)?\\(defpackage\\|define-package\\)\\>[ \t']*")
```
and it worked.
What do you think?

**Comment by luismbo** [comment]
Could you try the last regex suggested in #466 to see if it works and open a pull request for it?

**Comment by Ambrevar** [comment]
I've reviewed #468 and I think it could be merged.

**Comment by knobo** [comment]
The new pull request is here: #526

**Comment by knobo** [comment]
It would be interesting to know why you want a pull request for this, as long as it's not from me.

**Comment by Ambrevar** [comment]
@knobo: What do you mean "not from you"?  Is there anything blocking the merge?

**Comment by knobo** [comment]
No, I don't understand why it's not merged.

**Comment by luismbo** [comment]
@knobo because you've opened and closed multiple issues and pull requests and it's all very confusing given the limited time I have to review these things. :( Anyway, thanks @knobo and @Ambrevar.
