### ISSUE TITLE
Producing Random Strings Leads to Invalid Protocol Messages

### ISSUE THREAD

**Issue by Shinmera** [slime/slime#527]
Doing something like
```common-lisp
(let ((string (make-string 1000)))
  (map-into string (lambda () (code-char (random #xFFFF)))))
```
Will cause Slime to barf:
```
Invalid protocol message:
Error during string-to-utf8: Unable to encode character 28320 as :UTF-8.
```

This is especially troublesome if such a string occurs in a backtrace, as SLDB will refuse to launch at all.

**Comment by tshatrov** [comment]
I had this problem with some Windows filenames (containing emoji like  🎨). SBCL pathnames had no problem with this symbol, but SLIME would complain every time such a pathname had to be printed to the REPL.

**Comment by stassats** [comment]
f851763d96fe8aa7f563ad4e00ba06d275316210 resolved that.
