### ISSUE TITLE
Could compile-string-for-emacs pass the line to swank-compile-string?

### ISSUE THREAD

**Issue by drmeister** [slime/slime#530]
Hi - we would like to get the line number for the start of the code that is compiled using C-c C-c in slime.  Currently swank-compile-string is only passed the character offset in the file.
compile-string-for emacs has the line number in the alist in position:
https://github.com/slime/slime/blob/master/swank.lisp#L2495
But it only extracts the position to pass to swank-compile-string.

Questions/requests...
(1) Could the swank-compile-string add a :line keyword argument?
(2) Does this require everyone to rewrite their swank-compile-string function? 
(3) If (2) is true - then maybe the position alist could be bound to a dynamic variable in compile-string-for-emacs and we can look there for the line information?

We need the line because we are using llvm and the debug information we are generating currently has the wrong line number information.

**Comment by luismbo** [comment]
Why do you want the line? Where will you be using it?

**Comment by drmeister** [comment]
We compile code using llvm and we provide metadata that attaches source locations to every instruction that is generated.  The source locations that llvm can use must be file names, line number and column and not character offsets from the start of the file.  
The line number is available in the caller compile-string-from-emacs and we would like it passed to swank-compile-string.

**Comment by drmeister** [comment]
We know what change to make to pass the line to swank-compile-string and we would either:
(1) have to change every implementation of swank-compile-string to accept and ignore the :line-no keyword argument.
(2) change defimplementation to add &allow-other-keys to the lambda list and open the possibility that bad keywords may be accepted in the future.

I'm comfortable changing slime/swank/clasp.lisp - but will people come after me if I change slime/swank/sbcl.lisp or slime/swank/abcl.lisp?

If I were given the go ahead to change all of the implementations of swank-compile-string in all implementations we could go ahead and implement this.

**Comment by drmeister** [comment]
For this I would submit a pull request.

**Comment by luismbo** [comment]
`swank:compile-string-for-emacs`'s position argument is `((:position <position>) (:line <line> <column>))` (and, BTW, it's 1-based, not 0-based).

Although column is very often 1 due to the way `beginning-of-defun` works by default, seems like we should pass that in. So, I'd say, either add two new arguments to `swank-compile-string`, line and column, or turn position into a plist with :position, :line and :column keys. I'm leaning  towards the first alternative, maybe. What do you think?

**Comment by drmeister** [comment]
That sounds like a fine idea to add two new arguments to swank-compile-string, line and column.
I will code it up and submit it as a pull request.

**Comment by luismbo** [comment]
Closed via #531.
