### ISSUE TITLE
Continuing fails when Swank version differs

### ISSUE THREAD

**Issue by Ambrevar** [slime/slime#533]
From https://github.com/atlas-engineer/next/issues/428:

The Next binary is built with a version of Swank that is not necessarily the one that the user is running in Emacs.  Thus SLIME complains:

```
Versions differ: 2.24 (slime) vs. nil (swank). Continue? (y or n)
```

Replying `y` results in

```
Lisp connection closed unexpectedly: connection broken by remote peer
```

Any clue what's happening?

**Comment by stassats** [comment]
Doesn't matter what's happening, as different versions are not guaranteed to work together.

**Comment by Ambrevar** [comment]
And any clue why the Swank version (from the binary) would be reported as `nil`?

**Comment by stassats** [comment]
Missing slime.el

**Comment by Ambrevar** [comment]
So how can a Lisp binary preserve the Swank version then?
Shall we keep slime.el stored in an expected location?

**Comment by stassats** [comment]
It should be needed only when loading swank.

**Comment by Ambrevar** [comment]
So when an SBCL binary with swank compiled-in starts up, is the version
number burned-in or is it queried from slime.el then?

**Comment by stassats** [comment]
It's read when loading the sources, otherwise it wouldn't be a good representation of the loaded code.

**Comment by Ambrevar** [comment]
OK, makes sense.
I'll try to fix the Guix package then.
Thanks for your support!
