### ISSUE TITLE
`slime` function disappear when buffer enable slime-mode

### ISSUE THREAD

**Issue by ccqpein** [slime/slime#539]
I usually use `M-x slime` to run slime in my common lisp buffer. However, today I cannot find `slime` function. It is weird that in my other languages' buffers, those disabled slime-mode like python or golang, I can find `slime` function. 

slime version: 20191129.1304
emacs version: GNU Emacs 27.0.50

**Comment by luismbo** [comment]
That is weird since command availability doesn't depend on the current buffer AFAIK. Can you reproduce the issue starting from `emacs -q`?

**Comment by ccqpein** [comment]
`emacs -q` won't load slime-mode, it doesn't have slime function.

**Comment by luismbo** [comment]
@ccqpein right, you'll need to load it. The idea is to try and reproduce the issue with a minimal configuration.

**Comment by ccqpein** [comment]
Ah, good idea. I am not sure I do it right or not, first, I open `emacs -q` and `load-file` `~/.emacs.d/elpa/slime-20191129.1304/slime.el`, it says `Package cl is deprecated`. Secondly, I `load-file`, but this time is `swank.lisp`, then `slime` function appears, but I cannot run it.

**Comment by ccqpein** [comment]
I think I found what's the problem. I stop using `helm-M-x` in my config file and then the `M-x` command can find `slime`. It looks like `helm-M-x` for some reason cannot find `slime` function, so it doesn't show off when I am in lisp-mode.

**Comment by luismbo** [comment]
FWIW, I use `helm-M-x` too and it finds `slime`.
