### ISSUE TITLE
Travis CI tests are failing 

### ISSUE THREAD

**Issue by gendl** [slime/slime#541]
Hi,

I just submitted a [PR](https://github.com/slime/slime/pull/540) and happened to notice that the Travis builds in .travis-ci.yml have been failing starting in November 2018. At least some of the failures have to do with installation of emacs on the docker image being used for the test. 

I'm not sure exactly why these are failing, but maybe someone who is more familiar could look at the .travis-ci.yml and see about getting the tests to work as a baseline? That way we can know whether new PRs are introducing regressions or not. I can try looking at it myself as well but I thought to open a bit of a discussion here first before trying to dive in (I'm still a total newbie when it comes to Travis CI and docker - the extent of my CI experience so far is just shell executor with gitlab-ci). 

Query: The latest released Gnu emacs is 26.3 - should the slime tests be including emacs 26 and maybe 25 in the tests, and maybe drop 23 at this point? 

Thanks,

 Dave

**Comment by luismbo** [comment]
Yes the Travis file is in need of an upgrade.

**Comment by luismbo** [comment]
The Travis build has been upgraded some time ago and now we have GitHub Actions too, although tests are still a bit finicky.
