### ISSUE TITLE
Question: How do you talk to a Swank server without Emacs?

### ISSUE THREAD

**Issue by momozor** [slime/slime#546]
Hi. Let's say I started a Swank server manually at port 7777. Then I run another SBCL repl for the client. However, I'm not sure how to set the client up and to call Swank 'functions' like *compile-and-load-file* or something like that. I've gone through the SLIME documentation but I don't really get it or I just missed the obvious instructions to do exactly this. Anyone have any idea?

**Comment by luismbo** [comment]
Have a look at https://github.com/brown/swank-client HTH
