### ISSUE TITLE
How do I reset the path to swank-loader.lisp

### ISSUE THREAD

**Issue by haziz** [slime/slime#548]
After removing a distro installed version of slime, my melpa (stable) installed slime version still insists on accessing the old system wide swank-loader.lisp.

How do I purge the system and reset the path to swank-loader.lisp

Please be very explicit about the steps, do not assume that I am comfortable with common lisp/slime/swank.

Thanks.

**Comment by luismbo** [comment]
Do you have an error message or something?

**Comment by haziz** [comment]
Based on advise from the #LISP IRC channel (thank you user madrik). The following did in fact solve the problem:

`sudo apt purge slime`

Merely "removing" SLIME using apt remove slime was not enough, however purging the program did remove the configuration files and solved the problem.
