### ISSUE TITLE
Slime causes DIVISION-BY-ZERO error with cl-cffi-gtk library

### ISSUE THREAD

**Issue by OrdoFlammae** [slime/slime#549]
When using the [cl-cffi-gtk](https://github.com/crategus/cl-cffi-gtk) library with SBCL normally, there are no problems. However, when I run any program that makes a GTK window using that library in SLIME (running on top of SBCL), I get a DIVISION-BY-ZERO error as soon as I move my mouse into the window (probably just generally when any event is raised). This issue has already been noticed (crategus/cl-cffi-gtk#6, crategus/cl-cffi-gtk#15, crategus/cl-cffi-gtk#28) and tested, but only exists when using SLIME, which is why I'm raising the issue here.

Bactrace:
```
arithmetic error DIVISION-BY-ZERO signalled
   [Condition of type DIVISION-BY-ZERO]

Restarts:
 0: [ABORT] abort thread (#<THREAD "cl-cffi-gtk main thread" RUNNING {1004391023}>)

Backtrace:
  0: ((FLET SB-UNIX::RUN-HANDLER :IN SB-SYS:ENABLE-INTERRUPT) 8 #.(SB-SYS:INT-SAP #X7FFFF6025EF0) #.(SB-SYS:INT-SAP #X7FFFF6025DC0))
  1: ("foreign function: call_into_lisp")
  2: ("foreign function: funcall3")
  3: ("foreign function: interrupt_handle_now")
  4: ("foreign function: interrupt_handle_now_handler")
  5: ((LAMBDA NIL :IN GTK:ENSURE-GTK-MAIN))
  6: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
  7: ((FLET SB-UNIX::BODY :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
  8: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
  9: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
 10: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
 11: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {7FFFF6026D4B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THR..
 12: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING {1004391023}> NIL #<CLOSURE (LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS) {1004390FCB}..
 13: ("foreign function: call_into_lisp")
 14: ("foreign function: new_thread_trampoline")
```

**Comment by stassats** [comment]
That doesn't look to be caused by Slime.

**Comment by OrdoFlammae** [comment]
OK. I don't have much experience with slime, but this issue has only ever occurred inside slime, so I thought that it should at least be looked at by the slime community.

**Comment by stassats** [comment]
It's cl-cffi-gtk's job to properly deal with float traps and any other foreign code issues.

**Comment by luismbo** [comment]
@OrdoFlammae a common theme with running GUI code in SLIME is that the slime-repl runs on a dedicated thread rather than the main thread and this sometimes causes issues. You may able to simulate that scenario outside SLIME simply by running your program from a new thread. HTH.
