### ISSUE TITLE
How to support  utf-8

### ISSUE THREAD

**Issue by MorosithIi** [slime/slime#550]
Hello there.
I'm using slime 20200228.1656 from melpa & sbcl2.0.2 & aquamacs 3.5 in Mac10.15.3.
When I do something like
`(with-open-file (s "~/例子.txt"
                   :external-format :utf-8)
  (format t "~a~%" (read-line s)))`
slime says that:
_NIL c-string encoding error:
  the character with code 20363 cannot be encoded.
   [Condition of type SB-INT:C-STRING-ENCODING-ERROR]_
as the picture:
![image](https://user-images.githubusercontent.com/23580174/76379417-faa55f80-638a-11ea-9376-12c0b1d8f610.png)

while sbcl in terminal just print "你好” which is in the “例子.txt”:
![image](https://user-images.githubusercontent.com/23580174/76379482-26c0e080-638b-11ea-855b-650f034869f0.png)

I have tried:

(set-language-environment "utf-8")
(setq file-name-coding-system 'gb18030)
(set-buffer-file-coding-system 'utf-8)
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
(set-selection-coding-system 'utf-8)
(set-next-selection-coding-system 'utf-8)
(set-default-coding-systems 'utf-8)
(set-clipboard-coding-system 'utf-8)  
(setq ansi-color-for-comint-mode t)
(modify-coding-system-alist 'process "*" 'utf-8)  
(setq-default pathname-coding-system 'utf-8)  
(prefer-coding-system 'utf-8)
(setq default-process-coding-system '(utf-8 . utf-8))  
(setq locale-coding-system 'utf-8)
(setq default-buffer-file-coding-system 'utf-8)  
(setq slime-net-coding-system 'utf-8-unix)
but that doesn't work
please help!

**Comment by stassats** [comment]
The error is coming from SBCL, not slime.

**Comment by luismbo** [comment]
@MorosithIi what does (describe "~/例子.txt") yield at the console?

**Comment by MorosithIi** [comment]
> The error is coming from SBCL, not slime.

Could you tell me how to resolve it?

**Comment by MorosithIi** [comment]
> @MorosithIi what does (describe "~/例子.txt") yield at the console?
This is what I get:
In Iterm2:
![image](https://user-images.githubusercontent.com/23580174/76421043-09693200-63de-11ea-9eac-862f45372db9.png)
In Aquamacs:
![image](https://user-images.githubusercontent.com/23580174/76421306-6a910580-63de-11ea-8ee0-6f44f1c04877.png)

**Comment by stassats** [comment]
Two points:
* I made the error in SBCL mention the external format, not the "NIL" you are seeing.
* I made SBCL finally default to UTF-8, as I am fed up with this kind of problems.

So if you build SBCL from git or wait until the next release (unless there's a strong push back that will cause it to be reverted, but I feel strongly about the issue, so won't give up easily).

**Comment by MorosithIi** [comment]
I have finally found a solution to it, and I posted it at [stackoverflow](https://stackoverflow.com/questions/60621647/how-to-open-a-file-which-name-contain-unicode-code-in-lispsbclslime?noredirect=1#comment107269134_60621647)
@stassats Thanks to your reply again.

**Comment by luismbo** [comment]
Ah, OK, so the default external format in SBCL was different when running under Emacs. Got it. Yeah, I'm with Stas here. In the age of Unicode, having the default external format differ based on locale/environment is just a PITA.
