### ISSUE TITLE
eval-in-frame'ing `(abort)` in sldb is a no-op

### ISSUE THREAD

**Issue by phoe** [slime/slime#556]
Example SLDB session:

```lisp
The value
  "2"
is not of type
  NUMBER
when binding SB-KERNEL::Y
   [Condition of type TYPE-ERROR]

Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT] abort thread (#<THREAD "new-repl-thread" RUNNING {100F9BD4C3}>)

Backtrace:
  0: (SB-KERNEL:TWO-ARG-+ 2 "2") [external]
  1: (+ 2 "2")
  2: (SB-INT:SIMPLE-EVAL-IN-LEXENV (+ 2 "2") #<NULL-LEXENV>)
  3: (EVAL (+ 2 "2"))
 --more--
```

When in SLDB, typing `e` to eval-in frame number `0` and then evaluating the form `(abort)` does not leave the debugger.

This is because SLDB establishes a `Return to sldb level 1.` `abort` restart that is then found and invoked by `(abort)`. This causes `(abort)` to effectively be a no-op.

As much as I understand this behaviour, it is counter-intuitive, since it prevents the user from calling the standard function `#'abort` to utilize the `1: [*ABORT] Return to SLIME's top level.` restart that they see listed in the debugger.

**Comment by joaotavora** [comment]
If I may opine here, `e` is primarily for evaluating forms and printing results, it's not for performing transfer of control.  You're already in a perfect setting to do that transfer via other means beforehand.  Other Lisps' debuggers also seem to work like that: evaluating `(abort)` at the debugger prompt of SBCL doesn't do what you think, either.  I may be missing something here, but it's pretty intuitive to me.
