### ISSUE TITLE
Saving fasl files into an output directory

### ISSUE THREAD

**Issue by nixin72** [slime/slime#561]
When loading a file named `file-name.lisp` using `slime-compile-and-load` it always creates a `file-name.fasl` file in the same directory as the `.lisp` file I just compiled. Is there a way to configure Slime to use something else as an output directory - for example, `~/.cache` or a `bin` directory for the project? For example, if my project structure is like this:
```
/ project-root
|-- proj.asd
|-- main.lisp
|--/ src
   |-- file-1.lisp
   |-- file-2.lisp
```
Then by the time I'm done working in a day, it'll often look like this:
```
/ project-root
|-- proj.asd
|-- proj.fasl
|-- main.lisp
|-- main.fasl
|--/ src
   |-- file-1.lisp
   |-- file-1.fasl
   |-- file-2.lisp
   |-- file-2.fasl
```
Instead of like this
```
/ project-root
|-- proj.asd
|-- main.lisp
|--/ src
|  |-- file-1.lisp
|  |-- file-2.lisp
|--/ bin
   |-- main.fasl
   |-- proj.fasl
   |--/ src
      |-- file-1.fasl
      |-- file-2.fasl
```
The later keeps my project much cleaner. It makes it much easier to look at my project in the terminal, prevents a lot of misclicks when opening files from something like `neotree` and gives more visual distinction between paths when looking at them in tools like `fzf`.

If there is a way to accomplish this, it would really great to know how. Thank you.

**Comment by stassats** [comment]
See slime-compile-file-options.

**Comment by anlsh** [comment]
I can't find any references to this variable in the documentation.

```
$ grep -irn slime-compile-file-options .
./slime.el:2532:(defcustom slime-compile-file-options '()
./slime.el:2549:        (options (slime-simplify-plist `(,@slime-compile-file-options
```

Maybe it should be added?

**Comment by Plisp** [comment]
Something like this would work assuming you've installed the `projectile` package.
```lisp
(defvar *my-fasldir* "fasl/")

(defun my-sly-compile-file ()
  (interactive)
  (let* ((rootdir (projectile-project-root))
         (fasldir (concat (projectile-project-root) *my-fasldir*))
         (relative-dir (string-trim-right
                        (substring (buffer-file-name (current-buffer)) (length rootdir))
                        "[^/]+"))
         (file-fasl-dir (concat fasldir relative-dir)))
    (make-directory file-fasl-dir t)
    (setq sly-compile-file-options (list :fasl-directory file-fasl-dir))
    (sly-compile-file)))

; if using use-package do
; :bind (:map sly-editing-mode-map ("C-c C-k" . #'my-sly-compile-file))
; otherwise
(bind-key "C-c C-k" #'my-sly-compile-file sly-editing-mode-map)
```

**Comment by nixin72** [comment]
@stassats - I see now that I can use that variable to set a single directory for every `.fasl` file to be output to, but I was definitely more looking for what @Plisp suggested with creating an output directory for the project - although thinking about it a little more, I actually don't think it makes too much of a difference for my uses anyways... 

Thank you both of you for your help!

**Comment by luismbo** [comment]
the slime-asdf provides this option too `(pushnew 'try-compile-file-with-asdf *compile-file-for-emacs-hook*)`
