### ISSUE TITLE
Keyword noise in minibuffer suggestion

### ISSUE THREAD

**Issue by phoe** [slime/slime#572]
Versions: SBCL 2.0.6, emacs 26.3, spacemacs develop, slime-20200530.1629

There is a ton of implementation-internal keywords in the minibuffer suggestion of `initialize-instance` and `shared-initialize` which used not to be there before. I wish it only showed keyword arguments I've defined myself.

![Zrzut ekranu z 2020-07-05 09-56-27](https://user-images.githubusercontent.com/15045546/86528175-e3dcc880-bea5-11ea-9d7b-1bd9640c7ab7.png)
![Zrzut ekranu z 2020-07-05 09-58-43](https://user-images.githubusercontent.com/15045546/86528207-21d9ec80-bea6-11ea-9105-f19ad1ba37e1.png)

**Comment by luismbo** [comment]
What's wrong with those arglists?

**Comment by phoe** [comment]
When I try to `defmethod initialize-instance`, I do not expect `system other-systems name initform initfunction type allocation initargs documentation readers writers lambda-list argument-precedence-order` to be there - I did not define these keywords, they aren't standard, they are complete noise to me, and they appear even though I have not yet typed the specializers for that method.

I assume that it is the case that SBCL defines a large number of keyword arguments on these functions inside its internals, but that number is so large that I cannot find the keyword arguments that I have actually defined, and excessive to the point where the arglist for `shared-initialize` does not even fit in the minibuffer.

**Comment by luismbo** [comment]
I think it's collecting the lambda lists of all methods, which makes sense for a function call but not when adding a method. Can you take this for a spin?

```diff
iff --git a/contrib/swank-arglists.lisp b/contrib/swank-arglists.lisp
index 6c12940d..d417a5d5 100644
--- a/contrib/swank-arglists.lisp
+++ b/contrib/swank-arglists.lisp
@@ -1020,7 +1020,7 @@ If the arglist is not available, return :NOT-AVAILABLE."))
     (('defmethod (#'function-exists-p gf-name) . rest)
      (let ((gf (fdefinition gf-name)))
        (when (typep gf 'generic-function)
-         (with-available-arglist (arglist) (decode-arglist (arglist gf))
+         (with-available-arglist (arglist) (decode-arglist (swank-mop:generic-function-lambda-list gf))
            (let ((qualifiers (loop for x in rest
                                    until (or (listp x) (empty-arg-p x))
                                    collect x)))
```

**Comment by phoe** [comment]
Better, but not yet complete. When `initialize-instance` is typed in completely, we get the following:

![Zrzut ekranu z 2020-07-05 23-30-14](https://user-images.githubusercontent.com/15045546/86542630-a3b62e00-bf17-11ea-8f79-ac4a2ba422a0.png)

But with the name not yet complete and filled-in by autocomplete, we still get all the keywords ever defined on `initialize-instance`:

![Zrzut ekranu z 2020-07-05 23-30-05](https://user-images.githubusercontent.com/15045546/86542625-8b461380-bf17-11ea-8782-2e274b7dd408.png)

**Comment by luismbo** [comment]
Not sure what's going on in that second example. Can't reproduce it. What completion method are you using? In any case, pushed https://github.com/slime/slime/commit/fac8069fc13eb62742c31967b314bddb6da6b6c7 which should fix the original problem.

**Comment by phoe** [comment]
The second example pops up for a second when I finish typing before it is replaced with the first example. It's not much of a nuisance; thank you for the fix!
