### ISSUE TITLE
error in process filter: Wrong type argument

### ISSUE THREAD

**Issue by yvm** [slime/slime#574]
Example code to reproduse the issue:
```
(defmacro test (a b c d)
  (labels (,(if d
		`(foo ,a)
		`(bar ,b)))
    (if (> a b)
	(progn
	  ,(if fill-p
	       ()
	       ())))))
```
Putting emacs point (cursor) after 5th line (into body of latter if) and pressing C-a, C-e produeces `*Messages*`:
> error in process filter: setq: Wrong type argument: listp, "Arglist Error: \"#S(SWANK::ARGLIST-DUMMY :STRING-REPRESENTATION \"fill-p\") fell through ETYPECASE expression. Wanted one of ((EQL :NOT-AVAILABLE) LIST).\""
> error in process filter: Wrong type argument: listp, "Arglist Error: \"#S(SWANK::ARGLIST-DUMMY :STRING-REPRESENTATION \"fill-p\") fell through ETYPECASE expression. Wanted one of ((EQL :NOT-AVAILABLE) LIST).\""

sbcl --version:
> SBCL 2.0.1

Slime and swank was installed with (ql:quickload "swank"):
> slime-version is a variable defined in ‘slime.el’.
> Its value is "2.24"

emacs-version:
> GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.20) of 2020-05-17, modified by Debian

`*slime-events*`:
> (:emacs-rex
>  (swank:autodoc
>   '("defmacro" "test"
>     ("a" "b" "c" "d")
>     ("labels"
>      (...)
>      ("if" ... ...)))
>   :print-right-margin 172)
>  "COMMON-LISP-USER" t 10)
> (:return
>  (:ok "Arglist Error: \"#S(SWANK::ARGLIST-DUMMY :STRING-REPRESENTATION \"d\") fell through ETYPECASE expression. Wanted one of ((EQL :NOT-AVAILABLE) LIST).\"")
>  10)

**Comment by stassats** [comment]
Can't reproduce.

**Comment by luismbo** [comment]
Can't reproduce either. Try clearing out the fasls in `~/.slime` perhaps.
