### ISSUE TITLE
No REPL with Emacs 26.3, slime 2.24

### ISSUE THREAD

**Issue by lsandig** [slime/slime#579]
I can't get the repl (or any other contribs) to start with emacs 26.3 and slime 2.24 (neither git nor melpa version).

Minmal .emacs:

    (add-to-list 'load-path "~/Code/git/slime/")
    (require 'slime-autoloads)
    (setq inferior-lisp-program "/usr/bin/sbcl")
    (add-to-list 'slime-contribs 'slime-repl)

Running `emacs /tmp/foo.lisp` opens the file with `lisp-mode` and `slime-mode` active.
Pressing `C-c C-z` switches to the `*inferior-lisp*` buffer. Pressing `C-c C-k` echoes `Not connected`.
No repl buffer is created. Also, most entries in the SLIME menu are greyed out.
Checking `C-h v slime-contribs` shows that the variable is indeed set to `(slime-repl slime-fancy)`.
Running `slime-setup` manually also does not change things.
Now I have run out of ideas of things to try.

**Comment by luismbo** [comment]
slime-fancy already includes slime-repl. Does it help if you don’t change the default value of slime-contribs?

**Comment by luismbo** [comment]
In any case, you didn’t mention `M-x slime`. Did you skip that step?

**Comment by lsandig** [comment]
You are right. Now I feel dumb. I somehow conflated `M-x slime-mode` and `M-x slime`. I had assumed the `*slime-repl*` would automatically be started whenever a buffer was opened in `slime-mode`, in a similar way to the `*inferior-lisp*` process. Thanks for clearing that up.

**Comment by luismbo** [comment]
The “Not connected” message could probably suggest slime. That’d be nice, maybe.

**Comment by lsandig** [comment]
That would be more intuitive, I agree.  ESS (the mode for the R statistics package) does it this way. There, if you want to evaluate some code and no R process is running or associated with the file buffer, it offers to connect to an existing one or start a new one. Maybe its possible to wrap such functionality around the evaluation/compilation keybindings in slime-mode?
