### ISSUE TITLE
The package `cl' is deprecated within Emacs 27.1

### ISSUE THREAD

**Issue by Grausicht** [slime/slime#584]
Emacs 27.1 shows this message on startup: 
Package cl is deprecated

Slime 2.26 makes use of package `cl' in different files. 

For example:

https://github.com/slime/slime/blob/fb12bac676ab51b75be19197e21ab4674479d627/slime.el#L66

To list all files requiring `cl' evaluate the following in *scratch*:

``` elisp
(require 'loadhist)
(file-dependents (feature-file 'cl))
```

**Comment by stassats** [comment]
They may deprecate as much as they want to, but it still works.

**Comment by luismbo** [comment]
The package name is deprecated. We should change that to cl-lib. Not a high priority, pull request welcome.

**Comment by jonatack** [comment]
Thanks @Grausicht, I can confirm that I've been seeing this as well.

**Comment by joaotavora** [comment]
> The package name is deprecated. We should change that to cl-lib. Not a high priority, pull request welcome.

Just noting that that by itself won't work, you need to rename the macros/functions that aren't `cl-` prefixed.  (like  `loop`-> `cl-loop`and `find` -> `cl-find`).  SLY just very recently rid itself of `cl`.

**Comment by dingesista** [comment]
In 2021 emacs 28 will throw an error: slime-tests.el:28:1: Warning: Package cl is deprecated
which points to slime.el line, where in line 66 there is (eval-when-compile (require 'cl)). 

Perhaps it's time to change this to (eval-when-compile (require 'cl-lib))

**Comment by luismbo** [comment]
@dingesista It's not a single line change as slime.el still uses macros from the cl package: defsetf and lexical-let.

**Comment by dingesista** [comment]
@luismbo gosh, I did not realise.  

Is there something here that I can help with?

**Comment by luismbo** [comment]
@dingesista yes, sure. lexical-let should be replaceable with plain let for files with lexical-binding enabled, and you'll have to figure out how to replace defsetf. You can probably take a peek at SLY to see how @joaotavora did it there.

**Comment by erjoalgo** [comment]
I am still getting this warning and I realize that 2f24389 didn't make it into the latest release. It would be nice if there could be a new release soon.
