### ISSUE TITLE
Use eww for slime-documentation-lookup

### ISSUE THREAD

**Issue by Sasanidas** [slime/slime#586]
Seems like the function that is use for searching the documentation is browse-url, this opens a new tab in the default browser.
I think it can be interesting giving that the hyperspec files are mostly html, eww can be quite fast and straight forward (also I don't have to leave Emacs).

I changed the function common-lisp-hyperspec with an optional argument, add a customize option (default to nil) and passing it to the function call `(hyperspec-lookup symbol-name slime-documentation-browse-eww)` in the slime-hyperspec-lookup function.

Is a simple change and can be easily implemented, if this is interesting for the project I can submit the pull request.

Thank you.

**Comment by luismbo** [comment]
You can customize the `browse-url-browser-function` to use eww. E.g., `M-x customize-variable RET browse-url-browser-function` and pick Eww from the list of available options. Or put `(setq browse-url-browser-function 'eww-browse-url)` in your `.emacs`. Hope that helps.

**Comment by PuercoPop** [comment]
You can even customize it to only open the hyperspec using eww

```
(setq browse-url-browser-function '(("\\(?:^http://www\\.lispworks\\.com/reference/HyperSpec.*\\)" . (lambda (url &rest args)
                                                                                                       (eww url)))
                                    ("." . browse-url-default-browser)))
```
