### ISSUE TITLE
sbcl is not found?

### ISSUE THREAD

**Issue by anta40** [slime/slime#587]
Hi, I'm on MacOS Big Sur.

I already have SBCL and emacs installed via homebrew:

> $ sbcl
> This is SBCL 2.0.11, an implementation of ANSI Common Lisp.
> More information about SBCL is available at <http://www.sbcl.org/>.

> GNU Emacs 27.1 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G95))
>  of 2020-08-12
> Copyright (C) 2020 Free Software Foundation, Inc.

Next is to setup slime. I followed the steps described in [this link:](https://gist.github.com/BlameOmar/9477900)

1. Make the following directory 

> $ mkdir -p ~/.local/opt

2. Run SBCL 

> $ sbcl

3. Put quicklisp.lisp in ~/Downloads
4. Setup quicklisp: 

> (load "~/Downloads/quicklisp.lisp") 
> (quicklisp-quickstart:install :path "~/.local/opt/quicklisp")
> (ql:add-to-init-file)
> (ql:quickload "quicklisp-slime-helper")
> (quit)

5. Create the emacs config file 

> vim ~/.emacs 
> (setq inferior-lisp-program "sbcl")
> (load (expand-file-name "~/.local/opt/quicklisp/slime-helper.el"))

6. Run emacs and start slime: 

> M-x slime

Previously, it worked. I could see the SBCL REPL at the bottom of Emacs and tried to define some functions, etc. Then I quitted the REPL by typing `(quit)` and closed Emacs. The next time I run Emacs and start slime, emacs pointed me this:

> Searching for program: No such file or directory, sbcl 

Running sbcl on terminal works fine, though.

**Comment by luismbo** [comment]
You can either ensure that PATH contains sbcl -- you can inspect that on Emacs using, e.g. `M-x ielm` and evaluating `(getenv "PATH")` -- or you can point `inferior-lisp-program` directly to your sbcl installation with `(setq inferior-lisp-program "/path/to/your/homebrew/sbcl")`.

I haven't used homebrew in a while, but maybe a third option is to ensure that sbcl is on the PATH via some homebrew command, somehow.

HTH.

**Comment by anta40** [comment]
Sorry for the late reply. Actually, there's a solution in the article I mentioned [above](https://gist.github.com/BlameOmar/9477900):

Edit your `~/.emacs` :

Replace
`(setq inferior-lisp-program "sbcl")`

with
`(setq inferior-lisp-program "/usr/local/bin/sbcl")`

Done :)

**Comment by luismbo** [comment]
Right, that solution was also mentioned [here](https://github.com/slime/slime/issues/587#issuecomment-748034957).
