### ISSUE TITLE
Documentation suggests non-existent keyword argument

### ISSUE THREAD

**Issue by contrapunctus-1** [slime/slime#591]
[This page](https://common-lisp.net/project/slime/doc/html/Setting-up-the-lisp-image.html) suggests this call -
`(swank:create-server :port 4005  :dont-close t :coding-system "utf-8-unix")`
but evaluating that results in an unknown keyword argument error for `:coding-system`.

Would you like me to make a PR correcting the call in the documentation?

**Comment by luismbo** [comment]
Yes, please. Thanks. 👍
