### ISSUE TITLE
Improve support for :local-nicknames

### ISSUE THREAD

**Issue by cgay** [slime/slime#598]
I realize that `:local-nicknames` is not a part of the standard, but it's a very useful addition that (I believe) is being used more and more these days. Would it be possible to make SLIME support it (better)?  Here's our use case:

https://github.com/qitab/cl-protobufs/blob/0d00ccfcfcf7f4fbfba04b84ae41edd0f7db9d17/protoc/file.cc#L95

The Common Lisp `protoc` plug-in, for generating CL code from a protocol buffer definition, uses a local nickname to make the code more readable. It would be super useful, for understanding that generated code, to be able to use macro expansion in SLIME, but SLIME doesn't recognize `pi` as a local alias for `cl-protobufs.implementation`.

We've also taken to using local nicknames in many test files, to import the generated protobuf code with a `pb` nickname, and similar arguments apply there.

What's the right way to implement this?  Is it possible to query SBCL (et al) for local nicknames for a given package?

Thanks.

**Comment by cgay** [comment]
I guess you wouldn't be able to ask for nicknames for a package since the nicknames are relevant to a particular scope. Filename + line number?  ugh.  Parse the `defpackage`?  Not sure how SLIME currently handles packages.

**Comment by luismbo** [comment]
SLIME's fuzzy completion already supports package local nicknames. Fuzzy completion really should be the default, so I'll fix that.

**Comment by luismbo** [comment]
Actually, the default completion settings work for package local nicknames as well. What exactly is not working?

**Comment by cgay** [comment]
Sigh...I think this was just confusion on my part. I was looking at a different test that also had the `pi` local nickname but which had not already been compiled into the image. Sorry for the bother!

**Comment by luismbo** [comment]
@cgay in any case, while investigating your question, I've added PLN support for ACL, CCL, Clasp and Lispworks which were missing and changed the inspector to list package local nicknames when inspecting a package object. 👍
