### ISSUE TITLE
slime won't load in v.28 (obsolete calls to make-obsolete)

### ISSUE THREAD

**Issue by projectivemodule** [slime/slime#601]
I built emacs v.28 recently to use the native-comp feature and noticed that `slime` (v. 2.26.1) wouldn't load. The problem is that there are some calls to functions in `byte-run.el` whose function/macro signatures were changed:  https://lists.gnu.org/archive/html/emacs-devel/2021-01/msg00320.html   (The third argument is now required, not optional.) People have reported that this breaks other packages as well:  https://old.reddit.com/r/emacs/comments/kqb9s9/cannot_recompile_packagess_error_wrong_number_of/

grep-ing the `slime` source for calls with two arguments produced the following:

    lib/hyperspec.el:701:	  ("make-instances-obsolete" "f_mk_i_1.htm")
    lib/hyperspec.el:2141:     ("break-on-warnings-obsolete:remove" "iss020.htm")
    lib/hyperspec.el:2270:     ("eval-when-obsolete-keywords:x3j13-mar-1993" "iss148.htm")

A quick look suggests that the calls to these functions in `slime.el` and `slime-autoloads.el` are okay, but someone should check them anyway. Since I wasn't sure exactly what needs to be fixed (or what the missing third arguments should be), I'm working around this by loading parts of the v. 27 `byte-run.el` with the old function signatures.

**Comment by luismbo** [comment]
I believe this is fixed in master. Let us know if it’s not. Thanks.
