### ISSUE TITLE
Warnings under native-compilation Emacs (gccemacs)

### ISSUE THREAD

**Issue by david-christiansen** [slime/slime#603]
Under gccemacs, loading Slime results in a series of warnings like this:
```
Error (bytecomp): Wrong type argument: listp, #<subr slime-alistify>
Error (bytecomp): Wrong type argument: listp, #<subr slime-log-event>
Error (bytecomp): Wrong type argument: listp, #<subr slime-events-buffer>
Error (bytecomp): Wrong type argument: listp, #<subr slime-process-available-input>
...
```
This seems to come from `slime--compile-hotspots`, because native-compiled functions do not satisfy `byte-code-function-p`. However, they do satisfy `subrp`, and adding an `or` there seems to work locally to allow the function to be called without emitting warnings.

**Comment by luismbo** [comment]
Pushed your suggested fix, thanks. Is it possible to invoke the native compiler interactively as we do with `byte-compile`?

**Comment by david-christiansen** [comment]
Thank you!

I don't know if it's exactly what you want, but gccemacs has the function `native-compile` that seems to do what you would want.

**Comment by luismbo** [comment]
If you'd like to submit a pull request adapting `slime--compile-hotspots` to use `native-compile` when available, that'd be nice! Thanks.

**Comment by david-christiansen** [comment]
I'm afraid I'm not really using Slime for anything right now - I wouldn't know enough to test it properly, or how to set everything up correctly. In any case, I got this error because the code was already native compiled, so I suspect it's happening.
