### ISSUE TITLE
Slime debugger fails to name the error

### ISSUE THREAD

**Issue by Devon7** [slime/slime#604]
What it **should** say:

`> Error: (443 444 444 444 445 445 446 446 447 447 448 448 448 449 449 450 450 451 451 452 ...) doesn't match array dimensions of #<SIMPLE-VECTOR 33071> .
`

What it says:

```
(443 444 444 444 445 445 446 446 447 447 448 448 448 449 449 450
	#<... 1068 lines elided ...>
 6458 6458 6459 6459 6460 6..
   [Condition of type SIMPLE-ERROR]

Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT-BREAK] Reset this thread
 3: [ABORT] Kill this thread
```

**Comment by luismbo** [comment]
What Lisp is this? What value do you have in `*print-length*`? Can you share a snippet that yields this error?

**Comment by Devon7** [comment]
```
;; No-hands bug demo with CCL under MacOSX - wait for the timers.
;; Workaround: click on [Condition of type TYPE-ERROR]

(call-process "Open" nil t nil "-n" "-a"
	      "/Applications/Emacs-27.1.app/Contents/MacOS/Emacs-x86_64-10_14" "--args"
	      "--no-init-file" "--no-site-file" "--no-site-lisp"
	      "--load" "~/quicklisp/slime-helper.el"
	      "--eval" (prin1-to-string
			'(progn
			   (run-at-time 1 nil (defun bug-demo-1 ()
						(slime-repl)
						(insert "(/ (make-array 99999))")
						(slime-repl-return)))
			   (run-at-time 2 nil (defun bug-demo-2 ()
						(delete-other-windows)
						(goto-char (point-max))
						(recenter -1)
						(message "print-length = %S" print-length)))
			   (slime))))
```

**Comment by luismbo** [comment]
I see. I think SLDB has bad defaults for `*print-length*` and `*print-level*`. This patches changes that to mimic the ones SBCL uses, which seem more sensible. Can you give it a go?

```diff
diff --git a/swank.lisp b/swank.lisp
index 6af52bc8..4efca26a 100644
--- a/swank.lisp
+++ b/swank.lisp
@@ -2161,8 +2161,8 @@ conditions are simply reported."
                 (*print-pretty* t)
                 (*print-right-margin* 65)
                 (*print-circle* t)
-                (*print-length* (or *print-length* limit))
-                (*print-level* (or *print-level* limit))
+                (*print-length* (or *print-length* 12))
+                (*print-level* (or *print-level* 6))
                 (*print-lines* (or *print-lines* limit)))
             (print-condition condition stream))
         (serious-condition (c)
```

**Comment by stassats** [comment]
12 seems to be too low.

**Comment by luismbo** [comment]
64? 🤷‍♂️

**Comment by Devon7** [comment]
12 is too low but **way** better than NIL.
Investigating ways to never clobber essential parts of error messages, I tried
`(/ (make-array 9999 :initial-element (make-string 9999 :initial-element #\*)))`
Lisp connection closed unexpectedly: connection broken by remote peer

**Comment by luismbo** [comment]
The `*inferior-lisp*` buffer should have some clue on what happened there.

**Comment by Devon7** [comment]
It would if Emacs weren't tight-looping in redisplay_internal because of the notorious slong bug, where long line wedge it for hours or days.  I'll check back in a few hours.

**Comment by luismbo** [comment]
Pushed a fix with 64 rather than 12. HTH.

**Comment by stassats** [comment]
64 seems arbitrary too. It's barely one line on the screen.

**Comment by luismbo** [comment]
I don't think that's how `*print-length*` works.

**Comment by stassats** [comment]
Doesn't work how? One thing I know, it doesn't work at all for strings.

**Comment by luismbo** [comment]
Yes, `*print-length*` is not a bullet-proof solution to this problem, but this improves things, I think. For strings, it seems like the hyperspec hints that `*print-lines*` could help, but SBCL doesn't seem to truncate strings, which is probably sensible since that could easily go unnoticed.

**Comment by stassats** [comment]
SBCL has `sb-ext:*print-vector-length*`, but that's just SBCL.

**Comment by luismbo** [comment]
CCL seems to have `*print-string-length*`. Couldn't find anything for Lispworks, CLISP ou Allegro.

**Comment by luismbo** [comment]
Ah, `*print-lines*` truncates strings on Lispworks and Allegro.

**Comment by joaotavora** [comment]
FWIW in SLY i put in a `slynk:*string-elision-length*` for similar use cases.

**Comment by luismbo** [comment]
That's a good idea, but it doesn't help in this specific case where we're printing condition messages does it?

**Comment by joaotavora** [comment]
I don't know, that's why I said "similar use cases". The variable is unbound globally, and only kicks in the slynk print functions (similar to swank print functions) which print objects.  I suppose it could kick in there, depends on how you set it up. I just saw you talking about *print-length* not affecting strings and remembered I hit that same problem a year or so ago.
