### ISSUE TITLE
symbol-indentation fails on symbols with unknown arglist

### ISSUE THREAD

**Issue by slyrus** [slime/slime#605]
On recent SBCLs (e.g. 2.1.1.56-2576188ce), swank fails in symbol-indentation on compiling lparallel. The failure happens in symbol-indentation. The proximal cause is that the arglist is computed with (arglist symbol) which, for some reason, returns :unknown. This is then checked in an etypecase form against (member :not-available) or for being a list, but since :unknown is neither of those, an error is thrown. If I change the (etypecase ...) form to (member :not-available :unknown), things work. Alternatively, one could modify arglist to return :not-available.

**Comment by luismbo** [comment]
That last option sounds good since that's how the arglist definterface is documented. `sb-introspect:function-lambda-list` doesn't document that `:unknown` return value, are there others?

**Comment by stassats** [comment]
Not a problem after sbcl/sbcl@0c73891

**Comment by luismbo** [comment]
That doesn’t seem right. Not knowing the lambda list should be different from knowing that the function accepts no arguments.

**Comment by luismbo** [comment]
I see that it's been changed to return two values. https://github.com/sbcl/sbcl/commit/a977e1a04fafd40240a5219ef15dbdd018b28a40 👍
