### ISSUE TITLE
crash calling undefined function

### ISSUE THREAD

**Issue by Devon7** [slime/slime#608]
Launch Emacs with` --no-init-file --no-site-file --no-site-lisp`
in `*scratch*` evaluate	`(progn (load "~/quicklisp/slime-helper.el") (slime))`
in `*slime-repl ccl*` evaluate	`(x)`
REPL unresponsive due to CCL crash
MacOSX Mojave 10.14.6
Emacs 27.1
CCL 1.12
SLIME 2.26.1
[slime-bug.txt](https://github.com/slime/slime/files/6144094/slime-bug.txt)

**Comment by stassats** [comment]
If CCL is crashing, then it has nothing to do with slime.

**Comment by luismbo** [comment]
@Devon7 I don't have a macOS machine, but that test case works fine for me with CCL 1.12 on Linux so that's probably a CCL bug that you should report on their issue tracker.
