### ISSUE TITLE
Call to PATHNAME-NAME in SWANK:LIST-ALL-SYSTEMS-IN-CENTRAL-REGISTRY gives wrong result for system names containing '.'

### ISSUE THREAD

**Issue by spwhitton** [slime/slime#609]
Hello,

I have an ASDF system called "com.silentflame.consfig".  The function SWANK:LIST-ALL-SYSTEMS-IN-CENTRAL-REGISTRY maps PATHNAME-NAME over all system names and thus corrupts "com.silentflame.consfig" to "com.silentflame" which is a system which does not exist.  This makes it difficult to use the repl shortcut for ASDF:LOAD-SYSTEM to load my system, because "com.silentflame" shows up as a completion candidate but that would not be a valid system to load.

Thanks.

**Comment by Uthar** [comment]
I have this problem as well. There is an extra call to `pathname-name` that causes this. One can fix this with this patch:

```patch
--- a/contrib/swank-asdf.lisp
+++ b/contrib/swank-asdf.lisp
@@ -385,9 +385,8 @@
   "Returns a list of all systems in ASDF's central registry
 AND in its source-registry. (legacy name)"
   (unique-string-list
-   (mapcar
-    #'pathname-name
-    (while-collecting (c)
+   (while-collecting
+     (c)
       (loop for dir in asdf:*central-registry*
             for defaults = (eval dir)
             when defaults
@@ -402,7 +401,7 @@
             (destructuring-bind (directory &key recurse exclude) entry
               (register-asd-directory
                directory
-               :recurse recurse :exclude exclude :collect #'c))))))))
+               :recurse recurse :exclude exclude :collect #'c)))))))
 
 (defslimefun list-all-systems-known-to-asdf ()
   "Returns a list of all systems ASDF knows already."
```
