### ISSUE TITLE
Extract hyperspec frontend into a separate package?

### ISSUE THREAD

**Issue by lassik** [slime/slime#615]
`lib/hyperspec.el` appears to be self-contained and could be useful even without SLIME.

@sam-s just posted a simple, modernized [`clhs` package to MELPA](https://github.com/melpa/melpa/pull/7529) and says:

> SLIME's `hyperspec.el` is the old version and only supports 8.3 file names.
> My version supports both the original long file names and the new 8.3 ones (as well as any future compliant version).
> 
> The correct approach is to remove `hyperspec` from SLIME and [Sly](https://github.com/joaotavora/sly/blob/master/lib/hyperspec.el) and make both of them depend on `clhs`.

What do the SLIME maintainers think?

**Comment by joaotavora** [comment]
SLY maintainer here: traditionally both SLIME and SLY have been installable and completely functional from simple Git checkouts, without any other dependency, even ELPA/MELPA.  I use them like that. They can also both be gotten from a Lisp package manager called Quicklisp, which I don't think does any Elisp package resolution.  I'm not in love with the latter method but many people do use it. So your suggestion makes sense, but it's not 100% practical.  There should at least be some fallback to a bundled version.

**Comment by joaotavora** [comment]
Yes, but Emacs releases are really sparse and many Lispers are using old Emacs with bleeding edge SLIME/SLY.  The Elisp package repo is the "correct" solution, but since there has to be a decent fallback otherwise you break the setup of lots of people.

**Comment by luismbo** [comment]
@lassik we can do the same thing we do for `macrostep.el`. Include a copy in `lib/` but use a dependency for the MELPA package.

**Comment by stassats** [comment]
Generally, I dislike changes for the sake of changes.

**Comment by lassik** [comment]
@joaotavora 's idea is ingenious and seems to me like the best of both worlds.

https://github.com/melpa/melpa/blob/master/recipes/slime is the specification for how to build the MELPA package of SLIME. It mentions `lib/hyperspec.el` directly. If we dropped that, and added a separate `hyperspec` (or `clhs`) package to MELPA, that ought to work for everybody.

**Comment by lassik** [comment]
@luismbo  's idea is ingenious and seems to me like the best of both worlds.

https://github.com/melpa/melpa/blob/master/recipes/slime is the specification for how to build the MELPA package of SLIME. It mentions `lib/hyperspec.el` directly. If we dropped that, and added a separate `hyperspec` (or `clhs`) package to MELPA, that ought to work for everybody.

**Comment by luismbo** [comment]
In any case, that new clhs package has the drawback (IMHO) that it requires downloading and parsing the hyperspec symbol table for each Emacs session. I don't we want to bother with it at this point. Thanks for letting us know, though.
