### ISSUE TITLE
Symbol "%SIMPLE-FUN-NEXT" not found in the SB-KERNEL package - SBCL 2.1.4

### ISSUE THREAD

**Issue by lukehesluke** [slime/slime#616]
Hi, I get this error when attempting to quickload swank on my SBCL 2.1.4. This is on Mac OS X, but I suspect that the issue is cross platform:

```
Symbol "%SIMPLE-FUN-NEXT" not found in the SB-KERNEL package
```

More context:

```
* (ql:quickload '(swank))
To load "swank":
  Load 1 ASDF system:
    swank
; Loading "swank"
..................................................
[package swank/sbcl]............; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Symbol "%SIMPLE-FUN-NEXT" not found in the SB-KERNEL package.
;   
;       Line: 1597, Column: 54, File-Position: 64461
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file ~/quicklisp/dists/quicklisp/software/slime-v2.24/swank/sbcl.lisp" {10040A8F83}>
;; 
;; Error compiling ~/quicklisp/dists/quicklisp/software/slime-v2.24/swank/sbcl.lisp:
;;   COMPILE-FILE returned NIL.
;; 
```

This seems to be a result of this change to SBCL: https://github.com/sbcl/sbcl/commit/e103be077521e5f8918da7e346df6946157e5912 as pointed out in this comment: https://github.com/rigetti/qvm/issues/263#issuecomment-778635205

**Comment by stassats** [comment]
Are you sure you're using the right slime version?

**Comment by lukehesluke** [comment]
Thanks for your comment @stassats. Apologies, I'm new to Common Lisp. I had Slime installed via Spacemacs. I'm not sure what's happened (maybe Spacemacs updating its own packages?), but my local version of slime is now `slime-v2.26.1` rather than `slime-v2.24`. I had been using Clozure CL for a bit and then checked in again on SBCL after seeing your comment and now `(ql:quickload 'swank)` works 👍
