### ISSUE TITLE
using fuzzy-completions outside emacs

### ISSUE THREAD

**Issue by eko234** [slime/slime#621]
Hi, I'm trying to use the function fuzzy-completions from the fuzzy contrib package, I know the function is not external, but when i try to call it with swank::fuzzy-completions I'm notified that the symbol/function is undefined, I would like to know how I should go about it.

**Comment by stassats** [comment]
It's a contrib, you need to somehow load it.

**Comment by eko234** [comment]
I was looking into the cl-lsp repo and saw what you just said, sorry I'm still learning about the ecosystem, thanks.
