### ISSUE TITLE
Error compiling sbcl.lisp

### ISSUE THREAD

**Issue by GregoryBonar** [slime/slime#624]
I get an error when attempting to run slime after installation:
* ; loading #P"/Users/gregorybonar/quicklisp/dists/quicklisp/software/slime-v2.24/swank-loader.lisp"
; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Symbol "%SIMPLE-FUN-NEXT" not found in the SB-KERNEL package.
;   
;       Line: 1597, Column: 54, File-Position: 64461
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /Users/gregorybonar/quicklisp/dists/quicklisp/software/slime-v2.24/swank/sbcl.lisp" {1003D1EAD3}>
;; 
;; Error compiling /Users/gregorybonar/quicklisp/dists/quicklisp/software/slime-v2.24/swank/sbcl.lisp:
;;   COMPILE-FILE returned NIL.
;;

**Comment by stassats** [comment]
It says 2.24, but the latest slime version is 2.26.1.
