### ISSUE TITLE
hyperspec-lookup uses slime REPL prompt as a candidate

### ISSUE THREAD

**Issue by sionescu** [slime/slime#692]
For example, when the REPL buffer is like:

   ; SLIME 2013-04-23
   CL-USER> |

When emacs' cursor is at the postion designated by the bar | and then M-x hyperspec-lookup,
the prompt of emacs' minibuffer is like:

   Look up symbol in Common Lisp Hyperspec: cl-user> |

inside which the string "cl-user> " is kinda disturbing(also the bar | above means the cursor position).

the attached patch uses the 'face text property of the slime REPL prompt to remove such cases.

Launchpad Details: [#LP1176484](https://bugs.launchpad.net/bugs/1176484) Madsen Zhang - 2013-05-05 05:32:04 +0000

**Comment by sionescu** [comment]
Attachment: [patch.txt](https://api.launchpad.net/1.0/slime/+bug/1176484/+attachment/3665463/data)



Launchpad Details: [#LPC](https://bugs.launchpad.net/slime/+bug/1176484/comments/1) Madsen Zhang - 2013-05-05 05:32:04 +0000

**Comment by sionescu** [comment]
I can't reproduce it on emacs 24.3.1

Launchpad Details: [#LPC](https://bugs.launchpad.net/slime/+bug/1176484/comments/2) Stas Boukarev - 2013-05-05 12:05:33 +0000

**Comment by sionescu** [comment]
occurred on both linux and osx:

Emacs 24.3.50.1
Slime 2013-04-24

Launchpad Details: [#LPC](https://bugs.launchpad.net/slime/+bug/1176484/comments/3) Madsen Zhang - 2013-05-07 13:44:35 +0000

**Comment by stassats** [comment]
I suppose I still can't reproduce it.
