### ISSUE TITLE
swank vs. slime version difference

### ISSUE THREAD

**Issue by joshcho** [slime/slime#709]
This seems like a known issue, but I cannot for the life of me figure this out. I am trying to use version 27 as my emacs (29.0.5.0) is incompatible with previous versions. Since quicklisp-slime-helper is not updated (still at 26), I manually cloned the slime repo into `~/.quicklisp/dists/quicklisp/software`. I also changed some .txt files in quicklisp in order to reflect the new version.

I still get slime and swank have different versions when connecting. What could be the issue here?

**Comment by luismbo** [comment]
How are you loading SLIME from your `.emacs`?

**Comment by joshcho** [comment]
`  (load (expand-file-name "~/.quicklisp/slime-helper.el"))
  (slime-connect "localhost" 4004 nil nil) ; for stumpwm
`
This is at the beginning of .emacs

**Comment by luismbo** [comment]
Maybe drop that and load your clone SLIME directly. See the README for instructions on how to do that.
