### ISSUE TITLE
debugger hook not working after image dump

### ISSUE THREAD

**Issue by hemml** [slime/slime#716]
I'm dumping an SBCL image using `(sb-ext:save-lisp-and-die path :executable t :save-runtime-options t :purify t :toplevel #'run-daemon))` to make an executable binary.
When binary is started, I'm starting a swank server via `(swank:create-server :port my-port :dont-close t)` and connecting to it.
It seems, what debugger hook don't installed properly in this case -- if an error occurs, the debugger not invoking, also, standard output don't redirected to the slime. 

What I'm doing wrong? Does swank need some specific initialization procedure after image starts?

**Comment by hemml** [comment]
Upd.: if I'm executing a function with `(break)` via REPL, the debugger appears, but if the same function is executing via Hunchentoot handler the debugger is not raised.

**Comment by luismbo** [comment]
See <http://edicl.github.io/hunchentoot/#*catch-errors-p*> and <https://slime.common-lisp.dev/doc/html/Global-IO-Redirection.html>. HTH.

**Comment by hemml** [comment]
Unfortunately`(setf swank:*globally-redirect-io* t)` and `(setf hunchentoot:*catch-errors-p* nil)` changes nothing :(

**Comment by luismbo** [comment]
Can you produce a recipe for replicating your issue?

**Comment by hemml** [comment]
I have tried to make a minimal possible example and made https://gist.github.com/hemml/f3068782dc2039cd666c5f079b9f6c9c -- save it as `test-swank.lisp` and execute `sbcl --load test-swank.lisp`. The `test-swank` executable will be created. Start it and connect slime to it via 4005 port. Open http://127.0.0.1:8080 to trigger a `(break)` condition. 

I see the debugger output, but the debugger itself is not started.

My original code is much more complicated (I can give you a link and instructions, if you want) and I don't see the output in my code, but I believe, the debugger not raised by the same reason.

**Comment by luismbo** [comment]
`swank:stop-server` is asynchronous, and `destroy-thread` is also best avoided. At least give `swank:stop-server` some time to stop the swank server gracefully. Do you have to run Hunchentoot and SWANK before saving the image?

**Comment by hemml** [comment]
Hmmm... I will try, thank you! Is there a way to determine the swank server shutdown?

About server startup before image save: I need it. I'm developing a library (https://github.com/hemml/OMGlib) which helps to make web apps. To allow a Lisp-style incremental development, I want to to start a reverse proxy, which will connect users to a stable version image (spawned as a separate process), while I can perform development/debugging work on a "development" version. After the development version becomes stable enough, I want to save it (dumping the image) and it will become a new stable version (users, who are already works with previous versions will receive notification, but can continue their work before page reload, so, version commit will not affect their work).
Of course, the development version has to start http and swank servers to allow the debugging.

**Comment by luismbo** [comment]
There's `*connection-closed-hook*` though that runs before the swank thread returns. 🤔 I suppose you can wait for SWANK's Sentinel thread to exit.
