### ISSUE TITLE
defstruct name unrecognized

### ISSUE THREAD

**Issue by X01XX** [slime/slime#725]
It seems to not recognize:
(defstruct step
.....
)
I tried a few things, then changed the name to "astep", which worked.

**Comment by luismbo** [comment]
Not sure what you mean by "recognize", or why this would be a SLIME issue, but `step` is a symbol in the CL package and you can't/shouldn't use it to name a new type.

**Comment by X01XX** [comment]
Hello,

Standard functions created by defstruct, like make-step, are flagged by Slime to be unknown.

Thanks for checking.

Earl
________________________________
