### ISSUE TITLE
File Descriptor of Output and Error Streams for CFFI

### ISSUE THREAD

**Issue by digikar99** [slime/slime#742]
On SBCL, `sb-sys:fd-stream-fd` allows one to obtain the file descriptors corresponding to instances of `sb-sys:fd-stream`. However, after loading swank, 

```lisp
CL-USER> *standard-output*
#<SYNONYM-STREAM :SYMBOL SWANK::*CURRENT-STANDARD-OUTPUT* {10017285D3}>
CL-USER> swank::*current-standard-output*
#<SWANK/GRAY::SLIME-OUTPUT-STREAM {100170FF63}>
EXCL> (subtypep 'swank/gray::slime-output-stream 'sb-sys:fd-stream)
T
T
```

Inspecting the `#<SWANK/GRAY::SLIME-OUTPUT-STREAM {100170FF63}>` also did not do me any good. Would be great if someone could describe the way to obtain the file descriptors frm the streams used by swank. I'd like to pass the file descriptors to foreign functions, and potentially use them in [py4cl2/cffi](https://github.com/digikar99/py4cl2/tree/master/cffi).

**Comment by stassats** [comment]
These are not fd streams. I don't know how you managed subtypep to return T.

**Comment by digikar99** [comment]
Apologies, my mistakes for the typos in NIL vs T. But is there a way to use instances `sb-sys:fd-stream` instead of gray streams for communication between swank and slime/emacs?

**Comment by stassats** [comment]
It communicates using sockets. But the standard output for the REPL is not connected to that.
