### ISSUE TITLE
ECL: Setup error. (Apple M1 OS: 12.6）

### ISSUE THREAD

**Issue by applesnake** [slime/slime#743]
SLIME Version:2.27
;; Swank started at port: 55427.

Condition of type: SIMPLE-ERROR
SWANK/BACKEND:ADD-FD-HANDLER not implemented
Available restarts:

1. (RESTART-TOPLEVEL) Go back to Top-Level REPL.

Broken at SWANK::SETUP-SERVER. In: #<process TOP-LEVEL 0x105400f80>.
 File: "/Users/xxxxxx/slime/swank.lisp" (Position #28544)

PS：Changing inferior-lisp-program to Clouzure CL，Same error.

**Comment by stassats** [comment]
Do you have anything in ~/.swank.lisp?
