### ISSUE TITLE
Incorrect indentation in lambda lists for define-compiler-macro and define-setf-expander

### ISSUE THREAD

**Issue by galdor** [slime/slime#744]
With `lisp-indent-function` being `common-lisp-indent-function`, provided by Slime in `slime-cl-indent.el`, the following code is indented in a strange way:

```lisp
(define-compiler-macro foo (&whole form
                                   a b c
                                   &optional (d 0))
  form)
```

One would expect the following:

```lisp
(define-compiler-macro foo (&whole form
                            a b c
                            &optional (d 0))
  form)
```

The problem is the same with `&environment` in `define-setf-expander`.

`&whole` and `&environment` can only be followed by a single value; additional values are unrelated to them and should not be indented as so.

Looking at `common-lisp-init-standard-indentation`, it seems that there are no specific rules for `define-compiler-macro`, and that `define-setf-expander` is indented as `defun`.

I'm not sure how to fix this. Does anyone has an idea?

Context:
- Emacs 28.2.
- Slime 2.27.

**Comment by luismbo** [comment]
This seems to achieve your expected behaviour.

```diff
diff --git a/contrib/slime-cl-indent.el b/contrib/slime-cl-indent.el
index a620b691..7a6e4093 100644
--- a/contrib/slime-cl-indent.el
+++ b/contrib/slime-cl-indent.el
@@ -1054,7 +1054,7 @@ defun lisp-indent-report-bad-format
 (defvar lisp-indent-lambda-list-keywords-regexp
   "&\\(\
-optional\\|rest\\|key\\|allow-other-keys\\|aux\\|whole\\|body\\|\
+optional\\|rest\\|key\\|allow-other-keys\\|aux\\|body\\|\
 environment\\|more\
 \\)\\>"
   "Regular expression matching lambda-list keywords.")
@@ -1730,6 +1730,7 @@ defun common-lisp-init-standard-indentation
              (defcustom   (4 2 2 2))
              (defparameter     (as defvar))
              (defconst         (as defcustom))
+             (define-compiler-macro (as defun))
              (define-condition (as defclass))
              (define-modify-macro (4 &lambda &body))
              (defsetf      lisp-indent-defsetf)
```

**Comment by galdor** [comment]
Thank you!

I submitted a pull request to fix both issues. Regarding &WHOLE and &ENVIRONMENT, I did fix the indentation algorithm instead of just removing them from `lisp-indent-lambda-list-keywords-regexp` because the later felt like a hack which could have unintended consequences.

I'll close the issue once the PR is merged.
