### ISSUE TITLE
CMUCL: sldb-break-at-start crashes with :function-end breakpoints are currently unsupported for interpreted-debug-functions.

### ISSUE THREAD

**Issue by Enerccio** [slime/slime#758]
Steps to reproduce:

Load file containing

```
(defun argus ())
```

Then call `(swank::sldb-break-at-start 'common-lisp-user::argus)`

This will crash with `Error in function DEBUG-INTERNALS:MAKE-BREAKPOINT:    :function-end breakpoints are currently unsupported for interpreted-debug-functions.`

**Comment by luismbo** [comment]
Perhaps SLDB could handle this error more gracefully somewhere if it doesn't already, but if you're calling this function directly, you'll need to handle it yourself.
