### ISSUE TITLE
slime-describe-symbol in the doc output buffer tries to resolves symbols from the wrong package in some cases.

### ISSUE THREAD

**Issue by m-e-leypold** [slime/slime#759]
# How to reproduce

1. In lisp source invoke slime-describe-symbol on a symbol F3 at home in a package P2. The doc buffer opens and shows the doc strings.
2. Then in the buffer invoke slime-describe-symbol on a symbol P1:F1 that is at home in a different package P1.
3. Now try to invoke slime-describe-symbol on a symbol F2 (without explicit package name, that is also at home in P1). That does fail, because slime searches this symbol F2 in P2, not in P1.

I've packaged this into a minimal example with step for step instructions in the file comments and in the doc strings which will be displayed in the doc buffer => [reproduce-issue.tgz](https://github.com/slime/slime/files/10891979/reproduce-issue.tgz)

# What actually happens behind the scenes

When opening the doc buffer coming from P2 via F3, slime sets (the buffer local variable) slime-buffer-package to P2. When following P1:F1 it sets it to P2 again (or leaves it at P2) instead of setting it to P1. So it searches F2 in P2 instead of P1.

# How I think this should work

When following symbol references in doc strings in the doc buffer, they should be resolved from the "perspective" of the package Q /from which the doc string comes/. So P:S should be looked for in P, but S should be searched in Q.

**Comment by m-e-leypold** [comment]
Her is the code from the example:

# p1.lisp
```lisp
; Step 1: Load this file first with `slime-load-file', then load "p2.lisp"
;; 

(defpackage :p1
  (:use :cl)
  (:export :f1 :f2))

(in-package :p1)

(defun f1 ()
  "
  Step 5: Now invoke slime-describe-symbol on `f2': This will not
          work. ABORT the debugger.

  Step 6: While in the documentation buffer, eval-expression
          slime-buffer-package. This is set to
          :p2, not to :p1 now => Slime will look in :p2 for `f2',
          instead in :p1 where this doc string comes from.

  Step 7: For fun, now try invoking slime-describe-symbol on `f4':
          This will be found, though from the perspective of package
          :p1 it does not exist (even worse: the could be multiple
          symbols of that name in other packages, but slime will pick
          `p2:f4' because the we went from source to documentation
          buffer while we were in package :p2.

  THE END.
"
  nil)

(defun f2 ()
  "
  This symbol will not be found in step 5.  
"
  nil)
```

**Comment by stassats** [comment]
It's searched based on the current slime package.

**Comment by m-e-leypold** [comment]
It's searching based on the from which package the documentation buffer was last opened. This is recorded in the doc buffer. I know that. This is actually why I wrote this issue.

But regardless, can we talk about whether this is the right behavior? Because, with the same content in the doc buffer it means, that sometimes it can find a symbol when searching in the doc buffer, sometimes not.
When I'm invoking slime-describe-symbol from the doc-buffer, shouldn't the search be based on the package of the symbol S that is at that moment displayed in the doc buffer? So the result would be the same as if I would be at the place where this symbol S is defined as a function or variable and invoke slime-describe-symbol on the docstring from the home package of the symbol? Wouldn't that make more sense?

**Comment by m-e-leypold** [comment]
Would it help if I restate the issue like this: Yes, Slime searches based on the "current slime package", but, unfortunately sometimes has the strange (not to say wrong) idea about what the current package is.

Details:

1/ Slime's idea of "current slime package" is emacs buffer local, that is, depends on (currrent-buffer).
2/ Give two packages P1 and P2, when going into the source for P2, then invoking slime-describe-symbol of F3 (homed in P2), a documentation buffer opens. The "current slime package" in this buffer is P2. 
3/ Assume the doc string for P2:F3 contains a reference to P1:F1. Invoke slime-describe-symbol on this P1:F1 in the documentation buffer (C-c C-d C-d with point on the symbol). The documentation buffer changes and now shows the doc string (s) for P1:F1. So far everything seem proper.
4/ But now in the documentation buffer, "slime current package" is still P2. Despite the fact that it shows P1:F1.
5/ This leads to the problem that now all package local references to symbols in P1 that occur in the documentation string for P1:F1 do not work any more in the documentation buffer (when invoking slime-describe-symbol in the documentation buffer)

I posit, that (5) is wrong and simply not as expected by the (actually any) user. In the documentation buffer, slime should base the idea of "current buffer" on the symbol whose documentation is currently shown there.

Can I do anything that we have at least a conversation on this topic? Or perhaps re-open this issue?  For now I've the impression my original report was not understood. Can we fix this somehow?

**Comment by stassats** [comment]
Documentation has no concept of packages. So anything clever will break existing conventions and be confusing.
