### ISSUE TITLE
slime-pprint-eval-last-expression seems not to follow *print-circle*

### ISSUE THREAD

**Issue by Inc0n** [slime/slime#763]
Whilst it being a good help in breaking infinite cyclic structure printing.

It also make some list structure a lot harder to read.

With `*print-circle*` set to nil.  `slime-pprint-eval-last-expression` seems not to respect this variable and pretty prints the object with the circles.

Is there any immediate work arounds that can be applied?

**Comment by luismbo** [comment]
You can customize the contents of the `swank:*swank-pprint-bindings*` variable.
