### ISSUE TITLE
Slime 2.26.1: lib/hyperspec.el fails to compile on master

### ISSUE THREAD

**Issue by RuijieYu** [slime/slime#782]
hyperspec.el:1318:2: Error: Wrong number of arguments: (3 . 4), 2

The culprit is that the `define-obsolete-variable-alias` macro has been presumably changed after this code was last touched.

Adding any string as the third argument WHEN fixes the issue, where I can then load the slime package -- I tried "0" -- but I'm pretty sure it needs to be a concrete version.

**Comment by stassats** [comment]
Any reason for using  2.26.1 and not trying the latest version where this issue is fixed?

**Comment by RuijieYu** [comment]
Stas Boukarev ***@***.***> writes:

> Any reason for using 2.26.1 and not trying the latest version where this issue is fixed?

Because I'm not using Melpa, and apparently nongnu Elpa only supplies
2.26.1 as the latest version.  Even the nongnu-devel doesn't have 2.28,
for some reason.  But I'll investigate that separately, as it probably
doesn't belong to this bug report.

-- 
Best,


RY
