### ISSUE TITLE
emacs Warning (bytecomp): Unused lexical variable ‘start’

### ISSUE THREAD

**Issue by jw-rav** [slime/slime#795]
When loading slime-v2.28, emacs emits warning

  Warning (bytecomp): Unused lexical variable ‘start’

This has two unconvenient side-effects:

1. emacs splits the frame to display *Compile-Log* buffer. So one has to "C-X 1"
   to get rid of it

2. (sometimes) slime startup is aborted (I have no idea why) and all those
   buffers normally created by slime are missing.

Attached patch seems to fix the problem. But maybe the variable should be removed altogether.

**Comment by jw-rav** [comment]
Any hints how to attach the patch? I constantly get the error "We dont support that file type", no matter ehether I use X.diff, X.DIFF, X.patch or X.PATCH

[slime.txt](https://github.com/slime/slime/files/13216322/slime.txt)

(Uh, only X.txt seems to work...)

**Comment by stassats** [comment]
The usual way is to send a pull request.

**Comment by stassats** [comment]
Also that's 173aad693d7fd624aa522efe7e5ef3093480a221
