### ISSUE TITLE
slime-mdot-fu contrib broken

### ISSUE THREAD

**Issue by capitaomorte** [slime/slime#8]
bug imported from https://bugs.launchpad.net/slime/+bug/627323

The slime-mdot-fu contrib is supposed to make M-. be able to
jump to FLET/LABELS/MACROLET definitions. However it
depends on stuff that has been got ridden of after the slime-autodoc
rewrite.

It should not be too hard to adapt it/rewrite it using the new
parts.

**Comment by csziacobus** [comment]
This issue has been resolved.

**Comment by luismbo** [comment]
Closed via #231
