### ISSUE TITLE
inferior-lisp window causes wonky window layout with lisp-mode slime hook

### ISSUE THREAD

**Issue by mtstickney** [slime/slime#813]
When using the lisp-mode hook [described in the manual](https://slime.common-lisp.dev/doc/html/Auto_002dSLIME.html#Auto_002dSLIME), visiting a lisp file starts slime automatically, but instead of two windows (one for the visited file and one for the slime REPL), you end up with three:

![2024-02-28-234534_1272x697_scrot](https://github.com/slime/slime/assets/174859/5a0873d5-f7c8-4cc3-9841-dbeaf746aadf)

If the lisp-mode hook is not set up, visiting a lisp file and invoking slime manually only creates one additional window for the REPL. The additional-window business also doesn't seem to happen in console-mode, only in GUI emacs.

This is ultimately caused by the window created for the `*inferior-lisp*` buffer "stealing" the visited file buffer, which then throws off the rest of the repl setup.

### Repro

The following `init.el` contents are sufficient to produce this problem on its own, assuming you have slime checked out in the init directory. I tested this with Emacs 29.2, and slime 2.29.1, and HEAD as of this writing (commit eafb23cdaf80ef1c60558c756fcc1479aafc5325), but it's present in a version of slime from 2021 too.

```lisp
(defvar curdir (let ((path-parts (string-split load-file-name "/")))
                 (setf (car (last path-parts)) "")
                 (mapconcat 'identity path-parts "/")))

(add-to-list 'load-path (concat curdir "slime/"))
(require 'slime)

(setq slime-lisp-implementations
      '((sbcl ("sbcl" "--noinform") :coding-system utf-8-unix)))
(setq slime-default-lisp 'sbcl)

(add-hook 'lisp-mode-hook
          (lambda ()
            (save-excursion (slime))))

;; Opening a lisp file with C-x C-f or the --file arg will also trigger the problem.
(setq inhibit-startup-screen t)
(find-file "foo.lisp")
```

### Cause

As best as I can trace it down, the chain of events is this:
1. `find-file` creates a buffer for the file without showing it in the selected window; this runs the mode hook(s).
2. Slime setup begins; `slime-start` creates a new window for the `*inferior-lisp*` buffer with `pop-to-buffer`; this window is now the selected window.
3. Slime does remaining init with swank, asks for connection info, and sets up an asynchronous handler for the response.
4. `slime`, and thus the mode-hook, finish.
5. `find-file` now uses `pop-to-buffer-same-window` to show the buffer it has created for the visited file. This uses the window created for `*inferior-lisp*`, because that is now the selected window. The window `find-file` was invoked in is still sitting on the scratch buffer or whatever was there previously.
6. When swank responds with the connection info, the handler runs `slime-hide-inferior-lisp-buffer` in the slime-repl contrib, which examines the buffer and window situation. That is this:
  a. The inferior-lisp buffer exists
  b. The slime-repl buffer exists
  c. The inferior-lisp buffer has no window (it's showing the visited file buffer instead)
  d. The slime-repl buffer has no window (hasn't been created yet)
7. Since there is no existing repl window to use, and no inferior-lisp window to replace with the repl buffer, `slime-hide-inferior-lisp-buffer` uses `pop-to-buffer` to create a new window, which is now the third window in the frame.

### Possible Fixes

- One idea might be to create the `*inferior-lisp*` window without selecting it, which would prevent the visited file buffer from ending up there instead of the original window `find-file` was invoked in.
  - This would probably improve the situation, but not fix it if the window ends up selected when the repl buffer is shown (`find-file` could take a long time and end up using that window for the visited file again).
  - It's a bit of a side-note, but I was thinking it might be nice to have an way to not select the slime window by default, specifically for use with the lisp-mode hook. That would also be a workaround for this issue.
- Another idea would be to do all window manipulation in the async part of the process, so that `find-file` finishes showing the window before any of that happens.
  - I'm not actually sure that `slime-run-when-idle` is certain to only run after `find-file` completes (after a quick test, I'm reasonably sure it _doesn't_ work that way).
- ...don't use the lisp-mode hook to activate slime? I'm not sure if there's some other post-load mechanism that might be late enough to avoid some of these problems. `find-file-hooks` isn't, because that gets run before `find-file` does the pop-to-buffer (seems to be where most mode hooks happen).

Thoughts? This is my first time spelunking around in the slime code, and I'm not very familiar with emacs' window/buffer management stuff, but I can have a go at a patch if there's a reasonable approach to take.

**Comment by mtstickney** [comment]
> One idea might be to create the `*inferior-lisp*` window without selecting it, which would prevent the visited file buffer from ending up there instead of the original window find-file was invoked in.

In terms of this, a quick experiment indicates using `(display-buffer (process-buffer proc))` instead of `pop-to-buffer` in `slime-start` will do the trick of not selecting the inferior-lisp/repl window at all, although I'm not sure if that has side-effects for e.g. exotic multi-frame setups.

If the choice of `pop-to-buffer` or `display-buffer` could be wired up to something (customization variable? argument to `slime`?) that seems like it would be a good enough workaround for the lisp-mode hook use-case.

**Comment by stassats** [comment]
I can't reproduce this.

**Comment by mtstickney** [comment]
Hmm, I had this happening consistently last night (I was very happy to find a repro that didn't only happen when tool-bar-mode was disabled), but now I'm not seeing the same behavior with the minimal init. I _am_ still seeing it with a cut-down version of my regular setup.

I'll do more digging and see if I can figure out a more reliable trigger.

**Comment by mtstickney** [comment]
Wellp, touching things to investigate this has caused even my regular setup to stop exhibiting this behavior. Very probably this is related to some out-of-date bytecode that got regenerated in the process.

Guess that's one way to solve the problem. Apologies for the noise.

**Comment by mtstickney** [comment]
Just to clarify for posterity: the window "stealing" part is still happening as described here (the lisp file buffer ends up in the new window created for `*inferior-lisp*`, not the window `find-file` was invoked in), but `pop-to-buffer` is now re-using the original window for the repl buffer rather than creating a new one.
