### ISSUE TITLE
Segmentation fault when running slime with clisp in cygwin

### ISSUE THREAD

**Issue by volkers** [slime/slime#820]
I try to get started with CLISP under cygwin (Windows 10
Enterprise) but get a segmentation fault when starting slime.

I did the following:

- installed cygwin (--no-admin) and there CLISP + emacs (and some
  other stuff)
- GNU Emacs 29.2 (build 1, x86_64-pc-cygwin) of 2024-02-02
- installed in emacs package
  slime                          20240312.1427  installed             Superior Lisp Interaction Mode for Emacs
- set (setq inferior-lisp-program "clisp")
- M-x slime
- see the complete log longer down

Other tries:

- I also tested installing sbcl by using the Windows installer but then
  I get a path problem in slime:
  >> Couldn't load
  >> "/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/swank-loader.lisp":
  >> file does not exist.
  I think this is because Windows sbcl doesn't know the cygwin paths
  where I run emacs.

(No, Linux is no alternative because my customer forces me to use a
slightly crippled down Windows PC. I usually use Linux.) 

Any help appreciated!
Volker

The log:

(progn (load "/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/swank-loader.lisp" :verbose t) (funcall (read-from-string "swank-loader:init") :from-emacs t) (funcall (read-from-string "swank:start-server") "/tmp/slime.1579"))

  i i i i i i i       ooooo    o        ooooooo   ooooo   ooooo
  I I I I I I I      8     8   8           8     8     o  8    8
  I  \ `+' /  I      8         8           8     8        8    8
   \  `-+-'  /       8         8           8      ooooo   8oooo
    `-__|__-'        8         8           8           8  8
        |            8     o   8           8     o     8  8
  ------+------       ooooo    8oooooo  ooo8ooo   ooooo   8

Welcome to GNU CLISP 2.49+ (2010-07-17) <http://clisp.org/>

Copyright (c) Bruno Haible, Michael Stoll 1992, 1993
Copyright (c) Bruno Haible, Marcus Daniels 1994-1997
Copyright (c) Bruno Haible, Pierpaolo Bernardi, Sam Steingold 1998
Copyright (c) Bruno Haible, Sam Steingold 1999-2000
Copyright (c) Sam Steingold, Bruno Haible 2001-2010

Type :h and hit Enter for context help.

[1]> 
;; Loading file /home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/swank-loader.lisp ...
;; Loaded file /home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/swank-loader.lisp
;; Compiling file /home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/packages.lisp ...
;; Wrote file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/packages.fas
;; Loading file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/packages.fas ...
;; Loaded file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/packages.fas
;; Compiling file /home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/swank/backend.lisp ...
WARNING: in #:|1379 1394 (DEFINTERFACE WAIT-FOR-INPUT (STREAMS &OPTIONAL
         TIMEOUT) ...)-169-3-1-1| in lines 1379..1394 :
         SWANK:*COMMUNICATION-STYLE* is neither declared nor bound,
         it will be treated as if it were declared SPECIAL.
;; Wrote file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/backend.fas
;; Loading file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/backend.fas ...
;; Loaded file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/backend.fas
;; Compiling file /home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/xref.lisp ...
;; Wrote file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/xref.fas
;; Loading file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/xref.fas ...
;; Loaded file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/xref.fas
;; Compiling file /home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/metering.lisp ...
WARNING:  in lines 440..519 : function DELTA4-TIME is not used.
         Misspelled or missing IGNORE declaration?
;; Wrote file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/metering.fas
;; Loading file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/metering.fas ...
;; Loaded file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/metering.fas
;; Compiling file /home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/swank/clisp.lisp ...
WARNING: in ACCEPT-CONNECTION in lines 169..177 : variable BUFFERING is used
         despite IGNORE declaration.
;; Wrote file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/clisp.fas
;; Loading file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/clisp.fas ...
WARNING: DEFUN/DEFMACRO: redefining function BREAK in
         /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/clisp.fas,
         was defined in
         /home/kbrown/src/cygclisp/clisp-2.49-6.20150312hg15611.x86_64/build/condition.fas
WARNING: Replacing method #<STANDARD-METHOD (#<BUILT-IN-CLASS T>)> in
         #<STANDARD-GENERIC-FUNCTION EMACS-INSPECT>
;; Loaded file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/clisp.fas
;; Compiling file /home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/swank/gray.lisp ...
;; Wrote file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/gray.fas
;; Loading file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/gray.fas ...
WARNING: Adding method
          #<STANDARD-METHOD
            (#<STANDARD-CLASS SLIME-OUTPUT-STREAM> #<BUILT-IN-CLASS T>)>
         to an already called generic function
         #<STANDARD-GENERIC-FUNCTION STREAM-WRITE-CHAR>
WARNING: Adding method
         #<STANDARD-METHOD (#<STANDARD-CLASS SLIME-OUTPUT-STREAM>)> to an
         already called generic function
         #<STANDARD-GENERIC-FUNCTION STREAM-LINE-COLUMN>
WARNING: Adding method
         #<STANDARD-METHOD (#<STANDARD-CLASS SLIME-OUTPUT-STREAM>)> to an
         already called generic function
         #<STANDARD-GENERIC-FUNCTION STREAM-FORCE-OUTPUT>
WARNING: Adding method
         #<STANDARD-METHOD (#<STANDARD-CLASS SLIME-INPUT-STREAM>)> to an
         already called generic function
         #<STANDARD-GENERIC-FUNCTION STREAM-LINE-COLUMN>
;; Loaded file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/gray.fas
;; Compiling file /home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/swank/match.lisp ...
;; Wrote file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/match.fas
;; Loading file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/match.fas ...
;; Loaded file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/match.fas
;; Compiling file /home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/swank/rpc.lisp ...
;; Wrote file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/rpc.fas
;; Loading file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/rpc.fas ...
;; Loaded file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/rpc.fas
;; Compiling file /home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/swank.lisp ...
;; Wrote file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/swank.fas
;; Loading file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/swank.fas ...
;; Loaded file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/swank.fas
The following functions were used but not defined:
 SWANK/CLISP::FORMAT-SLDB-CONDITION
The following special variables were defined too late:
 SWANK:*COMMUNICATION-STYLE*
The following functions were used but are deprecated:

 SET - This function name is anachronistic. Use SETF SYMBOL-VALUE instead.
0 errors, 9 warnings
;; Compiling file /home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-util.lisp ...
;; Wrote file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-util.fas
0 errors, 0 warnings
;; Compiling file /home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-repl.lisp ...
;; Wrote file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-repl.fas
The following functions were used but are deprecated:

 SET - This function name is anachronistic. Use SETF SYMBOL-VALUE instead.
0 errors, 0 warnings
;; Compiling file /home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-c-p-c.lisp ...
;; Loading file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-util.fas ...
;; Loaded file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-util.fas
;; Wrote file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-c-p-c.fas
0 errors, 0 warnings
;; Compiling file /home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-arglists.lisp ...
;; Loading file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-c-p-c.fas ...
;; Loaded file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-c-p-c.fas
;; Wrote file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-arglists.fas
0 errors, 0 warnings
;; Compiling file /home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-fuzzy.lisp ...
;; Wrote file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-fuzzy.fas
0 errors, 0 warnings
;; Compiling file /home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-fancy-inspector.lisp ...
;; Wrote file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-fancy-inspector.fas
0 errors, 0 warnings
;; Compiling file /home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-presentations.lisp ...
;; Loading file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-repl.fas ...
WARNING: Replacing method
          #<STANDARD-METHOD
            (#<STRUCTURE-CLASS MULTITHREADED-CONNECTION> (EQL :FIND-EXISTING))>
         in #<STANDARD-GENERIC-FUNCTION THREAD-FOR-EVALUATION>
;; Loaded file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-repl.fas
;; Wrote file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-presentations.fas
0 errors, 1 warning
;; Compiling file /home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-presentation-streams.lisp ...
;; Loading file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-presentations.fas ...
;; Loaded file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-presentations.fas
;; Wrote file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-presentation-streams.fas
0 errors, 0 warnings
;; Compiling file /home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-package-fu.lisp ...
;; Wrote file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-package-fu.fas
0 errors, 0 warnings
;; Compiling file /home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-hyperdoc.lisp ...
;; Wrote file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-hyperdoc.fas
0 errors, 0 warnings
;; Compiling file /home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-mrepl.lisp ...
;; Wrote file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-mrepl.fas
0 errors, 0 warnings
;; Compiling file /home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-trace-dialog.lisp ...
WARNING: LOOP: FOR clauses should occur before the loop's main body
;; Wrote file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-trace-dialog.fas
0 errors, 1 warning
;; Compiling file /home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-macrostep.lisp ...
WARNING: in COLLECT-FORM-POSITIONS in lines 171..188 : variable EXPANSION is
         not used.
         Misspelled or missing IGNORE declaration?
WARNING: in COLLECT-FORM-POSITIONS in lines 171..188 : variable
         PRINTED-EXPANSION is not used.
         Misspelled or missing IGNORE declaration?
WARNING: in COLLECT-FORM-POSITIONS in lines 171..188 : variable FORMS is not
         used.
         Misspelled or missing IGNORE declaration?
;; Wrote file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-macrostep.fas
0 errors, 3 warnings
;; Compiling file /home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-quicklisp.lisp ...
;; Wrote file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-quicklisp.fas
0 errors, 0 warnings
;; Swank started at port: 52550.
CL-USER> 
;; Loading file /home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-indentation.lisp ...
WARNING: DEFUN/DEFMACRO: redefining function SYMBOL-INDENTATION in
         /home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-indentation.lisp,
         was defined in
         /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/swank.fas
WARNING: DEFUN/DEFMACRO: redefining function MACRO-INDENTATION in
         /home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-indentation.lisp,
         was defined in
         /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/swank.fas
;; Loaded file /home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-indentation.lisp
;; Loading file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-trace-dialog.fas ...
;; Loaded file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-trace-dialog.fas
;; Loading file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-package-fu.fas ...
;; Loaded file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-package-fu.fas
;; Loading file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-macrostep.fas ...
;; Loaded file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-macrostep.fas
;; Loading file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-fuzzy.fas ...
;; Loaded file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-fuzzy.fas
;; Loading file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-fancy-inspector.fas ...
;; Loaded file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-fancy-inspector.fas
;; Loading file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-arglists.fas ...
WARNING: Test failed: (&KEY #'#'+) => "(&key (function  #'+))"
         Expected: One of: "(&key (function #'+))", "(&key (function (function
         +)))"
;; Loaded file /home/Me/.slime/fasl/2.28/clisp-2.49+-unix-pc386/home/Me/.quicklisp/dists/quicklisp/software/slime-v2.28/contrib/swank-arglists.fas

Process inferior-lisp segmentation fault

**Comment by volkers** [comment]
My goal is to use the cffi interface for testing C-code. Maybe CLISP is not the right approach and I really need to use sbcl? any thoughts?

Regards
Volker

**Comment by luismbo** [comment]
Fault probably lies with CLISP as it is currently unmaintained.

My suggestion is to use SBCL and the official Emacs for Windows. You'll still be able to invoke cygwin (or MSYS2) tools from Emacs, although you might need some extra fiddling with PATHs.
