### ISSUE TITLE
Setting `sly-lisp-implementations` to a command that has quotes

### ISSUE THREAD

**Issue by aadcg** [slime/slime#822]
The following commands are valid ways to start lisp:

- `nix-shell -p sbcl --run "sbcl --dynamic-space-size 3072"`
- `nix-shell -p sbcl --run 'sbcl --dynamic-space-size 3072'`

However:

`C-u M-x sly RET nix-shell -p sbcl --run "sbcl --dynamic-space-size 3072" => OK` 
`C-u M-x sly RET nix-shell -p sbcl --run 'sbcl --dynamic-space-size 3072' => error: unrecognised flag '--dynamic-space-size'`

If we add to `sly-lisp-implementations`:
- `(test1 ("nix-shell" "-p" "sbcl" "--run" "'sbcl --dynamic-space-size 3072'"))`
- `(test2 ("nix-shell" "-p" "sbcl" "--run" "\"sbcl --dynamic-space-size 3072\""))`

`M--- M-x sly RET test1 => /tmp/nix-shell-9574-0/rc: line 3: sbcl --dynamic-space-size 3072: command not found` 
`M--- M-x sly RET test2 => /tmp/nix-shell-10951-0/rc: line 3: sbcl --dynamic-space-size 3072: command not found`

------

At the heart of these bugs lies:

```
(start-process "test" (get-buffer-create "test") "nix-shell" "-p" "sbcl" "--run" "'sbcl --dynamic-space-size 3072'")
=> (opens a buffer called test):
/tmp/nix-shell-13722-0/rc: line 3: sbcl --dynamic-space-size 3072: command not found

Process test<1> exited abnormally with code 127

```

I wonder if there's a way for `start-process` to handle the quotes.

**Comment by stassats** [comment]
This is not sly.

```(setf slime-lisp-implementations '((test1 ("sh" "-c" "sbcl --dynamic-space-size 3072"))))```

works.
