### ISSUE TITLE
Swank/gray not loading if I am using emacs with slime at 2.30

### ISSUE THREAD

**Issue by sabracrolleton** [slime/slime#827]
Everything compiles running sbcl from the command line. 

However, if I try (ql:quickload :swank) while running slime 2.30 in emacs, it hangs when loading swank/gray. (Using ultralisp, so pulling the most recent version of swank).

**Comment by luismbo** [comment]
Reloading SWANK while running SWANK seems like a recipe for trouble. 🤔

**Comment by stassats** [comment]
Yes. Don't do that.

**Comment by sabracrolleton** [comment]
I do NOT WANT to do that. BUT swank is a dependency for clack and clack is a dependency for clog. So I am forced into it.

**Comment by sabracrolleton** [comment]
Or rather, now that I finally figured out what was happening, I put a copy of slime-2.30 into quicklisp/local-projects and everything is happy again. 

Not a bug in slime, just a consequence of different versions.
