### ISSUE TITLE
After an error, output is only displayed after interrupt in 2.30

### ISSUE THREAD

**Issue by lamuswawir** [slime/slime#828]
I am running slime 2.30, on Ubuntu 24.04 and SBCL 2.4.4 and emacs 29.3. When an error is encountered, the next function call will only print output after interrupting. Before interrupting, there is no information printed, and the debugger will only be brought after the interruption. It appears to enter an infinite loop. I first encountered the issue of FreeBSD, where I solved it by using 2.60 for ports. The backtrace is shown below and the error given off is SIMPLE-ERROR. 

`("bogus stack frame")
  (SB-UNIX:UNIX-SIMPLE-POLL 0 :INPUT -1)
 (SB-SYS:WAIT-UNTIL-FD-USABLE 0 :INPUT NIL T)
 (SB-IMPL::REFILL-INPUT-BUFFER #<SB-SYS:FD-STREAM for "standard input" {1003F3B833}>)
 (SB-IMPL::INPUT-CHAR/UTF-8/LF #<SB-SYS:FD-STREAM for "standard input" {1003F3B833}> NIL 0)
 (READ-CHAR #<SB-SYS:FD-STREAM for "standard input" {1003F3B833}> NIL 0 #<unused argument>)
 (READ-CHAR #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDIN* {10000201E3}> NIL 0 #<unused argument>)
 (READ-CHAR #<SYNONYM-STREAM :SYMBOL SWANK::*CURRENT-STANDARD-INPUT* {10014CAFD3}> NIL 0 #<unused argument>)
 (SB-IMPL::%READ-PRESERVING-WHITESPACE #<SYNONYM-STREAM :SYMBOL SWANK::*CURRENT-STANDARD-INPUT* {10014CAFD3}> NIL (NIL) T)
 (SB-IMPL::%READ-PRESERVING-WHITESPACE #<SYNONYM-STREAM :SYMBOL SWANK::*CURRENT-STANDARD-INPUT* {10014CAFD3}> NIL (NIL) NIL)
 (READ #<SYNONYM-STREAM :SYMBOL SWANK::*CURRENT-STANDARD-INPUT* {10014CAFD3}> NIL (NIL) NIL)
 (SB-IMPL::REPL-READ-FORM-FUN #<SYNONYM-STREAM :SYMBOL SWANK::*CURRENT-STANDARD-INPUT* {10014CAFD3}> #<unused argument>)
 (SB-IMPL::REPL-FUN NIL)
 ((LAMBDA NIL :IN SB-IMPL::TOPLEVEL-REPL))
 (SB-IMPL::%WITH-REBOUND-IO-SYNTAX #<FUNCTION (LAMBDA NIL :IN SB-IMPL::TOPLEVEL-REPL) {7C8491BFFC1B}>)
 (SB-IMPL::TOPLEVEL-REPL NIL)
 (SB-IMPL::TOPLEVEL-INIT)
 ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
 ((FLET "WITHOUT-INTERRUPTS-BODY-3" :IN SB-IMPL::START-LISP))
 (SB-IMPL::%START-LISP)  0: ("bogus stack frame")
 (SB-UNIX:UNIX-SIMPLE-POLL 0 :INPUT -1)
 (SB-SYS:WAIT-UNTIL-FD-USABLE 0 :INPUT NIL T)
  (SB-IMPL::REFILL-INPUT-BUFFER #<SB-SYS:FD-STREAM for "standard input" {1003F3B833}>)
 (SB-IMPL::INPUT-CHAR/UTF-8/LF #<SB-SYS:FD-STREAM for "standard input" {1003F3B833}> NIL 0)
 (READ-CHAR #<SB-SYS:FD-STREAM for "standard input" {1003F3B833}> NIL 0 #<unused argument>)
  (READ-CHAR #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDIN* {10000201E3}> NIL 0 #<unused argument>)
 (READ-CHAR #<SYNONYM-STREAM :SYMBOL SWANK::*CURRENT-STANDARD-INPUT* {10014CAFD3}> NIL 0 #<unused argument>)
 (SB-IMPL::%READ-PRESERVING-WHITESPACE #<SYNONYM-STREAM :SYMBOL SWANK::*CURRENT-STANDARD-INPUT* {10014CAFD3}> NIL (NIL) T)
 (SB-IMPL::%READ-PRESERVING-WHITESPACE #<SYNONYM-STREAM :SYMBOL SWANK::*CURRENT-STANDARD-INPUT* {10014CAFD3}> NIL (NIL) NIL)
 (READ #<SYNONYM-STREAM :SYMBOL SWANK::*CURRENT-STANDARD-INPUT* {10014CAFD3}> NIL (NIL) NIL)
 (SB-IMPL::REPL-READ-FORM-FUN #<SYNONYM-STREAM :SYMBOL SWANK::*CURRENT-STANDARD-INPUT* {10014CAFD3}> #<unused argument>)
 (SB-IMPL::REPL-FUN NIL)
 ((LAMBDA NIL :IN SB-IMPL::TOPLEVEL-REPL))
 (SB-IMPL::%WITH-REBOUND-IO-SYNTAX #<FUNCTION (LAMBDA NIL :IN SB-IMPL::TOPLEVEL-REPL) {7C8491BFFC1B}>)
 (SB-IMPL::TOPLEVEL-REPL NIL)
 (SB-IMPL::TOPLEVEL-INIT)
  ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
 ((FLET "WITHOUT-INTERRUPTS-BODY-3" :IN SB-IMPL::START-LISP))
 (SB-IMPL::%START-LISP)`

**Comment by lamuswawir** [comment]
I have just downgraded to 2.28 installed on Ubuntu via apt. I can confirm that it is an issue with version 2.30. 2.28 works fine.

**Comment by amos1969** [comment]
I have just encountered the same problem using SBCL 2.4.4, SLIME 2.30 (installed via MELPA) and EMACS 29.3 on Kubuntu 23.10.

**Comment by luismbo** [comment]
I haven't been able to replicate this but perhaps I didn't understand the scenario. Do you have some example code?

**Comment by amos1969** [comment]
> I haven't been able to replicate this but perhaps I didn't understand the scenario. Do you have some example code?

Hi  Luis

1. Start a new instance of Slime.
2. In the REPL trigger an error (I did `(print hi)`).
3. Choose the `[abort]` option to Exit the debugger.
4. Back in the REPL run some code that should work (I did `(print "hi")`).
5. This appears to cause the REPL to hang and there is no response initially.
6. Use `C-c C-c` to interrupt the REPL which outputs the following stacktrace:

```
Interrupt from Emacs
   [Condition of type simple-error]

Restarts:
 0: [continue] Continue from break.
 1: [abort] Exit debugger, returning to top level.

Backtrace:
  0: ("bogus stack frame")
  1: (sb-unix:unix-simple-poll 0 :input -1)
  2: (sb-sys:wait-until-fd-usable 0 :input nil t)
  3: (sb-impl::refill-input-buffer #<sb-sys:fd-stream for "standard input" {1003F46833}>)
  4: (sb-impl::input-char/utf-8/lf #<sb-sys:fd-stream for "standard input" {1003F46833}> nil 0)
  5: (read-char #<sb-sys:fd-stream for "standard input" {1003F46833}> nil 0 #<unused argument>)
  6: (read-char #<synonym-stream :SYMBOL sb-sys:*stdin* {10000201E3}> nil 0 #<unused argument>)
  7: (read-char #<synonym-stream :SYMBOL swank::*current-standard-input* {1001482FD3}> nil 0 #<unused argument>)
  8: (sb-impl::%read-preserving-whitespace #<synonym-stream :SYMBOL swank::*current-standard-input* {1001482FD3}> nil (nil) t)
  9: (sb-impl::%read-preserving-whitespace #<synonym-stream :SYMBOL swank::*current-standard-input* {1001482FD3}> nil (nil) nil)
 10: (read #<synonym-stream :SYMBOL swank::*current-standard-input* {1001482FD3}> nil (nil) nil)
 11: (sb-impl::repl-read-form-fun #<synonym-stream :SYMBOL swank::*current-standard-input* {1001482FD3}> #<unused argument>)
 12: (sb-impl::repl-fun nil)
 13: ((lambda nil :in sb-impl::toplevel-repl))
 14: (sb-impl::%with-rebound-io-syntax #<function (lambda nil :in sb-impl::toplevel-repl) {766912DFFC1B}>)
 15: (sb-impl::toplevel-repl nil)
 16: (sb-impl::toplevel-init)
 17: ((flet sb-unix::body :in sb-impl::start-lisp))
 18: ((flet "WITHOUT-INTERRUPTS-BODY-3" :in sb-impl::start-lisp))
 19: (sb-impl::%start-lisp)
```
7. The interrupt causes the `(print "hi")` to complete evaluation.
8. Running further code in the REPL triggers the same behaviour. I have to close Slime and start a new instance of it to make it behave.

**Comment by stassats** [comment]
Are you selecting the wrong abort restart?
