### ISSUE TITLE
Slow output in Allegro CL

### ISSUE THREAD

**Issue by dieggsy** [slime/slime#831]
Here's a test case:
```
(print (make-list 7862 :initial-element "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"))
```
In SBCL, this outputs near instantly. In Allegro CL 11, it takes a really long time to finish.

Curiously, the following is  about equally responsive in both:
```
(mapcar #'print (make-list 7862 :initial-element "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"))
```

**Comment by stassats** [comment]
It can't sleep for short periods of time:
https://franz.com/support/documentation/11.0/multiprocessing.html#90-clsleep-and-minimum-sleeping-time

**Comment by dieggsy** [comment]
Thank you for the quick turnaround on this and #830!
