### ISSUE TITLE
Need help understanding swank backend error during compile of swank

### ISSUE THREAD

**Issue by rabbibotton** [slime/slime#834]
This on Windows amd64 sbcl

I only see warnings and then the build interrupts. Any idea what is causing this or how I can find issue?

; file: C:/Users/david/projects/rtest/systems/slime-2.30/swank/sbcl.lisp
; in: DEFUN INPUT-READY-P
;     (SB-BSD-SOCKETS-INTERNAL::FD->HANDLE (SB-SYS:FD-STREAM-FD STREAM))
;
; caught WARNING:
;   The function SB-BSD-SOCKETS-INTERNAL::FD->HANDLE has been deprecated as of SBCL version 1.2.10.
;
;   In future SBCL versions SB-BSD-SOCKETS-INTERNAL::FD->HANDLE will signal a
;   runtime error.
;   See also:
;     The SBCL Manual, Node "Deprecation Conditions"

; in: DEFVAR *SHEBANG-READTABLE*
;     (LAMBDA (STREAM CHAR) (VALUES))
;
; caught STYLE-WARNING:
;   The variable STREAM is defined but never used.
;
; caught STYLE-WARNING:
;   The variable CHAR is defined but never used.

; wrote C:/Users/david/AppData/Local/cache/common-lisp/sbcl-2.4.6-win-x64/C/Users/david/projects/rtest/systems/slime-2.30/swank/sbcl-tmpB7NPDQCW.fasl
; compilation finished in 0:00:01.641

debugger invoked on a UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread
#<THREAD tid=23320 "main thread" RUNNING {1000110093}>:
  COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "swank" "backend" "sbcl">

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     compiling #<CL-SOURCE-FILE "swank" "backend" "sbcl">.
  1: [ACCEPT                       ] Continue, treating
                                     compiling #<CL-SOURCE-FILE "swank" "backend" "sbcl">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4:                                 Retry ASDF operation.
  5:                                 Retry ASDF operation after resetting the
                                     configuration.
  6: [CONTINUE                     ] Ignore runtime option --eval "(asdf:load-system :clog/tools)".
  7: [ABORT                        ] Skip rest of --eval and --load options.
  8:                                 Skip to toplevel READ/EVAL/PRINT loop.
  9: [EXIT                         ] Exit SBCL (calling #'EXIT, killing the process).

(UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "swank" "backend" "sbcl">)))
   error finding frame source: Bogus form-number: the source file has probably
                               changed too much to cope with.
   source: NIL
0]

**Comment by luismbo** [comment]
compile-file returns failure due to the WARNING and ASDF fails compilation.
You can tell ASDF not to do that with a special variable and some other
ways.

**Comment by rabbibotton** [comment]
I never heard of warnings being the cause of a compilation to stop and there are a maybe 30 before it. What are the special variables and other ways? Since no other warnings are stopped.

**Comment by stassats** [comment]
`asdf:*compile-file-failure-behaviour*`

**Comment by rabbibotton** [comment]
very appreciated, looking

**Comment by rabbibotton** [comment]
Fantastic worked!

**Comment by stassats** [comment]
We could resolve all the warnings, but... lazy.
