### ISSUE TITLE
Version header is invalid

### ISSUE THREAD

**Issue by darkfeline** [slime/slime#839]
The version header is invalid:

```
;; Version: 2.30.dev
```

Specifically, the builtin function `version-to-list` which Emacs uses to parse this doesn't support the `.dev`.

**Comment by stassats** [comment]
Why does it work fine then?

**Comment by darkfeline** [comment]
The version header is used by `package.el`, so you won't notice anything if you load or install SLIME via other methods.

**Comment by stassats** [comment]
i'd prefer "git" to "alpha"

**Comment by darkfeline** [comment]
> i'd prefer "git" to "alpha"

sounds good
