### ISSUE TITLE
Don't abbreviate the REPL prompt poorly

### ISSUE THREAD

**Issue by cgay** [slime/slime#843]
Hi. SLIME sometimes [abbreviates](https://github.com/slime/slime/blob/7db8c0ac2da2978fcb85313ad0a222e3a323fdaf/swank.lisp#L1905) the REPL prompt poorly, for example changing `CLACK.TEST>` to just `TEST>`.  What do you think about defaulting `swank::*auto-abbreviate-dotted-packages*` to `NIL`?

Or, alternatively, make the prompt code even more complicated and disallow certain common leaf names like `TEST`?

Of course I can set the variable to `NIL` in my init file, but this seemed like a poor default to me, hence the bug report. I'd be happy to send a PR.

**Comment by luismbo** [comment]
I don't like the default either, so I'd accept that pull request.

**Comment by cgay** [comment]
This variable should be exported and [documented](https://slime.common-lisp.dev/doc/html/Other-configurables.html).

**Comment by luismbo** [comment]
Or silently deprecated and removed, maybe. 😏

**Comment by cgay** [comment]
That works for me, but I'm new here and I'm not sure if it would be ill-received by the community. Is there any way to take a poll?  But if you say "go for it", I'm happy to do it.

**Comment by stassats** [comment]
I say go for it as well. Slime is not a library, we can break stuff more freely.

**Comment by stassats** [comment]
You can redefine swank:package-string-for-prompt, nothing wrong with that. We can't really accommodate all custom use-cases, and, this being lisp, things are easily redefined. 
Maybe a more interesting option would be to make the prompt into > and show the package in the mode-line, à la lisp-mode buffers.

**Comment by fiddlerwoaroof** [comment]
I liked this too, but it would be more useful for there to be a hook to customize the prompt anyways.
